### ISSUE TITLE
Why delay when shutting down?

### ISSUE THREAD

**Issue by raelb** [salvadordf/CEF4Delphi#10]
Just curious why there is a delay of about 2 seconds when the application is closed. Other implementations (e.g. DCEF3, CefSharp) seem to be able to close immediately. 
I wonder if this is something that could be improved?
Thanks

**Comment by salvadordf** [comment]
In multitabbed applications like BriskBard I must follow the steps described in the comments of cef_life_span_handler_t::do_close (include/capi/cef_life_span_handler_capi.h) to close each tab or popup window. I followed those steps but I had some unexpected crashes when I tested some websites with heavy use of flash on my old computer. The solution was to add a small delay after all those steps and then destroy the tab.
I'll keep looking for a more cleaner solution.
