### ISSUE TITLE
Please confirm: Create and Free of GlobalCEFApp.

### ISSUE THREAD

**Issue by Ruffo324** [salvadordf/CEF4Delphi#101]
On my tests i found out, that there is a other possible  way you can Create and Free the GlobalCEFApp.
Instead of createing it in the **.dpr** file around the **Application.Initalize** you can use the following:
(The example is an excerpt of my project work for my degree. Project topic: Conception and programming of a component for the integration of different web browser frameworks.)

**Creation**
```Delphi
....

// @GitHub (The create is called if the Web-Browser is needed on a form)
constructor TAdvChromeEmbeddedFrameworkBrowser.Create(AOwner: TComponent);
begin  
  // Chrome Embedded Framework Main instance If necessary, instantiate. 
  if (not Assigned(GlobalCEFApp)) then begin
    GlobalCEFApp := TCefApplication.Create();

    // Wait for Main Process and Context.    
    while not GlobalCEFApp.StartMainProcess() do begin end;
    while not GlobalCEFApp.GlobalContextInitialized do begin end;
  end;

...
```

**Free**
```Delphi
.... 
finalization
begin
  FreeAndNil(GlobalCEFApp);
end;
end.
...
```

Works like a charm,
Can you confirm this solution?

**Comment by salvadordf** [comment]
In theory, you can delay the GlobalCEFApp creation if you use a different EXE for the subprocesses. The code in TAdvChromeEmbeddedFrameworkBrowser.Create is using the same EXE for the subprocesses and that will generate problems.

Let's continue this conversation in the forum : 
https://www.briskbard.com/forum/
