### ISSUE TITLE
question: call window.external.MyMethod();

### ISSUE THREAD

**Issue by boomsya** [salvadordf/CEF4Delphi#103]
hi. Can i ask for your help?
i need register method MyMethod in any one demo project and call method in JS: `window.external.MyMethod();`

can you show me how can i do this in this component?

**Comment by salvadordf** [comment]
Several demos inside the "demos\JavaScript" directory show you how to register functions that can be used in JS. 

The **JSWindowBindingWithFunction** demo registers a function called "myfunc". Build that demo, run it and click the "Click me" button to see the results.

Please, for questions use our forum : 
https://www.briskbard.com/forum/

**Comment by boomsya** [comment]
thanks. I have already found this demo JSWindowBindingWithFunction too :) all works fine
