### ISSUE TITLE
Build an install error

### ISSUE THREAD

**Issue by DobraMorda** [salvadordf/CEF4Delphi#104]
Hello!

I made everything agree with instruction of installation from site:
https://www.briskbard.com/index.php?lang=en&pageid=cef

and when I click on build i get this error:
[dcc32 Fatal Error] uCEFChromium.pas(51): E2225 Never-build package 'vcl' must be recompiled

Someones has an idea?

Best Regards!
DobraMorda

EDIT
Delphi Version: 10.2.2 Tokyo

**Comment by salvadordf** [comment]
I've never seen that error message but try this : 
https://stackoverflow.com/questions/17114206/delphi-xe-bogus-never-build-package-must-be-recompiled-f2084-internal-erro
https://www.devexpress.com/Support/Center/Question/Details/B20715/e2225-never-build-package-cxeditorsd11-must-be-recompiled

**Comment by DobraMorda** [comment]
I tried it earlier, but not works.

The problem is that in file uCEFChromium the compiler not see Vcl.Controls nad Vcl.Forms in uses section. This is very strange, becouse i'm using alot of componenct in very complicated projects and never get this like error.

**Comment by salvadordf** [comment]
Maybe it's a conditional compilation problem. Have you tried simplifying the uses section? 
 
`uses
 WinApi.Windows, WinApi.Messages, Vcl.Controls, Vcl.Graphics, Vcl.Forms, WinApi.ActiveX, System.Classes,
  uCEFTypes, uCEFInterfaces, uCEFLibFunctions, uCEFMiscFunctions, uCEFClient,
  uCEFConstants, uCEFTask, uCEFDomVisitor, uCEFChromiumEvents,
  uCEFChromiumOptions, uCEFChromiumFontOptions, uCEFPDFPrintOptions, uCEFDragAndDropMgr;`

**Comment by DobraMorda** [comment]
Yes, i tried it. 

Is this a valid path?
C:\Users\<me>\Documents\Embarcadero\Studio\Projects\Komponenty\Chromium\CEF4Delphi-master\source\

**Comment by DobraMorda** [comment]
The best info is that the Vcl.Graphics is visible and when i click "Find the declaration" that environment open this file. The problem is with Vcl.Controls and Vcl.Forms...

**Comment by salvadordf** [comment]
If I remember correctly, old Delphi versions had a maximum library path length. Maybe Delphi 10.2.2 still has this limitation. Try making it shorter.

**Comment by DobraMorda** [comment]
Nope. I got JEDIvcl which has longer path and it works.

**Comment by salvadordf** [comment]
I meant the total library path length. You can shorten all paths in your "Projects" directory replacing "C:\Users<me>\Documents\Embarcadero\Studio\Projects" by $(BDSPROJECTSDIR)

In your last example it would be : 
$(BDSPROJECTSDIR)\Komponenty\Chromium\CEF4Delphi-master\source\

If you have many components try adding $(BDSPROJECTSDIR) to all the paths in your "Projects" directory and make sure all the paths are correct by clicking the "Folder" button.

Make a copy of your library path before testing all this!!!!

**Comment by DobraMorda** [comment]
Ok. Resolved.

I uninstall my Rad Studio 10.2.2 and install new version - 10.2.3.

After install everything works.

Now I'm looking for why Chromium DB not work (WebSQL)...
