### ISSUE TITLE
How can I use CommandLine?

### ISSUE THREAD

**Issue by rubinho241180** [salvadordf/CEF4Delphi#11]
Hi, sorry my bad english...
My name is Rubens and... firstly,  congratulations for the project.

I use another dcef3 soluction and I use CommandLine like this:

```
procedure OnBeforeCommandLine(const  processType: ustring; const  commandLine: ICefCommandLine);
begin
  commandline.AppendSwitch('--use-fake-ui-for-media-stream');
  commandline.AppendSwitch('--enable-media-stream');
  commandline.AppendSwitch('--disable-notifications');

end;


initialization

  DcefBApp.OnBeforeCommandLineProcessing := OnBeforeCommandLine;

end.
```

How can I use CommandLine in CEF4Delphi?

Thank you!

**Comment by salvadordf** [comment]
Download the latest version of CEF4Delphi and add all your switches using the TCEFApplication.AddCommandLine procedure

**Comment by rubinho241180** [comment]
Some Commands that need  parameter don't work...

In another dcef3 soluction I used:
commandline.AppendSwitchWithValue('--touch-events', 'disabled');

In Dcef4Delphi I tryed:
GlobalCEFApp.AddCustomCommandLine('--touch-events=disabled');

Isn't one, but all commands that need parameter i tested and do not work.

Thanks!!!
