### ISSUE TITLE
App hangs when exit

### ISSUE THREAD

**Issue by thachngopl** [salvadordf/CEF4Delphi#111]
Hi @salvadordf 

First, I would like to say thank you for all your works :+1: 

Please see the attachment for the source code: 
[New folder.zip](https://github.com/salvadordf/CEF4Delphi/files/1998516/New.folder.zip)

Step to reproduce:
1) Open the app
2) Click "Button 1"
3) Close the modal form
4) Close the main form
5) => App hangs

OS: Win7 x64, app x32, Cef4delphi: latest

Thank you very much

**Comment by salvadordf** [comment]
Please, don't use the single process mode unless you really need it to debug some code that would be executed in the render process normally. The single process mode is unsupported and it's known to cause errors and access violations.

If you need a browser in a child window use the "**ToolBoxBrowser**" demo as a template for your app. It's very important that your app waits until all browsers are correctly closed before closing the main form. Read the code comments in the ToolBoxBrowser demo to know the details.

**Comment by thachngopl** [comment]
Thank you for your help. I will turn the single process mode off.

**Comment by salvadordf** [comment]
GlobalCEFApp.ChildProcessesCount has the number of child processes but this is not the best way to close an application that uses CEF4Delphi. 

Check all these : 
- All the browsers **must** be destroyed following the "destruction sequence" described in the code comments of the demo you used as a template for your application.
- Make sure you don't mix classes with interfaces. If you use a local variable declared as a CEF4Delphi class, declare it as the CEF4Delphi interface that the class is implementing.
- Avoid circular references in the interfaces.
- If your app uses URLRequests you must cancel all active requests before closing your app.

Please, use our forums if you have more questions : 
https://www.briskbard.com/forum/
