### ISSUE TITLE
Lazarus: empty TChromium.RetrieveHTML or TChromium.RetrieveText

### ISSUE THREAD

**Issue by andersonbiz** [salvadordf/CEF4Delphi#112]
Hello,
Thanks a lot for porting this to Lazarus!

On Lazarus, when call TChromium.RetrieveHTML or TChromium.RetrieveText the "aText" variable returns empty on TChromium.OnTextResultAvailable event.

On Delphi it works perfectly.

Regards,

**Comment by salvadordf** [comment]
Most of the CEF4Delphi strings are "ustrings" and that means that they are UnicodeStrings. 
You need to convert them to AnsiStrings using UTF8Encode or some other function.
