### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by kingdjf** [salvadordf/CEF4Delphi#115]
when i running SimpleBrowser.dproj into Delphi tokyo ,i get below error, let's look at the picture.
![image](https://user-images.githubusercontent.com/20849778/40481648-a2094b68-5f84-11e8-8f48-af80c0a70f52.png)

![image](https://user-images.githubusercontent.com/20849778/40481603-7d8435c8-5f84-11e8-826a-f87bf99b4562.png)
![image](https://user-images.githubusercontent.com/20849778/40481680-b92e56da-5f84-11e8-993d-f0b644ce5606.png)

i use the dll from folder [cef_binary_3.3359.1774.gd49d25f_windows32]
![image](https://user-images.githubusercontent.com/20849778/40481801-196f137c-5f85-11e8-962d-56c91815d52f.png)

copy folder Release all the files into CEF4Delphi folder bin
![image](https://user-images.githubusercontent.com/20849778/40482010-d560ccce-5f85-11e8-9106-5d8a6c19af0d.png)

**Comment by salvadordf** [comment]
Please, download the latest version of CEF4Delphi and try that demo again. The last update includes some destruction changes that might help you.
If you still get that error with the new version please use the forum to report it and provide a detailed step-by-step description of that error.
https://www.briskbard.com/forum
