### ISSUE TITLE
getElementById

### ISSUE THREAD

**Issue by EasyVizi** [salvadordf/CEF4Delphi#123]
Hello, I can't find DOMVisitor_OnDocAvailable function in MiniBrowser.dpr file, and can't find it in all project. (it's example for using getElementById, src = https://github.com/salvadordf/CEF4Delphi/issues/20)
Pls, tell me, how or where can i find example?

**Comment by salvadordf** [comment]
The code has changed during the last year. All the functions are now in the **uDOMVisitor.pas** file 
https://github.com/salvadordf/CEF4Delphi/blob/2db1a72deb090213e30c088a21842843c26c9108/demos/DOMVisitor/uDOMVisitor.pas#L218
