### ISSUE TITLE
TextSelectionChanged event is not fired

### ISSUE THREAD

**Issue by thachngopl** [salvadordf/CEF4Delphi#124]
Hi,

I trying to get selected text in the page. I added this line into TextSelectionChanged event of MiniBrowser example. But it not fired:
```pascal
  CodeSite.Send('Chromium1TextSelectionChanged', selected_text);
```

**Comment by salvadordf** [comment]
The TChromium.OnTextSelectionChanged event is only triggered in OSR mode. 
To get the selected text you can use the code in the DOMVisitor demo. 
The DOMVisitor_OnDocAvailable function in uDOMVisitor.pas uses ICefDomDocument.SelectionAsText to save it in the log but you can send it back to the browser process.

**Comment by thachngopl** [comment]
Thank you very much
