### ISSUE TITLE
Problem to execute javascript of the page

### ISSUE THREAD

**Issue by josea2019** [salvadordf/CEF4Delphi#127]
When you put the url "http://www.emisora.org.es/cadena-cien/" in the Chrome browser, the audio playback button is automatically executed, however in "SimpleBrowser2" you have to click on the button to start playing the audio.
Is there any way to solve this problem?
Thanks for your help.
Best regards,
Jose A.Molina

**Comment by salvadordf** [comment]
That's the default "autoplay policy" in Chromium : https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

To enable autoplay add this code before the GlobalCEFApp.StartMainProcess call in the DPR : 
`GlobalCEFApp.AddCustomCommandLine('--autoplay-policy', 'no-user-gesture-required');`

**Comment by josea2019** [comment]
Yes. It is perfect. You are a crack.
Thank you very much for your help.
