### ISSUE TITLE
How can I use DLL's and Resource files in another folder?

### ISSUE THREAD

**Issue by rubinho241180** [salvadordf/CEF4Delphi#13]
Hi,
How can I use dlls and resource files in different EXE folder?

Like this:

```
  CefCache := 'cef\__cache';
  CefLibrary := 'cef\libcef.dll';
  CefResourcesDirPath := 'cef\';
  CefLocalesDirPath   := 'cef\locales\';


```

I tried this bu don't work:
```
  GlobalCEFApp.Library := 'cef\libcef.dll'; <---- ???? This property "Library" do not exists
  GlobalCEFApp.FrameworkDirPath := 'cef\';
  GlobalCEFApp.ResourcesDirPath := 'cef\';
  GlobalCEFApp.LocalesDirPath   := 'cef\locales\';
```

In my project structure I separated my main EXE from another files (DLLs/resources).

Thank you!!!

**Comment by salvadordf** [comment]
Download CEF4Delphi again. I just added your suggestion and now you can set a customized location for libcef.dll using the GlobalCEFApp.LibCef property. Thanks! :smile: 

About the FrameworkDirPath, the CEF3 source comments say that "_The path to the CEF framework directory on macOS._" and Marshall Greenblatt said this at the CEF3 forum : 

> The expected path for icudtl.dat and *.bin files is hard-coded in Chromium and cannot be configured. 

http://magpcss.org/ceforum/viewtopic.php?f=6&t=14873&p=33742#p33742

**Comment by raelb** [comment]
Can you describe how this function should be used?

In my .dpr file I have:
 
>   GlobalCEFApp := TCefApplication.Create;
  GlobalCEFApp.LibCef := 'cef\libcef.dll';
  GlobalCEFApp.ResourcesDirPath := 'cef\\';
  GlobalCEFApp.LocalesDirPath   := 'cef\locales\\';

My dir structure is as follows:

Exe folder:
> cef [folder]
guiclient.exe
icudtl.dat
natives_blob.bin
snapshot_blob.bin

Cef subfolder:
> locales
cef.pak
cef_100_percent.pak
cef_200_percent.pak
cef_extensions.pak
chrome_elf.dll
d3dcompiler_43.dll
d3dcompiler_47.dll
devtools_resources.pak
libcef.dll
libcef.lib
libEGL.dll
libGLESv2.dll
widevinecdmadapter.dll

I receive CEF binaries missing when I run the app.

**Comment by salvadordf** [comment]
I made some more tests setting GlobalCEFApp.CheckCEFFiles := False; to skip the file checking and it seems that the only files you can move safely are the locales. The moment you try to use another directory for the resources or the DLLs you'll get a crash in CEF3 initialization.

**Comment by rubinho241180** [comment]
Before, I used "https://github.com/hgourvest/dcef3" (very old) and I cold do it like this:
```
CefLibrary := 'cef\libcef.dll';
CefResourcesDirPath := 'cef\';
CefLocalesDirPath   := 'cef\locales\';
```
I wanna to separate my main executable from the other cef files, like this:
```
[app_folder]
     app.exe
     [app_folder\cef_folder]
          cef_files.*
          [app_folder\cef_files_folder\locales_folder]
               locales_files.*
```

And all my distributed projects are working this way, is it just like the dcef3 I mentioned, could you add that possibility?

Very Thanks!!!!,

**Comment by salvadordf** [comment]
After some more test I could move a few more files but you have to use complete paths. With this settings you can move all but 5 files.
  GlobalCEFApp.FrameworkDirPath := 'k:\cef\';  // FULL PATH
  GlobalCEFApp.ResourcesDirPath := 'k:\cef\';  // FULL PATH
  GlobalCEFApp.LocalesDirPath := 'k:\cef\locales\';  // FULL PATH

K: iss a custom drive unit. Use whatever you want as long it's a full path.

The files that I couldn't move from the application directory were : icudtl.dat, natives_blob.bin, snapshot_blob.bin, libcef.dll and chrome_elf.dll. 

I could move all the *.pak files, locales and the rest of the DLLs.
