### ISSUE TITLE
Lost UI shared context

### ISSUE THREAD

**Issue by samchild** [salvadordf/CEF4Delphi#137]
Hi,  
when i create a console application to call the procedure InitializeCEF4Delphi of DLLBrowser.dll ( the DLLBrowser demo project ), it says  :
[1025/144702.999:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

![image](https://user-images.githubusercontent.com/12930061/47481222-7faada00-d865-11e8-90e1-337ba5c2fdf4.png)

what can i do  to make it work in console application , please?

**Comment by salvadordf** [comment]
Please, download CEF4Delphi again and try the new **ConsoleBrowser** demo. 

It uses the OSR mode and it also disables the GlobalCEFApp.MultiThreadedMessageLoop mode.

For this reason, the ShowBrowser function calls GlobalCEFApp.RunMessageLoop after showing the form and the browser form also calls GlobalCEFApp.QuitMessageLoop in the last destruction step, inside the OnCloseQuery event.

The console still shows the "Lost UI shared context" message and some other debug messages but you can ignore it.

You can apply this to the "DLLBrowser" demo and it also works! 

Disable GlobalCEFApp.MultiThreadedMessageLoop and add the GlobalCEFApp.RunMessageLoop and GlobalCEFApp.QuitMessageLoop calls in the "DLLBrowser" and "SubProcess" projects. 

Then replace the "CEF4DelphiLoader" for a console application it also works.

If you have more questions, please use our forums at : https://www.briskbard.com/forum/

**Comment by samchild** [comment]
It works, thanks every much!
For i just need OSR for images, but not windows  UI ,  so i
remove
```
 GlobalCEFApp.ExternalMessagePump        := False;
GlobalCEFApp.MultiThreadedMessageLoop   := False;
```
and it also work.
If i do not remove these tow lines , it will not get the OnPaint  callback of TChromium.
