### ISSUE TITLE
Slow MS Excel startup while a web browser is running

### ISSUE THREAD

**Issue by salvadordf** [salvadordf/CEF4Delphi#139]
If there is a TChromium running and you try to open a xlsx file from the explorer, Excel will take up to 40 seconds to start.

When you close the TChromium browser, Excel will start almost instantly.

Tested with : 

- Delphi 10 Seattle Subscription Update 1 and Delphi 10.2 Update 3

- Microsoft Office Standard 2013 and Microsoft Office Standard 2016

- Windows 10 PRO (64-Bit) and Windows 8.1 (64 bit)

**Comment by salvadordf** [comment]
Possibly related to this old DCEF3 issue : 
https://github.com/hgourvest/dcef3/issues/72

**Comment by salvadordf** [comment]
Excel broadcasts WM_DDE_INITIATE using SendMessage or SendMessageTimeout to initiate a DDE conversation. All top-level windows receive that message and Excel can't continue until the message is processed.
The CEF4Delphi subprocesses created using the same EXE as the main process can't process that message because Application.Run is never called.
The best solution would be to use a different EXE for the subprocesses because "Application" is not created but if you use the same EXE, then "Application" is created and you have to destroy Application.Handle and Application.PopupControlWnd before the subprocess calls TCefAplication.ExecuteProcess inside TCefApplication.StartMainProcess.

**Comment by schidi** [comment]
Just spent some time with this effect. Using subprocess, but some unfortunate use in our code included VCL.Controls, which in InitControls creates Application: TApplication;
Found it with unit-dependency-scanner
Might help somone with a similar problem
