### ISSUE TITLE
OnDocumentAvailable not called

### ISSUE THREAD

**Issue by ludydoo** [salvadordf/CEF4Delphi#14]
The Chromium.OnDocumentAvailable event is never triggered.

How to be able to access the document object ?

I tried using the Frame.VisitDomProc / Frame.VisitDom. Never gets triggered...

Thank you

**Comment by salvadordf** [comment]
VisitDom can only be called from the renderer thread. If you have multiple processes then you can only post a task in that thread from the renderer process.

**Comment by salvadordf** [comment]
Download the latest version of CEF4Delphi. The MiniBrowser demo has a working example of a DOM visitor. The Chromium.OnDocumentAvailable event no longer exists.
