### ISSUE TITLE
flash support.

### ISSUE THREAD

**Issue by hakwolf** [salvadordf/CEF4Delphi#143]
how can i set option to add this "--enable-system-flash"?if enable thi option ,is it  will work as well as  i use google chrom brower. Is there any other way? if i  has install plugn about flash,  is it will work fine with do nothing?

**Comment by salvadordf** [comment]
The "--enable-system-flash" switch is used to enable the detection of the Pepper Adobe Flash plugin installed in the operating system. 

Some switches are integrated in GlobalCEFApp and you only need to set a property to use them. 

In this case, you can use that switch by setting the GlobalCEFApp.FlashEnabled property to TRUE (which is the default value).

If you use the GlobalCEFApp.FlashEnabled property, your app users must install the Pepper Adobe Flash plugin as described [here](https://www.briskbard.com/index.php?lang=en&faqitem=208).

If you don't want to force all of your users to install the Flash plugin and you can distribute the Adobe Flash plugin with your app, you can also use the GloablCEFApp.CustomFlashPath property to specify a directory where the plugin binaries can be found. This property uses the "--ppapi-flash-path" and "--ppapi-flash-version" switches internally.

The Adobe Flash plugin works fine with CEF4Delphi if you use the GlobalCEFApp.FlashEnabled or GloablCEFApp.CustomFlashPath properties correctly.

Please, use our forums for more questions : 
https://www.briskbard.com/forum/
