### ISSUE TITLE
falsh problem.

### ISSUE THREAD

**Issue by hakwolf** [salvadordf/CEF4Delphi#145]
If you have problems with some video websites it might be caused by the use of proprietary video codecs.
i find it is't that reason. this mfc demo in release dir of https://github.com/xiaonaiquan/CEF3.open it demo exe,it can open it one video can normal play.And it can not open proprietary video codecs. Is it the problem of flash?

**Comment by hakwolf** [comment]
first,open video website  url: www.iqiyi.com then,open one viedeo webpage,it is blak screen , But use MFC demo ,it can play normal.And you can both open url :www.html5test.com to compare their difference.

**Comment by salvadordf** [comment]
That website is really slow if the browser is not using a local cache directory. 

Add GlobalCEFApp.cache := 'cache'; before the GlobalCEFApp.StartMainProcess call in the DPR file and you will see some videos in the VIP section. Install the latest Adobe Flash Plugin and open this address in the MiniBrowser demo : 
https://www.iqiyi.com/v_19rqrqho0s.html

If the browser doesn't use a cache directory then the video remains black but if you use a valid cache directory then the video plays normally in MiniBrowser.

That website opens new tabs for the videos and all the demos block them for simplicity. If you want to test a complete web browser implementation using CEF4Delphi try [BriskBard](https://www.briskbard.com/index.php?lang=en&pageid=download) and visit http://www.iqiyi.com/

Not all the videos in the video websites use open source codecs, some require DRM and some are restricted to some geographical locations.

Please, for more questions use our forum : 
https://www.briskbard.com/forum/
