### ISSUE TITLE
Declaration terminated incorrectly in C++Builder

### ISSUE THREAD

**Issue by petko** [salvadordf/CEF4Delphi#149]
For some reason the following changes in `uCEFConstants.pas` are not compatible with my C++Builder:
https://github.com/salvadordf/CEF4Delphi/commit/7342cccbb5f9a83eb909a158c089979caee4084d#diff-224f77cdaa091b419e661574ba55f842

I get an error `[bcc32 Error] uCEFConstants.hpp(314): E2040 Declaration terminated incorrectly` for each of the following:
```
static const System::Int8 IMAGE_FILE_MACHINE_UNKNOWN = System::Int8(0x0);
static const System::Word IMAGE_FILE_MACHINE_I386 = System::Word(0x14c);
static const System::Word IMAGE_FILE_MACHINE_IA64 = System::Word(0x200);
static const System::Word IMAGE_FILE_MACHINE_AMD64 = System::Word(0x8664);
static const System::Word IMAGE_FILE_MACHINE_R3000_BE = System::Word(0x160);
static const System::Word IMAGE_FILE_MACHINE_R3000 = System::Word(0x162);
static const System::Word IMAGE_FILE_MACHINE_R4000 = System::Word(0x166);
static const System::Word IMAGE_FILE_MACHINE_R10000 = System::Word(0x168);
static const System::Word IMAGE_FILE_MACHINE_ALPHA = System::Word(0x184);
static const System::Word IMAGE_FILE_MACHINE_POWERPC = System::Word(0x1f0);
```

If I comment them out, it works properly, but of course it will be better not to have to do that each new version..

**Comment by salvadordf** [comment]
I didn't realize those constants are already declared in the "Windows" unit.
