### ISSUE TITLE
Documentation note needed RE Threads on Events

### ISSUE THREAD

**Issue by hsvandrew** [salvadordf/CEF4Delphi#151]
Hi, 
I think there should be a big red note on the front page documentation that says 'please be aware, DCEF events do not run in the main thread and therefore you must not directly work with VCL components from the event handler but should create a callback into the main thread. If you don't you'll get all sorts of VCL corruption and display issues'. This is especially true for the JsDialog event.

**Comment by salvadordf** [comment]
Thanks!

I just added a paragraph in the main information page about that : 
https://www.briskbard.com/index.php?lang=en&pageid=cef

The JSDialog demo already used a critical section and a message to the main form to avoid that issue.
