### ISSUE TITLE
ExecuteJavaScript is unsuccessful

### ISSUE THREAD

**Issue by haostrange** [salvadordf/CEF4Delphi#153]
document.getElementsByClassName("select-image")[0].getElementsByTagName("label")[0].click();

This code is to open opendialog,I failed to open opendialog in cef4,In the chrome console is successful.

**Comment by salvadordf** [comment]
This seems like a pure JavaScript issue. Use the same Chrome or Chromium version as CEF4Delphi (71.0.3578.80) and check the log for possible error messages.

Perhaps the log has some error messages that can help you debug that code.

Please, use our forum for more questions : 
https://www.briskbard.com/forum/

**Comment by haostrange** [comment]
[1220/055033.920:VERBOSE1:thread_state.cc(1593)] [state:14680554] CollectGarbage: time: 0.17ms stack: NoHeapPointersOnStack marking: IncrementalMarking sweeping: LazySweeping reason: IncrementalIdleGC.

The log adds a record like this, I don't understand what this means.
