### ISSUE TITLE
SchemeRegistrationBrowser fails with resources > 32 kB

### ISSUE THREAD

**Issue by EricGrange** [salvadordf/CEF4Delphi#154]
The ReadResponse method can be called by CEF in 32 kB blocks.

Can be reproduced by adding to test.html

    <p><img src='jupiter.png'><br>Bigger image</p>

Only the top of the image is displayed.

The fix for THelloScheme.ReadResponse appears to be to remove the "FStream.Seek(0, soFromBeginning);" line, so that subsequent calls will read the remaining bytes.

**Comment by salvadordf** [comment]
Thanks for reporting this issue! 
I added your solution and modified the returned value when the stream is copied completely.
