### ISSUE TITLE
Drop down selection in TChromiumFMX

### ISSUE THREAD

**Issue by padamjain** [salvadordf/CEF4Delphi#155]
I am not able to select items from drop down when i use TChromiumFMX in a firemonkey application. Although the VCL component doesnt have this problem.
Any advice ?

**Comment by salvadordf** [comment]
I just tried the SimpleFMXBrowser, FMXExternalPumpBrowser and FMXToolBoxBrowser demos with this web page and the SELECT element works correctly :
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

If your application is based in FMXExternalPumpBrowser then the browser is in OSR mode and you need to use the TFMXChromium.OnPopupSize and TFMXChromium.OnPopupShow events. The TFMXChromium.OnPaint event must be prepared to paint the popup when the "kind" parameter is PET_POPUP.

Please, upgrade to the latest CEF4Delphi version and use one of the demos as a template of your application. If you still see that issue provide the web page address that can be used to reproduce this issue with one of the demos.
