### ISSUE TITLE
About support for video

### ISSUE THREAD

**Issue by StarXXin** [salvadordf/CEF4Delphi#156]
Hey, thank you very much for the constant update of dcef4. When I tried to use the dcef4 browser to watch the youtube website video, I was prompted that the browser version was too low. When I tested with html5test.com, I found that this does not support the h264 encoded stream. If you can support the playback of video, it is perfect. Thank you

**Comment by salvadordf** [comment]
Thanks!

The CEF3 binaries available at Spotify only have open source codecs. If you need proprietary codecs you need to build the binaries with some special parameters. 

Read this for more details : 
https://www.briskbard.com/index.php?lang=en&pageid=cef#codecs

**Comment by StarXXin** [comment]
Thanks!
There is still a question to ask, CEF4 installs SimpleBrowser after installation, open Baidu, the browser can not jump pages. Where is the switch not open?

**Comment by salvadordf** [comment]
Baidu creates a new browser tab when you click on the search results and the SimpleBrowser demo blocks all new tabs and new popup windows. 

Almost all demos block new popup windows and all of them block new tabs to keep them as simple and easy to understand as possible.

If you need tabs in your browser use the code in the **TabbedBrowser** demo.

Please, use our forum if you have more questions : 
https://www.briskbard.com/forum/
