### ISSUE TITLE
Access Global variable

### ISSUE THREAD

**Issue by ronelio** [salvadordf/CEF4Delphi#157]
Hello,

I need access a Global Variable in another Unit and this variable is not Updated after calling GlobalCEFApp.StartMainProcess.

Code below:

  GlobalCEFApp.LogFile              := 'debug.log';
  GlobalCEFApp.LogSeverity          := LOGSEVERITY_VERBOSE;
  GlobalCEFApp.SitePerProcess     := false;

```
  for i := 1 to ParamCount do
  begin
    **BrowserFrm.MakerServerId** := BrowserFrm.MakerServerId + ' - ' + ParamStr(i);
  end;

  if GlobalCEFApp.StartMainProcess then
    begin

      BrowserFrm.MakerServerId := 'o';
      Application.Initialize;
```

After that, when I get the value of BrowserFrm.MakerServerId, the value is something like 

> --type=renderer - --no-sandbox - --disable-gpu-compositing - --service-pipe-token=5901633039512350493 - --lang=en-US - --locales-dir-path=C:\Users\ronelio\Documents\Sources\MakerStudio\output\maker\cef\locales - --log-file=debug.log - --log-severity=verbose - --resources-dir-path=C:\Users\ronelio\Documents\Sources\MakerStudio\output\maker\cef - --enable-speech-input=1 - --enable-system-flash - --device-scale-factor=1 - --num-raster-threads=1 - --service-request-channel-token=5901633039512350493 - --renderer-client-id=2 - --mojo-platform-channel-handle=2116

And not "o".

If I put the code `BrowserFrm.MakerServerId := 'o';` before of 

> GlobalCEFApp.StartMainProcess

the variable is updated as I wish.

Is there some reason to that? Is there an option that I can do to get my own global variables updated?

**Comment by salvadordf** [comment]
It seems that you're trying to access a variable from a different process.

If you set BrowserFrm.MakerServerId in the browser process and you try to read that variable in the render process you will not get the same variable. 

CEF3 uses command switches to create new processes and BrowserFrm.MakerServerId is copying all those command switches from ParamStr.

You need to send those values with a process message using TCefProcessMessageRef.ArgumentList like this : 
https://github.com/salvadordf/CEF4Delphi/blob/2a82206be33ce12b031d4e16996eaf0f02ab4252/demos/DOMVisitor/uDOMVisitor.pas#L243

Please, use our forum for more questions : 
https://www.briskbard.com/forum/

**Comment by ronelio** [comment]
Ok. I'll use the forum for more clarification.

The supposed issue occurs when I try to get the variable on v8Handler, after user contextGlobalCreated.
