### ISSUE TITLE
Delphi-Android Support

### ISSUE THREAD

**Issue by azzahrah** [salvadordf/CEF4Delphi#159]
Hello

Any plan to support Android Platform?

**Comment by salvadordf** [comment]
CEF4Delphi is just a wrapper of CEF3 and CEF3 doesn't support Android at this moment. 

If you need a web browser using the Blink rendering engine in Android you can use a WebView widget or "Chrome Custom Tabs" : 
https://developer.chrome.com/multidevice/android/customtabs
https://android-developers.googleblog.com/2015/09/chrome-custom-tabs-smooth-transition.html
https://github.com/GoogleChrome/custom-tabs-client
