### ISSUE TITLE
Popup window does not close

### ISSUE THREAD

**Issue by leoeuclids** [salvadordf/CEF4Delphi#16]
When i click a link that opens another page inside a popup, everything works fine, but i can't close the popup.

Is there any configuration needed to close popups?

**Comment by salvadordf** [comment]
I tried this example of popups with the minibrowser demo and it works : https://www.w3schools.com/js/tryit.asp?filename=tryjs_win_close

Those are windows generated automatically by the CEF3 library but if you use a custom window for popups you need to follow the instructions given at the comments before the do_close callback : 
https://bitbucket.org/chromiumembedded/cef/src/54647945f168cb46df034fed5f1c71730be27e4b/include/capi/cef_life_span_handler_capi.h?at=master&fileviewer=file-view-default

**Comment by leoeuclids** [comment]
Just used the MiniBrowser example and it works!

But the issue appears when using the SimpleBrowser example, because its related to the TChromiumWindow component.
It's working fine when using a TCefWindowParent with a TChromium (as in the MiniBrowser example).

**Comment by leoeuclids** [comment]
After some more digging, i found the source of the issue on the WebBrowser_OnClose event, inside TChromiumWindow.

````pascal
unit uCEFChromiumWindow;
// [...]
procedure TChromiumWindow.WebBrowser_OnClose(Sender: TObject; const browser: ICefBrowser; out Result: Boolean);
begin
  PostMessage(self.Handle, CEF_DOONCLOSE, 0, 0);
  Result := True;
end;
````

Changing the Result to False allows the popup window to close as expected.

**Comment by salvadordf** [comment]
Thanks! I'll modify TChromiumWindow to set Result as False by default.

**Comment by leoeuclids** [comment]
I ran into another issue related to this.
After closing the popup window, the TChromium object loses the ICefBrowser reference (fBrowser property), wich causes the browser to stop responding to LoadUrl or ExecuteJavascript functions.

Tried to dig in the code to find the root cause, but no luck so far.

**Comment by salvadordf** [comment]
When you let CEF3 create the popup then TChromium receive the OnClose and OnBeforeClose events of the popup. I'll add some checks in the next version : if (browser <> nil) and (FBrowserId = browser.Identifier) then...
Thanks!!!

**Comment by salvadordf** [comment]
The latest CEF4Delphi includes all the fixes for the bugs you mentioned. Thanks! :smile:

**Comment by leoeuclids** [comment]
Great... all the issues i mentioned are fixed in the new version.

Thanks!
