### ISSUE TITLE
How can get data from html to delphi?

### ISSUE THREAD

**Issue by george-kar** [salvadordf/CEF4Delphi#160]
I was wondering how can send back data from an html page to the delphi app. Although there are dozen of examples how to make the opposite (Send data from delphi to html) there is no such example how to send from html to delphi. I need to catch link clicks and using an interval send custom data every X seconds back to delphi. Right now the only solution I found is using "console.log" by sending text and catching from delphi app. But I feel must be a better way. Any idea?

Btw, I don't know if that's the right place to ask but briskbard.com forum is not working. Activation email never came (I have gmail account) and I can't login to create a thread. So I had to ask here.

**Comment by salvadordf** [comment]
I'm sorry about the missing activation email. Send me your username and I'll activate it manually : 
https://www.briskbard.com/index.php?lang=en&pageid=emailgnrl

You will need to register a JavaScript extension to be able to call a custom JavaScript function that executes native Delphi code. That custom function is executed in a different process and you will need to send a message from that custom function to the main browser process with the data you wish to handle in Delphi code.

Open the **JSRTTIExtension** demo in the JavaScript directory for all the details. To test that demo, run it , right-click and select the "_Set mouseover event_" option. Then move the mouse over the web page and you will see some HTML elements in the status bar that were sent from JavaScript to Delphi. Read the code comments in that demo for more details.

**Comment by george-kar** [comment]
Hello, I can't even send you an email to the form. It returns error:

SERVER ERROR.
PLEASE TRY AGAIN IN A FEW MINUTES.

As for the JSRTTIExtension example I will check that. Thanks!

**Comment by salvadordf** [comment]
Thank you for reporting the issue in the contact form!
Now it's fixed.

**Comment by george-kar** [comment]
I am sorry but it still says server error try again :/

https://monosnap.com/file/XZGoxAB42rKmV0RI85DfJPa6FMbcna

**Comment by salvadordf** [comment]
Press CONTROL + F5 to refresh the page.

**Comment by george-kar** [comment]
Of course I tried ctrl+f5 and ctr+shift+r. Also i tried to disable cache so it will bring latest files 100%

https://monosnap.com/file/j5JZEHPbtqhubIRsDFB5YLyrcSkVYR

**Comment by salvadordf** [comment]
Sorry again.

That form has some anti-spam features and one of them was too restrictive. Please, try again or use one of the email addresses at the top of that page.

**Comment by george-kar** [comment]
Yes now it works! Btw, regarding my original question I want to ask one more thing. I've seen the example and it works perfect. But I was wondering if I can use the exact same technique to return data back to html. For example:  $("#pc_name_number").text( myextension.get_pcname() )
Also, if its possible to have function names with underscore.

**Comment by salvadordf** [comment]
I'm glad to hear that. Your forum user is now activated.

Yes, you can send process messages to communicate between JavaScript and Delphi in both ways but you may have some problems due to the #138 issue. I would recommend to use the workaround described in the #138 issue or just use the **TChromium.ExecuteJavaScript** function to send information from Delphi to JS.

Let's continue this conversation in our forum : 
https://www.briskbard.com/forum/
