### ISSUE TITLE
FMXChromium (TFMXChromium) not showing web page

### ISSUE THREAD

**Issue by padamjain** [salvadordf/CEF4Delphi#162]
Hi,

I am using TFMXChromium browser in my application. All the demo application (uSimpleFMXBrowser.pas) are working fine . but when i integrate the demo form code in my application, then web page is not loading.
any advice , if i am missing anything.

**Comment by salvadordf** [comment]
Hi,

Check that your app is using FMXApplicationService.pas and copy all the code in uSimpleFMXBrowser.pas, especially the TSimpleFMXBrowserFrm.FormCreate and TSimpleFMXBrowserFrm.FormShow procedures.

Please, use our forum for more questions : 
https://www.briskbard.com/forum/

**Comment by padamjain** [comment]
Would like to discuss more about this topic on forum, could you please add me or activate my email on the forum.

**Comment by salvadordf** [comment]
Done! :)
