### ISSUE TITLE
How to load browser in bpl

### ISSUE THREAD

**Issue by kevinsui581** [salvadordf/CEF4Delphi#163]
I have some form with browser component in some bpl, I init cef4delphi in main process, then load some form from bpl, but browser can't work。what can i do to make browser to work in bpl?

**Comment by salvadordf** [comment]
I've never tried to add CEF4Delphi using just a BPL but I would try to configure CEF4Delphi to use a different EXE for the subprocesses. 

Take a look at these demos for more details : SubProcess, DLLBrowser and ConsoleBrowser.

If you have more questions please use our forum at : 
https://www.briskbard.com/forum/
