### ISSUE TITLE
'DisableWebSecurity' not working

### ISSUE THREAD

**Issue by xunni1000** [salvadordf/CEF4Delphi#164]
test url : **https**://www.yge.me/main.html

html-code:
`<html>
<body>
<div class='test'>
<iframe src="http://blog.yge.me/1.html"  id='f1' name='f1' scrolling="no"  frameborder="0"></iframe>
</div>
</body>
<html>
`

**Comment by salvadordf** [comment]
Thanks for reporting this issue. It seems to be an old bug in Chromium but you can use an alternative way to load that web page.

Please, download CEF4Delphi again and add this in the DPR file : 
`GlobalCEFApp.AllowRunningInsecureContent := True;`
Add that line before the GlobalCEFApp.StartMainProcess call.
