### ISSUE TITLE
How to Use TPagecontrol with cef4delphi?Multi-page browser

### ISSUE THREAD

**Issue by Delhpi** [salvadordf/CEF4Delphi#165]
Multi-page browser

**Comment by salvadordf** [comment]
The TabbedBrowser demo uses a TPageControl with a browser on each page.

**Comment by Delhpi** [comment]
but，in Chromium_OnBeforePopup，no code to create a new page。

When clicking on a link in curent web page, this link opens a new page in POST mode.

procedure TMainForm.Chromium_OnBeforePopup(Sender: TObject;
  const browser: ICefBrowser; const frame: ICefFrame; const targetUrl,
  targetFrameName: ustring; targetDisposition: TCefWindowOpenDisposition;
  userGesture: Boolean; const popupFeatures: TCefPopupFeatures;
  var windowInfo: TCefWindowInfo; var client: ICefClient;
  var settings: TCefBrowserSettings; var noJavascriptAccess: Boolean;
  var Result: Boolean);
begin
  // For simplicity, this demo blocks all popup windows and new tabs
  Result := (targetDisposition in [WOD_NEW_FOREGROUND_TAB, WOD_NEW_BACKGROUND_TAB, WOD_NEW_POPUP, WOD_NEW_WINDOW]);
end;

**Comment by salvadordf** [comment]
To open new popup windows use the code in the PopupBrowser2 demo. 

That demo creates hidden browsers in the main thread to be used as the next popup window. If you need new tabs, create a hidden tab and use it when Chromium_OnBeforePopup has a targetDisposition with these values : WOD_NEW_FOREGROUND_TAB, WOD_NEW_BACKGROUND_TAB.
