### ISSUE TITLE
Problem in Delphi XE3 with initializing

### ISSUE THREAD

**Issue by JanBoersma** [salvadordf/CEF4Delphi#17]
I found this project lately, and I really like the idea to implement Chromium for Delphi in an easy way!

Unfortunately, I have this problem.
On initializing this line produces an error message:
Result := (cef_initialize(@HInstance, @TempSettings, CefGetData(FAppIntf), FWindowsSandboxInfo) <> 0);

I am able to locate the error (see below), but this kind of programming is too complicated for me to understand, so I hope there will be a solution from somebody else. :)

On executing the above mentioned line, the program enters this procedure several times:
procedure cef_base_add_ref(self: PCefBase); stdcall;
The third time result in the error message: the program enters this function:
function CefGetObject(ptr: Pointer): TObject; inline;
This function's result is '()', and after returning to 'cef_base_add_ref', the error comes up.

It seems to be some memory problem, but I don't know what kind of error it is or what to do to fix it.

And here is some more: it does not matter if I run the 32bit version or the 64bit version, there is always this error. The message content differs, but I think they are basically the same.

![errormessage](https://cloud.githubusercontent.com/assets/26403004/23891580/622ec03a-0897-11e7-9fc4-32e80cddc66a.jpg)
![errormessage_x64](https://cloud.githubusercontent.com/assets/26403004/23891581/622f688c-0897-11e7-8bb6-b6d51c66458c.jpg)

**Comment by salvadordf** [comment]
This code line belongs to an old version of CEF4Delphi : 
Result := (cef_initialize(@HInstance, @TempSettings, CefGetData(FAppIntf), FWindowsSandboxInfo) <> 0);

Download CEF4Delphi clicking the green button "clone or download" and then click on "Download Zip"

**Comment by JanBoersma** [comment]
Thanks, Salvador. I don't remember where I got the old zip from, but the error is gone now.
Next step: I will try to create a simple browser and investigate its possibilities.
