### ISSUE TITLE
Double App Launching

### ISSUE THREAD

**Issue by Kashaket** [salvadordf/CEF4Delphi#170]
When using CEF with some other packages, which loads libraries and SingleProcess disabled, after a somewhile, the application accidentally starts itself for the second time, for example when typing in google something (not the browsing, it's important!)

**Comment by salvadordf** [comment]
By default, CEF3 creates multiple processes to handle different tasks. 

To create each process CEF3 executes an EXE file and that file can be your application's EXE file or a different one.

By default, CEF4Delphi will use your application's EXE file to create all the processes and the Windows Task Manager will show several instances of your application running at the same time.

CEF4Delphi can also be configured to use a different EXE for all those subprocesses. Take a look at the [SubProcess](https://github.com/salvadordf/CEF4Delphi/tree/master/demos/SubProcess) demo for more details.

Please, read this too : 
https://www.briskbard.com/index.php?lang=en&pageid=cef

**Comment by Kashaket** [comment]
Thanks :smile:
