### ISSUE TITLE
Lazarus publishing

### ISSUE THREAD

**Issue by Kashaket** [salvadordf/CEF4Delphi#171]
Hello, dear author, the lazarus ide supports online package manager (something like nuGet) from version 1.6 (if i am right), why not to publish CEF4Delphi in lazarus package catalog?

**Comment by salvadordf** [comment]
I didn't know that package manager existed. I'll take a look as soon as I can and add CEF4Delphi.

Thanks! :D

**Comment by salvadordf** [comment]
CEF4Delphi is now in the Lazarus Online Package Manager.

**Comment by dtamade** [comment]
good
