### ISSUE TITLE
FMX Demos shows a warning for Duplicate Resourses

### ISSUE THREAD

**Issue by SchneiderInfosystems** [salvadordf/CEF4Delphi#173]
Compiling the FMXExternalPumpBrowser.dproj leads to 5 warnings:
[dcc32 Hint] H2161 Warning: Duplicate resource:  Type 12 (CURSOR GROUP), ID 32761; File c:\program files (x86)\embarcadero\studio\20.0\lib\Win32\release\Controls.res resource kept; file c:\program files (x86)\embarcadero\studio\20.0\lib\Win32\release\FMX.Controls.Win.res resource discarded.

The root cause behind this is a mixup when including components from FMX and VCL together. I have solved this point by adding a new conditional define "$(FrameworkType)" in the project options in oder to distinguish the framework type in uCEFApplication.pas and in uBufferPanel.pas.

Additionaly I have removed the part "DestroyWindow(Application.Handle)" in TCefApplication.SingleExeProcessing because the Firemonkey does not support such a handle for a hidden window. My understanding of the Firemonkey framework is that we do not have a such hidden window anymore than it was used in VCL. But in fact I'm in this point also not 100% sure.

Here you can preview my commit:
https://github.com/SchneiderInfosystems/CEF4Delphi/commit/239ca44873e45b23e196683e56fc24ebf19475f9

If you like I can do a pull request with my solution but I don't have changed all FMX Demo projects yet (by adding the conditional define). And perhaps there are other source files which requires to distinguish the framework type...

Thank you for your great work!

**Comment by salvadordf** [comment]
All pull requests are welcome! Specially from people with more FireMonkey experience than me.

I'll try to take a look at your code as soon as I can but I'm extremely busy these days.

**Comment by SchneiderInfosystems** [comment]
Thanks for checking my pull request carefully.
