### ISSUE TITLE
Suggestion: HTML Editor

### ISSUE THREAD

**Issue by raelb** [salvadordf/CEF4Delphi#179]
Hi,
Suggestion for either a demo project or perhaps side project using CEF4Delphi together with TinyMCE, to add HTML Editor functionality to applications. Toolbar buttons should be part of the VCL interface.

For me I think it would be fairly straight forward to work off the file system, i.e. navigate to a index.html at temp location. Add add images to the folder. What would be difficult is for the implementation to be in memory. I.e feed html and other resources into the control, and feed them out when saving.

**Comment by salvadordf** [comment]
The update to CEF 75.1.4 includes a new demo called EditorBrowser
