### ISSUE TITLE
Random crashes using custom schemes

### ISSUE THREAD

**Issue by salvadordf** [salvadordf/CEF4Delphi#18]
The MiniBrowser registers a custom scheme called 'hello' and the app crashes randomly when you visit hello://world/

**Comment by jazlee** [comment]
any update on this issue? it might be similar issue found on CEFSharp of which had been closed, please check this:

https://github.com/amaitland/CefSharp/commit/e492c0d21e81ee373656f14df6738f7df8b58dc0

**Comment by salvadordf** [comment]
Not yet. I'll take a look as soon as I can.

**Comment by salvadordf** [comment]
Please download the latest update

**Comment by jazlee** [comment]
great, thanks...
