### ISSUE TITLE
how to use SetNewBrowserParent?

### ISSUE THREAD

**Issue by betafoxy** [salvadordf/CEF4Delphi#181]
how to use SetNewBrowserParent? can i  use it to move a Chromium to another form?

**Comment by salvadordf** [comment]
This forum thread has some instructions to use TChromium.SetNewBrowserParent with frames but you can apply them to other situations too :
https://www.briskbard.com/forum/viewtopic.php?f=10&t=439&p=1896

**Comment by betafoxy** [comment]
thanks, solved !
![BaiduShurufa_2019-5-10_17-2-32](https://user-images.githubusercontent.com/45146564/57528695-929a7d00-7365-11e9-8520-682d35e17a2e.png)
