### ISSUE TITLE
how to handle devtool event??

### ISSUE THREAD

**Issue by betafoxy** [salvadordf/CEF4Delphi#183]
as the image, click "open in new tab" ,can't open ......

![BaiduShurufa_2019-5-10_17-2-32](https://user-images.githubusercontent.com/45146564/57528183-37b45600-7364-11e9-9b17-db98a2dcd88c.png)

**Comment by salvadordf** [comment]
I'm afraid I can't help you. 

That context menu is not like the context menu in the browser window and it doesn't trigger the usual events to handle menus, new tabs or navigation : TChromium.OnContextMenuCommand, TChromium.OnOnBeforePopup, TChromium.OnOnBeforeBrowse, etc.

I tried those events modifying TChromium.ShowDevTools to create a TCustomClientHandler with a ContextMenuHandler, a LifeSpanHandler and a RequestHandler.

**Comment by betafoxy** [comment]
thanks yet
