### ISSUE TITLE
download filename issue

### ISSUE THREAD

**Issue by betafoxy** [salvadordf/CEF4Delphi#185]
html node <A>, the "download" attribute means saved filename, but on cef not work,on chrome is ok. 

![BaiduShurufa_2019-5-11_23-2-30](https://user-images.githubusercontent.com/45146564/57571440-f0e85e00-7440-11e9-9c0c-02f9eb30c707.png)

**Comment by salvadordf** [comment]
I tested this page with the MiniBrowser demo :
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_a_download2

If you click on the image the demo uses the suggestedName parameter in the TChromium.OnBeforeDownload event which has the download attribute value.

Please, use our forums if you have more questions : 
https://www.briskbard.com/forum/

**Comment by betafoxy** [comment]
i see,  with that page , the OnBeforeDownload  suggestedName  should be w3logo.jpg，but  it's myw3schoolsimage.jpg
