### ISSUE TITLE
form restore issue

### ISSUE THREAD

**Issue by betafoxy** [salvadordf/CEF4Delphi#186]
as the screen capture, form first nomal state , then to max , then to mini ,the issue is "**when i restore form，the page  will re layout**"。

on chrome and cefclient.exe no this issue.

![1111](https://user-images.githubusercontent.com/45146564/57686289-e827a000-766b-11e9-9143-ae1e6e7bb488.gif)

**Comment by salvadordf** [comment]
TCEFWindowParent updates the browser size every time the VCL calls the _Resize_ procedure and the VCL calls it several times when you restore a form.

If you don't want that happening set the alignment to alNone before minimizing the form and restore the old value when the form is fully restored. 

It's recommended to set the TCEFWindowParent.Enable and TCEFWindowParent.Visible properties to False, and set the TCEFWindowParent.Width and TCEFWindowParent.Height to 0 when the form is minimized to avoid unnecessary browser updates.

**Comment by betafoxy** [comment]
ok,thanks.

i hooked the TCEFWindowParent resize prodc，move updatesize call to it's onresize  , and check  the windowstate first.
