### ISSUE TITLE
converted most of the projects to lazarus

### ISSUE THREAD

**Issue by zeljkoavramovic** [salvadordf/CEF4Delphi#187]
Temporary download link:
https://bitbucket.org/avra/ct4laz/downloads/tmp_cef4delphi_demos_and_fixes.zip

Lazarus fixes for uCEFInterfaces.pas

Tested on Win10x64 with 32bit FPC 3.0.5 and LAZ 2.0.1

**Comment by salvadordf** [comment]
Thank you very much for all those demos! 
I'll add them as soon as I can.
