### ISSUE TITLE
OnWebKitInitialized is never called

### ISSUE THREAD

**Issue by betonetotbo** [salvadordf/CEF4Delphi#191]
I created a custom `JJWCEFPlugin.exe` to use a subprocess for my CEF.

I created too, an javascript integration with my application, injecting a global variable with a my custom function inside (as described in **Functions And Extensions** in https://bitbucket.org/chromiumembedded/cef/wiki/JavaScriptIntegration.md).

This is my `TCefApplication` creation:

```
  GlobalCEFApp := TCefApplication.Create;
  GlobalCEFApp.BrowserSubprocessPath := 'JJWCEFPlugin.exe';
  GlobalCEFApp.ShowMessageDlg := False;
  GlobalCEFApp.OnWebKitInitialized := TJJWXPV8Handler.GlobalCEFApp_OnWebKitInitializedEvent;

  GlobalCEFApp.StartMainProcess;
```

The problem is, that my registration method `TJJWXPV8Handler.GlobalCEFApp_OnWebKitInitializedEvent` is never called. Why?

Is because the `JJWCEFPlugin.exe` hasn't the `TJJWXPV8Handler.GlobalCEFApp_OnWebKitInitializedEvent` plugged-in?

There are a way to make an IPC to call my code inside my main application instance instead of run it on the subprocesss instance?

**Comment by salvadordf** [comment]
GlobalCEFApp.OnWebKitInitialized is executed in a different process and Delphi can only debug one process. 

Read this for more information about debugging CEF application in Delphi :
https://www.briskbard.com/index.php?lang=en&pageid=cef#debugging

Please, use our forums for more questions : 
https://www.briskbard.com/forum/

**Comment by betonetotbo** [comment]
One question, If I have created a subprocess.exe with this code:

```
program subprocess;

uses uCEFApplication;

{$R *.res}

begin
  GlobalCEFApp := TCefApplication.Create;
  try
    GlobalCEFApp.StartSubProcess;
  finally
    GlobalCEFApp.Free;
  end;
end.
```
The `OnWebKitInitializedEvent` event will be fired inside the `subprocess.exe` ?

If the answer is YES, how can I intercomunicate between my mainprocess and the subprocess? There are some stuffs that I only can access from the mainprocess.

I need to make an integration between CEF and my running application, an integration by javascript. A function that will call my delphi code inside the main process instance.

**Comment by salvadordf** [comment]
Yes, GlobalCEFApp.OnWebKitInitializedEvent is executed in subprocess (render process) and you will need to use process messages to communicate between the render process and the main browser process. 

All the details are in the code comments of the JSExtension demo : https://github.com/salvadordf/CEF4Delphi/blob/7662b61778544cfacddb68a5bdca9e7d6da292b7/demos/Delphi_VCL/JavaScript/JSExtension/uJSExtension.pas#L131

Or here : 
https://www.briskbard.com/forum/viewtopic.php?f=8&t=918&p=4084#p4084

Please, use our forums for more questions :
https://www.briskbard.com/forum/
