### ISSUE TITLE
Error opening Mini Browser demo (VCL) - Event no longer exists

### ISSUE THREAD

**Issue by raelb** [salvadordf/CEF4Delphi#192]
![image](https://user-images.githubusercontent.com/13108198/58322836-70ebcc00-7e22-11e9-9710-ebcc28f46bce.png)

**Comment by salvadordf** [comment]
Delphi is loading an old BPL. Uninstall CEF4Delphi and install it again following these steps : 
https://www.briskbard.com/forum/viewtopic.php?f=8&t=772#p3481
