### ISSUE TITLE
BUG:Firebase connection do not  work

### ISSUE THREAD

**Issue by wpbarcelos** [salvadordf/CEF4Delphi#193]
I've attached a page that uses the firebase plugin.
This page responds with table refresh events.
External to Delphi works. with a page linked to the cef4delphi component does not work.
I did a simple test to update the screen to test and not work.
I used up to an older version to see the degree of compatibility but went wrong.
https://www.gstatic.com/firebasejs/4.2.0/firebase.js

**Comment by salvadordf** [comment]
I'm sorry but I know nothing about Firebase and I can't help you. 

Perhaps someone in our forum can help you if you post a fully testable example with detailed instructions and all the code : 
https://www.briskbard.com/forum/
