### ISSUE TITLE
the page goes to freeze in the background

### ISSUE THREAD

**Issue by mesutalturk** [salvadordf/CEF4Delphi#199]
Hi,

I'm working on MiniBrowser. The application goes to sleep sometimes in the background. (the other chrome is also very tab open) what is the reason of this? How can I solve? (proactive-tab-freeze-and-discard)
Thank you

Best regards,
Mesut Altürk

**Comment by salvadordf** [comment]
Hi,

Try adding this before the GlobalCEFApp.StarMainProcess call in the DPR file : 
`GlobalCEFApp.AddCustomCommandLine('--memory-pressure-off');`

It seems that Chromium added an automatic tab and cache discarding feature to save memory. 

Please, use our forum for more questions : 
https://www.briskbard.com/forum/
