### ISSUE TITLE
Error when try to install in Delphi XE4

### ISSUE THREAD

**Issue by raelb** [salvadordf/CEF4Delphi#2]
I have followed your install instructions but receive the following error when trying to install the package into DXE4:

![cef4delphi_error](https://cloud.githubusercontent.com/assets/13108198/22594525/10d3a7fc-ea2c-11e6-9890-bc8394a65f65.png)

I have placed libcef.dll & chrome_elf.dll into system folder

**Comment by salvadordf** [comment]
Looks like you are using an old libcef.dll
If that's the case, that error has nothing to do with the Delphi version.
Make sure you use the version CEF 3.2924.1558.g872fbc0 of the CEF3 binaries next to your EXE and in c:\windows. 
This is the link to the win32 binaries : http://opensource.spotify.com/cefbuilds/cef_binary_3.2924.1558.g872fbc0_windows32.tar.bz2

**Comment by raelb** [comment]
I think I was using the correct dll's since I used your download link. I think the problem was that there was another copy of libcef.dll somewhere else on the PATH. 

I'm glad to see that you removed the need for dlls when loading in the IDE. It is working for me now in XE4.
