### ISSUE TITLE
getElementById

### ISSUE THREAD

**Issue by JanBoersma** [salvadordf/CEF4Delphi#20]
After loading a webpage with a TChromium component, I need to read and write some data (value, innerHTML). I was hoping I could use some command like "getElementbyId('blabla').value"

I have been searching the internet for 2 days now, but nothing seems to work. I have found some ideas, which are offered as solutions, but they don't seem to work.

Is there an example Delphi project available, that shows me how to get a handle to the HTML document or how to get data from text fields, forms, etc?

I really hope that there is a solution, because I love what I have seen from Chromium, so far.

**Comment by salvadordf** [comment]
I found a working solution using a custom RenderProcessHandler. I'll clean up the code and upload it as part of the MiniBrowser demo tomorrow.

**Comment by JanBoersma** [comment]
That is really fast. Super! I can hardly wait to see how it works. Thank you so much!

**Comment by salvadordf** [comment]
Download the latest version of CEF4Delphi. It has all what's necessary to access the DOM inside the DOMVisitor_OnDocAvailable function in the MiniBrowser.dpr file.

Take a look at the CEF3 documentation to access the DOM : 
http://magpcss.org/ceforum/apidocs3/projects/(default)/CefDOMDocument.html
http://magpcss.org/ceforum/apidocs3/projects/(default)/CefDOMNode.html

Remember that the DOMVisitor_OnDocAvailable is called from another process. You'll have some difficulties debugging.

**Comment by JanBoersma** [comment]
Thanks, Salvador! I can hardly wait to try. :)

There is one issue, though. Of course I need new CEF3 binaries, because the version numbers should match.
But when downloading this link: http://opensource.spotify.com/cefbuilds/cef_binary_3.2987.1596.gc2b4638_windows32.tar.bz2,
the contents of the download are quite different from what I expect (no dll files, etc).

**Comment by salvadordf** [comment]
Use **WinRAR** to decompress the BZ2 file and copy the contents of the **Release** and **Resources** directories to the same directory of your EXE. You can delete the _cef_sandbox.lib_ and _libcef.lib_ files.

**Comment by JanBoersma** [comment]
Yes, the necessary folders (and files) are in the 64 bits RAR, but not in the 32 bit RAR, as far as I can see. Or am I overlooking something?

**Comment by salvadordf** [comment]
Maybe one of your downloads got corrupted. I downloaded both packages again and they contain all the DLLs and resources.

**Comment by JanBoersma** [comment]
Now I have them. Thanks for your persistent support! :-)

**Comment by virtelot** [comment]
Is there any opportunity to get element by name or tag name? Element doesn't have ID.
I'm using a tag name now in WebBrowser. But did not find any solution in CEF :(

`a:=webbrowser1.oleobject.document.GetElementsByTagName('select').item(0);`

**Comment by EasyVizi** [comment]
I can't find DOMVisitor_OnDocAvailable function in MiniBrowser.dpr file, and can't find it in all project.
Pls, tell me, how or where can i find example?

**Comment by EasyVizi** [comment]
I can't find DOMVisitor_OnDocAvailable function in MiniBrowser.dpr file, and can't find it in all project.
Pls, tell me, how or where can i find example?
