### ISSUE TITLE
CEF Build expected libcef.dll 75.0.7.0 version: found libcef.dll version: 75.0.13.0

### ISSUE THREAD

**Issue by shariful2011** [salvadordf/CEF4Delphi#200]
I build CEF 75.0.13.0 as per [https://bitbucket.org/chromiumembedded/cef/wiki/MasterBuildQuickStart.md](url) but when try run it is saying "expected libcef.dll 75.0.7.0 version: found libcef.dll version: 75.0.13.0". Whereas in your readme.md you mentioned as "CEF4Delphi uses CEF 75.0.13 which includes Chromium 75.0.3770.100". I have to re-build CEF for using MP4. Version mismatch issue is not understood, can you please explain.

Also please check I made on issue in CEF forum @ [https://magpcss.org/ceforum/viewtopic.php?f=10&t=16876&p=42364#p42364](url)

**Comment by salvadordf** [comment]
Please, read this forum post about the CEF version number format update :
https://www.briskbard.com/forum/viewtopic.php?f=8&t=833#p3714

There you have some details to download the right CEF sources.

I've never built the CEF binaries but the official CEF forum have many experts that can help you in that regard.

**Comment by shariful2011** [comment]
I solved the issue by using the latest CEF4Delphi. Thanks
