### ISSUE TITLE
AV when close SimpleBrowser demo

### ISSUE THREAD

**Issue by raelb** [salvadordf/CEF4Delphi#201]
I updated to latest version of CEF4Delphi and cef 75.0.13.
I run the SimpleBrowser demo. 
I tried 2 things:
 - wait for the start page to load (google.com)
 - do not wait for start page to load

I do not load any other page or press on Go
Sometimes when I close I get an AV.

**Comment by raelb** [comment]
Seems to be solved if I add

      GlobalCEFApp.DisableFeatures := 'NetworkService';

**Comment by salvadordf** [comment]
The network service still has a few issues in CEF and sometimes it's necessary to disable it to avoid AV errors.
