### ISSUE TITLE
Problemas con los focos de la aplicacion

### ISSUE THREAD

**Issue by duxman** [salvadordf/CEF4Delphi#203]
Hemos detectado un caso extraño con los focos.
Sucede lo siguiente: 

Cuando cambiamos el foco entre una ventana principal que contengan un componente TCrhomiunWindow y el escritorio al cabo de varias interacciones la ventana que contiene el navegador se va al fondo de todas las ventanas abiertas.

¿Tienes alguna idea de porque sucede esto?
¿Podría contactar contigo de alguna forma?, los dos somos de esta gran ciudad :) 

un cordial saludo

**Comment by salvadordf** [comment]
Hola,

Con otras aplicaciones que no contienen ningún componente de CEF4Delphi he visto como algunas ventanas secundarias se quedan detras de la principal.

Si buscas "delphi z order form issues" en Google verás multiples casos similares.

Me alegra ver que no soy el único de Zaragoza que usa Delphi o Lazarus, pero normalmente respondo a dudas en nuestro foro : 
https://www.briskbard.com/forum/
