### ISSUE TITLE
AudioMuted problem

### ISSUE THREAD

**Issue by betafoxy** [salvadordf/CEF4Delphi#204]
when i set Chromium1.AudioMuted value on a button click, then to check，alwayls is same value. but in Chromium1BeforeContextMenu to check  is ok...
`procedure TMiniBrowserFrm.BtnClick(Sender: TObject);
begin
  Chromium1.AudioMuted := not Chromium1.AudioMuted;// !!!! alwayls is false
end;`

**Comment by salvadordf** [comment]
It's a CEF limitation. We can only read the "AudioMuted" property in a CEF thread called "UI thread". This thread is not the same as the main application thread. https://bitbucket.org/chromiumembedded/cef/src/45329d05a5e0d96047374decaa6170cdeac9e0d7/include/capi/cef_browser_capi.h#lines-850

TChromium.OnBeforeContextMenu and many other TChromium events are executed in the "UI thread".

**Comment by betafoxy** [comment]
ok ,thanks,  deal the state by my code..
