### ISSUE TITLE
No webrtc video when use TBufferPanel (KioskOSRBrowser)

### ISSUE THREAD

**Issue by RicardoBer** [salvadordf/CEF4Delphi#205]
I test in SimpleBrowser example and it works, but not when use TBufferPanel to paint as in KioskOSRBrowser example.

You can test with this html code (load it from a page in local for example):

`<div id="cuadro_atencion_jitsi">
<iframe allow="camera; microphone" src="https://meet.jit.si/test" name="jitsiConferenceFrame0" id="jitsiConferenceFrame0" allowfullscreen="true" style="height: 600px; width: 100%; border: 0px;">
</iframe>
</div>`

in Kiosk example it creates chromium in windowless mode, 

`chrmosr.CreateBrowser(nil, '')`

and paint in chrmosrPaint (onpaint method) from chromium to TBufferPanel. 

in simple browser it creates in a CEFWindowParent component

`Chromium1.CreateBrowser(CEFWindowParent1, '')`

and it paints it self.

**NOTE:**

It seems that the problem arises when uses 

api = new JitsiMeetExternalAPI, 

from jitsi api that create a iframe into div, so the problem seems to be asociated to a iframe tag.

**Comment by salvadordf** [comment]
I did a quick test with SimpleOSRBrowser and a cheap webcam navigating to these web pages : 
https://webrtc.github.io/samples/src/content/getusermedia/gum/
https://meet.jit.si/test

Both pages showed the video captured by the camera correctly.

The SimpleOSRBrowser and the KioskOSRBrowser demos are almost identical. Both of them are OSR browsers that use a TBufferPanel but the Kiosk demo also uses the virtual keyboard with a maximized form without borders to simulate a full screen app. 

Please, download the official CEF application called "cefclient" from here : 
http://opensource.spotify.com/cefbuilds/cef_binary_75.0.13%2Bg2c92fcd%2Bchromium-75.0.3770.100_windows32_client.tar.bz2

Execute cefclient with the following command line parameter and repeat the tests : 
--off-screen-rendering-enabled

Let's continue this conversation in our forum : 
https://www.briskbard.com/forum/

**Comment by RicardoBer** [comment]
Thanks for your soon response.

Yes it works with full page load. But try with above example in an html.

<iframe allow="camera; microphone" src="https://meet.jit.si/test" name="jitsiConferenceFrame0" id="jitsiConferenceFrame0" allowfullscreen="true" style="height: 600px; width: 100%; border: 0px;"> </iframe>

The TBufferpanel doesn't work in that case (video in iframe), some times show half image, some time full image, some time nothing.

In other way, this example works on MiniBrowser example that uses TCEFWindowParent, no TBufferPanel.

Thanks in advance

**Comment by salvadordf** [comment]
I put that iframe in a simple html like this : 
`<html><head></head><body><iframe allow="camera; microphone" src="https://meet.jit.si/test" name="jitsiConferenceFrame0" id="jitsiConferenceFrame0" allowfullscreen="true" style="height: 600px; width: 100%; border: 0px;"> </iframe></body></html>`
I uploaded it to my website and I tested the SimpleOSRBrowser demo with Lazarus. I could see this image : 
![SimpleOSRBrowser demo](https://www.briskbard.com/images/iframe.png)
The camera is out of focus and it gives a grainy image but it can be used for this test.
Perhaps the noise in the image was forcing the browser to refresh the iframe image constantly.

Please, try to resize your browser after you load the HTML. If you see the complete image in your camera then all you need is to call TChromium.Invalidate(PET_VIEW) or TChromium.WasResized when the TChromium.OnLoadEnd is triggered for the iframe.
