### ISSUE TITLE
Chrome extension web store

### ISSUE THREAD

**Issue by vilsonmagnus** [salvadordf/CEF4Delphi#207]
How to add a web store extension?

I need to open the following link: https://www.fsist.com.br/

**Comment by salvadordf** [comment]
CEF supports some of the APIs used by extensions but it's not complete yet : 
https://bitbucket.org/chromiumembedded/cef/issues/1947/add-support-for-chrome-extensions

You can use the CEF functions to load some extensions with CEF4Delphi but there's no demo showing how to do it.
