### ISSUE TITLE
Create a demo that shows how to load a browser extension

### ISSUE THREAD

**Issue by salvadordf** [salvadordf/CEF4Delphi#208]
CEF supports browser extensions : 
https://bitbucket.org/chromiumembedded/cef/issues/1947/add-support-for-chrome-extensions

CEF4Delphi exposes all the functions to load extensions and it's possible that we'll need new components to handle extensions easily. 

Not all the APIs are supported yet. Navigate to this URL to see the supported APIs so far : 
chrome://extensions-support

**Comment by salvadordf** [comment]
The latest commit includes 2 demos called **HelloWorldExt** and **PageColorExt** showing how to load browser extensions.

**Comment by bts22** [comment]
> The latest commit includes 2 demos called **HelloWorldExt** and **PageColorExt** showing how to load browser extensions.

Estou precisando usar a extensão da metamask, consegue me ajudar com isto? Te faço uma doação.

**Comment by littlesekii** [comment]
> > The latest commit includes 2 demos called **HelloWorldExt** and **PageColorExt** showing how to load browser extensions.
> 
> Estou precisando usar a extensão da metamask, consegue me ajudar com isto? Te faço uma doação.
> 
> Quando faço o load da extensão abaixo, o aplicativo fecha:
> 
> https://github.com/MetaMask/metamask-extension/releases

I was trying to add this too but I had the same problem.

**Comment by salvadordf** [comment]
The extensions support is very limited in CEF browsers using the normal mode. 

However, the new _Chrome runtime_ mode seems to have much better support but that mode is considered experimental for now. 

See the TinyBrowser and TinyBrowser2 demos for more details about the Chrome runtime mode.

Please, use our forums for more questions : 
https://www.briskbard.com/forum/
