### ISSUE TITLE
picture in picture problem

### ISSUE THREAD

**Issue by betafoxy** [salvadordf/CEF4Delphi#209]
when play video，click picture in picture menuitem，then the video hided,but no window popup....

![image](https://user-images.githubusercontent.com/45146564/61180754-cf2c7280-a64d-11e9-8065-ae3fca520bec.png)

**Comment by betafoxy** [comment]
CEF	74.1.19+gb62bacf+chromium-74.0.3729.157
Chromium	74.0.3729.157

**Comment by salvadordf** [comment]
I've never tried that but according to the tutorials for some chromium based browsers you would need to enable 3 switches : 
--enable-experimental-web-platform-features
--enable-picture-in-picture
--enable-surfaces-for-videos

The first two switches are listed in the "List of Chromium Command Line Switches" : 
https://peter.sh/experiments/chromium-command-line-switches/

I don't know why the last one is not in that list.

Remember that not all the switches in the "List of Chromium Command Line Switches" are supported by CEF.

Please, use our forum for more questions : 
https://www.briskbard.com/forum/

If you have problems registering in the forum just let me know and I'll activate your account manually.

**Comment by betafoxy** [comment]
ok, i'll register in the forum .
