### ISSUE TITLE
Does it support H.245?

### ISSUE THREAD

**Issue by lhsstudio** [salvadordf/CEF4Delphi#21]
I am very excited to find this open source project, thank you very much, but does it support H.245? How to make it support mp3 or MP4 format? Thank you!

**Comment by salvadordf** [comment]
That depends on the CEF3 binaries used with CEF4Delphi. The CEF3 binearies available at opensource.spotify.com are compiled with proprietary codecs disabled to avoid patent infrigement problems. However, if you compile the CEF3 binaries as described in the following URL, you'll be able to use all codecs. 

http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=13515

**Comment by lhsstudio** [comment]
OK, thanks a lot!, but it seems to be difficult to compile CEF3 binaries on my computer
