### ISSUE TITLE
Enhancement: Option to turn off site isolation

### ISSUE THREAD

**Issue by codebeat-nl** [salvadordf/CEF4Delphi#212]
Hi, found diffucalties (executing works fine but without results - cannot find/access documents DOM elements) to inject Javascript however because of site isolation it doesn't seems to work. There is no option, method, function to turn it off.

Tried the folowing:
```
- TChromium.executeJavaScript(  <jscode>, '', '' );
- TChromium.loadURL( 'javascript:{<jscode>}' );
```

What I try to do is selecting an element on a page, tried this with Firefox build-in Developers Notepad and is working fine. The code uses jQuery to find and select the element however in chromium the DOM is isolated and cannot find the element/any elements. Problem is not the code, it runs fine, the problem is the isolation.

It would be great to be able to turn off the isolation.

**Comment by salvadordf** [comment]
You can try different process models but CEF only supports the default model. 

Read this for more information : 
https://www.briskbard.com/forum/viewtopic.php?f=8&t=756

The list of switches and their meaning is here : 
https://peter.sh/experiments/chromium-command-line-switches/
