### ISSUE TITLE
OSR demos crash when resized since CEF 76

### ISSUE THREAD

**Issue by salvadordf** [salvadordf/CEF4Delphi#214]
All OSR demos crash since the CEF 76.1.5 update when the form is resized.

**Comment by kormizz** [comment]
I'm just rewriting FMXExternalPumpBrowser from TForm to installable TControl. I can confirm the crashes during component sizing somewhere deep inside libcef.dll. Any progress with this issue?
The sources of the component and demo application are included... It throws the error instantly after moving the splitter. Hope it helps!
[browser.zip](https://github.com/salvadordf/CEF4Delphi/files/3640131/browser.zip)

**Comment by salvadordf** [comment]
I debugged that error and the last steps in the trace are related to a new feature called "Viz" that is not completely implemented.
https://bitbucket.org/chromiumembedded/cef/issues/2575

Please, use the previous CEF4Delphi release if you need to use the OSR mode.

**Comment by kormizz** [comment]
OK understand... So please could you recommend me which revision of your repo is the best for my solution?
Thank you... ;)

**Comment by salvadordf** [comment]
https://github.com/salvadordf/CEF4Delphi/releases/tag/75.0.3770.100

**Comment by salvadordf** [comment]
The update to CEF 78.3.9 fixed this issue
