### ISSUE TITLE
Property and method are not compatible OnprocessMessageReceived and OnClose in TChromium

### ISSUE THREAD

**Issue by DmitryR** [salvadordf/CEF4Delphi#215]
when try use events OnProcessMessageReceived or OnClose in TChromium component getting an error "Property and method are not compatible"

**Comment by salvadordf** [comment]
Perhaps there's an old BPL or DCU file with different event parameters. Download the latest CEF4DElphi version, uninstall the previous version and install the new version.

If you still have problems after that, provide the name and version of the IDE (Delphi, Lazarus, C++ Builder?) that you're trying to use.

Please, use our forum for more questions :
https://www.briskbard.com/forum/index.php

**Comment by DmitryR** [comment]
Thanks... but issue still exists... no old bpl or dcu. downloaded latest version in zip.
old version uninstalled and deleted all files from disk
Using Delphi XE
installation works only Debug mode. Release don't work due of issues in dpk file config.
opened source and checked function event OnProcessMessageReceived
as you can see, on attached screenshot
![onProcessMessageReceived](https://user-images.githubusercontent.com/516966/62517570-52e21500-b830-11e9-9024-0cf636b6ffc6.png)
, at least it is function in TChromium class and interface CefChromiumEvents but type TOnProcessMessageReceived is procedure and also has additional parameter.
here is link to [downloaded zip](https://www.dropbox.com/s/trxpotyidw4h6o4/cef4delphi-master.zip?dl=0) that I have.

**Comment by salvadordf** [comment]
All IChromiumEvents procedures are used internally to trigger the TChromium events when a "handler" like ICefLoadHandler, ICefFocusHandler, ICefContextMenuHandler, etc executes one of its procedures or functions.

TChromium implements all IChromiumEvents procedures but you rarely need to override them. Usually you use the TChromium events.

To generate the procedure to handle an event, select the TChromium component in your form and double click the empty event box in the "Object inspector". This will create a procedure inside your form with the right parameters.

If you try to assign a different procedure type then you may get the "Property and method are not compatible" error message.
