### ISSUE TITLE
Error LoadString

### ISSUE THREAD

**Issue by yeahname5** [salvadordf/CEF4Delphi#218]
I can't use the commands

chromium.loadstring('<b>test</b>', 'http://mysite.com.br');
or
chromium.browser.mainframe.loadstring('<b>test</b>', 'http://mysite.com.br');

load a blank page
I need to enter "http://mysite.com.br" because I need its origin

I'm using the latest version

**Comment by salvadordf** [comment]
LoadString only works when there's already a renderer process.
https://magpcss.org/ceforum/viewtopic.php?f=6&t=14975&p=34178#p34178

As a workaround, try loading the URL "about:blank" before using LoadString.
