### ISSUE TITLE
doOnBeforeResourceLoad is not virtual

### ISSUE THREAD

**Issue by MrArachnid** [salvadordf/CEF4Delphi#22]
https://github.com/hgourvest/dcef3/issues/71 (still not fixed)
file uCEFChromium.pas
method doOnBeforeResourceLoad() should be virtual

**Comment by salvadordf** [comment]
I just uploaded a new version of CEF4Delphi with more virtual procedures in TChromium and a couple of new properties in TCEFApplication. 

Thanks for your report! :smile:

**Comment by MrArachnid** [comment]
Great work! Thank you!
