### ISSUE TITLE
[Q] How to copy TBitmap into JS Canvas Context?

### ISSUE THREAD

**Issue by GregSpa** [salvadordf/CEF4Delphi#220]
Hi,

As in the subject.
I'm trying to use for this NewArrayBuffer. However, can't find the documetation how to use it.
Some little example would be very helpfull.

Thank you,
Greg

**Comment by salvadordf** [comment]
Hi,

I'm not a JavaScript expert but this could be useful in this case :
https://stackoverflow.com/questions/3435528/how-do-i-load-a-bitmap-file-into-html5s-canvas
https://www.w3schools.com/tags/canvas_imagedata_data.asp

To send the image data you can use a process message but there is a limit of a few kilobytes in the binary message arguments so I would suggest to use a temporary bitmap file or a data base protected by a mutex to store the image data and then notify the render process when it's ready to be read.

Read the new code comments in the JSExtension and DOMVisitor demos for more details.

Please, use our forum if you have more questions : 
https://www.briskbard.com/forum/
