### ISSUE TITLE
Why DOMVisitor Demo No trigger VisitDomProc？

### ISSUE THREAD

**Issue by hzjzxp** [salvadordf/CEF4Delphi#221]
I want to get the DOM content of the current page. What should I do?

**Comment by salvadordf** [comment]
Hi,

TCefFastDomVisitor2.Create must be called in the renderer procecess and the DOMVisitor uses the GlobalCEFApp.OnProcessMessageReceived event to create it.

Delphi can only debug one process and it usually debugs the main application process, in this case CEF calls it "browser process".

Follow the instructions given here to debug the renderer process :
https://www.briskbard.com/index.php?lang=en&pageid=cef#debugging

For more questions, please use our forum at : 
https://www.briskbard.com/forum/
