### ISSUE TITLE
BUG : ICefPostData*->AddElement not work ?

### ISSUE THREAD

**Issue by morgancdip** [salvadordf/CEF4Delphi#222]
Hi,

I have a problem with sending parameters in post to an url.

The AddElement function of ICefPostData raises an exception (address problem). I am in Builder C ++.

Here is the function used:

void __fastcall TForm::WebPostDataChromium(TChromium* _nav, String _url, TStringList* _params)
{
	ICefStringMultimap* header = TCefStringMultimapOwn();
	header->Append("Content-Type", "application/x-www-form-urlencoded");
	ICefPostData* Data = TCefPostDataRef::New();
	ICefPostDataElement* elmt;
	for (int i = 0; i < _params->Count; i++)
        {
		if(i==0)
			elmt = CreateField(_params->Strings[i]);
		else
			elmt = CreateField("&" + _params->Strings[i]);
		Data->AddElement(elmt);   //<===  error here
	}
	ICefRequest* request = TCefRequestRef::New();
	request->SetMethod("POST");
	request->SetUrl(_url);
	request->SetPostData(Data);
	request->SetHeaderMap(header);
	_nav->LoadRequest(request);
}

//---------------------------------------------------------------------------

ICefPostDataElement* __fastcall TForm::CreateField(AnsiString _data)
{
	ICefPostDataElement* elmt = TCefPostDataElementOwn(true);
	elmt->SetToBytes(_data.Length(), _data.c_str());
	return elmt;
}

**Comment by salvadordf** [comment]
Please, download CEF4Delphi again.

I just fixed some bugs in the ICefPostData and TCefPostData declarations and I also added a POST example to the URLRequest demo.

I don't have a C++Builder license and I can't test it in that IDE but it works correctly in Delphi and Lazarus.
