### ISSUE TITLE
GlobalCEFApp.SitePerProcess:=True

### ISSUE THREAD

**Issue by raychl** [salvadordf/CEF4Delphi#223]
GlobalCEFApp.SitePerProcess:=True
this didn't work either.
GlobalCEFApp.AddCustomCommandLine('process-per-site','1');
this work.

**Comment by salvadordf** [comment]
--site-per-process and --process-per-site are not the same. 
One of them isolates and the other consolidates. 

Read this for more information :
https://peter.sh/experiments/chromium-command-line-switches/
http://www.chromium.org/developers/design-documents/process-models

All process models may work with CEF but only the default model is supported by CEF.
