### ISSUE TITLE
Mobile browsing mode

### ISSUE THREAD

**Issue by hzjzxp** [salvadordf/CEF4Delphi#224]
How do DevTools choose mobile browsing mode?

**Comment by salvadordf** [comment]
According to the CEF project maintainer, the DevTools have a device emulation mode but it is not currently supported in CEF.
https://magpcss.org/ceforum/viewtopic.php?f=6&t=14929#p33986

There is an open issue about this :
https://bitbucket.org/chromiumembedded/cef/issues/1992/devtools-device-emulation-mode-missing-in

This feature requires code changes in the CEF project and I can't do anything from the CEF4Delphi level.
https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=14499

However, some say that it might be possible to control the device emulation mode in the DevTools if you send remote commands :
https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=11952

Read this if you want to try that :
https://chromedevtools.github.io/devtools-protocol/
