### ISSUE TITLE
CanGoBack and CanGoForward of TChromium not work properly

### ISSUE THREAD

**Issue by morgancdip** [salvadordf/CEF4Delphi#225]
Call the function LoadUrl ("http://....")
Click on a link on the page -> once the page loaded -> CanGoBack = true it's good.
Call the GoBack function  -> after the end of loading CanGoBack = true and CanGoForward = false: it's not good,  it should be the opposite.
If I call the GoBack function again, it's about:blank that is in charge

**Comment by salvadordf** [comment]
I followed your instructions with the MiniBrowser demo in Lazarus and I couldn't reproduce this issue. I could navigate "back" and "forward" correctly. 

That demo uses the TChromium.OnLoadingStateChange event to update the the "back" and "forward" buttons and calls TChromium.GoBack and TChromium.GoForward when the user clicks on those buttons.

The code for TChromium.GoBack and TChromium.GoForward checks the value of TChromium.CanGoBack and TChromium.CanGoForward before navigating. That means that in my test, TChromium.CanGoBack and TChromium.CanGoForward returned the correct values.

Use the TChromium.OnLoadingStateChange event to enable or disable the "back" and "forward" buttons with the "canGoBack" and "canGoForward" parameters. 

Set TChromium.DefaultURL before calling TChromium.CreateBrowser to load a URL as soon as the browser is initialized or it will load "about:blank".

Please, download and install Lazarus (or Delphi) to make tests. It wouldn't be the first time a C++ Builder developer has unexpected issues using CEF4Delphi that can't be reproduced in other IDEs.

Remember that you can use our forum for questions and suggestions : 
https://www.briskbard.com/forum/

**Comment by morgancdip** [comment]
Thank you for the info.
I updated the back and next button info on the LoadEnd event and not in the LoadingStateChange event
