### ISSUE TITLE
flash issue

### ISSUE THREAD

**Issue by betafoxy** [salvadordf/CEF4Delphi#227]
**when i update to cef 76.1.13，all flash must right click to show，wow!!!     i test on the tabeddemo, have the same problem;  But, i tested on latest version BriskBard  with  cef 76.1.13, _no this problem_** 

ps: a flash page [](url)http://demo.imacros.net/Automate/FlashDemo

**on my exe or tabeddemo:**
![image](https://user-images.githubusercontent.com/45146564/66144901-474a7900-e63c-11e9-9cf6-8c813390b440.png)

**on BriskBard  with  cef 76.1.13：**
![image](https://user-images.githubusercontent.com/45146564/66144321-351c0b00-e63b-11e9-9958-08398ad9f0c0.png)

![image](https://user-images.githubusercontent.com/45146564/66144407-5e3c9b80-e63b-11e9-99d9-0af913a5b1c5.png)

**Comment by salvadordf** [comment]
Set TChromium.RunAllFlashInAllowMode to TRUE before the TChromium.CreateBrowser call.

**Comment by betafoxy** [comment]
lol,thanks....
