### ISSUE TITLE
Why Validation Errors？

### ISSUE THREAD

**Issue by hzjzxp** [salvadordf/CEF4Delphi#228]
When I use CEF Mini Browser to browse https://shop57616696.taobao.com, drag validation appears, but after dragging the corresponding operation, the browser did not open the correct page. What is the problem?
[http://www.hnsdjt.com/cef_error_20191012.jpg](url)

**Comment by salvadordf** [comment]
That address redirects the browser to another site and I don't see any drag validation.

Some websites show different content to different users. This might be one of those cases where the server is tracking the location of my IP and shows localized contents.

Please, use our forum for more questions : 
https://www.briskbard.com/forum/
