### ISSUE TITLE
Render process crash with large images

### ISSUE THREAD

**Issue by salvadordf** [salvadordf/CEF4Delphi#23]
The render process crashes when loading really large images.

The tests so far indicate that this only happen in 32bit application running in 64bit Windows.
All other bitness combinations seem to work fine.

More tests are needed.

**Comment by salvadordf** [comment]
CEF3 requires to set the LARGEADDRESSAWARE flag.
https://bitbucket.org/chromiumembedded/cef/issues/1855/windows-add-largeaddressaware-to-binary

In Delphi you set that flag adding {$SetPEFlags IMAGE_FILE_LARGE_ADDRESS_AWARE} in the DPR.

**Comment by qq18436558** [comment]
thanks
