### ISSUE TITLE
Compilation problems on linux

### ISSUE THREAD

**Issue by palsan** [salvadordf/CEF4Delphi#231]
Lazarus 2.0.4, FPC 3.0.4, CEF4Delphi master.
Compilation error 
`uCEFSentinel.pas(83,33) Error: Identifier not found "HWND"`
after chaging to HWND to THandle (which is probably not 100% correct) other errors arose
```
uCEFSentinel.pas(236,25) Error: Identifier not found "CEF_SENTINEL_START"
uCEFSentinel.pas(283,29) Error: Identifier not found "CEF_SENTINEL_DOCLOSE"
uCEFSentinel.pas(297,29) Error: Identifier not found "CEF_SENTINEL_DOCLOSE"
```
after commenting these out compilation is successful, but maybe thy must not be commented out but changed to something meaningful.

**Comment by palsan** [comment]
Also none of SimpleBrowser* example compile on linux. Compilation stops on WM_* reference, changing to LM_ messages does not work, because some WM_ messages do not have corresponding LM_ messages

**Comment by salvadordf** [comment]
I'm sorry but Linux is not supported yet.

I would love to add support for that OS but I still need to learn **a lot** about programming in Linux. 

I started adding some code to support it and I try to fix compilation issues from time to time but even when it compiles the demos crash in Linux.
