### ISSUE TITLE
hi after add cef to xe2 and rum minibrowser show dialog "CEF binaries missing !" why?

### ISSUE THREAD

**Issue by sazehapp** [salvadordf/CEF4Delphi#24]

**Comment by salvadordf** [comment]
That message means that at least some of the CEF3 binaries files can't be found.

Please, read this : 
https://www.briskbard.com/index.php?lang=en&pageid=cef

Take a look at the image with the final layout at the bottom of that web page and compare it with your layout to see what's missing.

Download the binaries from the links in the readme of this project.

**Comment by sazehapp** [comment]
tanks,
but show a new error
'the procedure entry point QueryUnBiasedInteraptTime could not located in the dynamic link library KERNEL32.dll'

**Comment by salvadordf** [comment]
CEF3 binaries need Windows 7 or newer to work.

**Comment by sazehapp** [comment]
ok, but I run dcef3 in windows server 2003  and good work.

**Comment by salvadordf** [comment]
It depends on the version of the CEF3 binaries.

The branch 2623 of CEF3 still supported Windows XP but since then you need Windows 7 or newer.
