### ISSUE TITLE
SimpleOSRBrowser shows a black screen in Windows 10

### ISSUE THREAD

**Issue by salvadordf** [salvadordf/CEF4Delphi#248]
The Lazarus/FPC version of the SimpleOSRBrowser demo shows a black screen in Windows 10 (version 1909)

It works correctly in Windows 7.

**Comment by pmccarenko** [comment]
HI!

If you set Trash variables (-gt) in Debugging options (see Other debugging info), the SimpleOSRBrowser demo works as it should in Windows 10 (version 1909). May be it help to you find a problem in Lazarus (I'm test it on Lazarus 2.0.9 and FPC 3.0.4).

**Comment by pmccarenko** [comment]
Remove the check “TempBufferBits <> nil” in chrmosrPaint and everything will work correctly.

**Comment by salvadordf** [comment]
Good catch! :D
Thank you very much for this fix! I'll upload the modified demo ASAP.
