### ISSUE TITLE
 CEF4 Does Not Open Form

### ISSUE THREAD

**Issue by emanueltobias** [salvadordf/CEF4Delphi#251]
When trying to access the site https://wf2.linx.com.br/ does not display the login screen, I tested on Delphi 10.3 32bits and Lazarus.

![image](https://user-images.githubusercontent.com/11075043/69920631-f81c9b00-1468-11ea-9522-a974821bb4d6.png)

![image](https://user-images.githubusercontent.com/11075043/69920653-31eda180-1469-11ea-852f-57b31471a9f5.png)

**Comment by salvadordf** [comment]
You need to use the TChromium.OnGetAuthCredentials event and set the "Result" parameter to true.

Save the parameters and send a windows message to the main form to show a custom dialog asking for the username and password in the main thread. Then call callback.continue with the username and password. 

Remember to set your copy of the callback parameter to nil after that to avoid shutdown issues.

Read this for more information :
https://magpcss.org/ceforum/apidocs3/projects/(default)/CefRequestHandler.html#GetAuthCredentials(CefRefPtr%3CCefBrowser%3E,constCefString&,bool,constCefString&,int,constCefString&,constCefString&,CefRefPtr%3CCefAuthCallback%3E)
https://magpcss.org/ceforum/apidocs3/projects/(default)/CefAuthCallback.html
