### ISSUE TITLE
Forward shortcut keys

### ISSUE THREAD

**Issue by LeventeKocsis** [salvadordf/CEF4Delphi#252]
Hi,

We are using Chromium browser in a tabbed MDI application. When the Chromium tab is focused, the shortcut key from the application are not functional.
Is there any possibility to forward them?

Thank you and best regards

**Comment by salvadordf** [comment]
Hi,

You need to use the TChromium.OnPreKeyEvent and TChromium.OnKeyEvent events to forward those keys to your controls.

Several demos use those events and MiniBrowser use them here : 
https://github.com/salvadordf/CEF4Delphi/blob/c99d14c8f01d32ed16eacb10c86a0fefcce32172/demos/Delphi_VCL/MiniBrowser/uMiniBrowser.pas#L817
https://github.com/salvadordf/CEF4Delphi/blob/c99d14c8f01d32ed16eacb10c86a0fefcce32172/demos/Delphi_VCL/MiniBrowser/uMiniBrowser.pas#L659

Read this for more information about those events : 
https://magpcss.org/ceforum/apidocs3/projects/(default)/CefKeyboardHandler.html

For more questions please use our forum at : 
https://www.briskbard.com/forum/
