### ISSUE TITLE
SimpleOSRBrowser demo crashes in Linux

### ISSUE THREAD

**Issue by salvadordf** [salvadordf/CEF4Delphi#255]
The SimpleOSRBrowser demo for Lazarus in Linux crashes at initialization.

If we don't use the GlobalCEFApp properties to set the CEF binaries directories we get a '_RunError(232)_' error.

If we use the GlobalCEFApp properties to set the CEF binaries directories we get a '_External: SIGABRT_' error.

**Comment by giovanierthal** [comment]
I didn't look at the sources of your project.

But to work with threads in linux, you need to add the cthreads unit.

https://forum.lazarus.freepascal.org/index.php?topic=4377.0

If I add this unit to my project, it starts, but immediately closes.

Is this information useful?

**Comment by salvadordf** [comment]
Thank you very much for this information! :-D

After reading that forum post I see that I may also need to add the dUseCThreads package.

**Comment by salvadordf** [comment]
I just added the -dUseCThreads compiler option to the Linux demos but they close automatically. Sometimes they show a External: SIGABRT error and sometimes no error at all.

GlobalCEFApp seems to initialize correctly and the form calls TChromium.CreateBrowser correctly but TChromium.OnAfterCreated is not triggered.

**Comment by giovanierthal** [comment]
In my case there is no error.

Only the GlobalCEFApp.StartMainProcess call returns false.

Instead of using PostMessage, as in your demo, I use: https://wiki.freepascal.org/Asynchronous_Calls

I also commented on the following code:

procedure WMMove(var aMessage : TWMMove); message WM_MOVE;
procedure WMMoving(var aMessage : TMessage); message WM_MOVING;
procedure WMEnterMenuLoop(var aMessage: TMessage); message WM_ENTERMENULOOP;
procedure WMExitMenuLoop(var aMessage: TMessage); message WM_EXITMENULOOP;

**Comment by giovanierthal** [comment]
Looking patiently, I realized that he is not finding the libraries.

https://imgur.com/SWv1dtG

GlobalCEFApp                     := TCefApplication.Create;
GlobalCEFApp.FrameworkDirPath     := 'CEFLib/';
GlobalCEFApp.ResourcesDirPath     := 'CEFLib/';
GlobalCEFApp.LocalesDirPath       := 'CEFLib/locales/';
GlobalCEFApp.cache                := 'CEFData/cache/';
GlobalCEFApp.UserDataPath         := 'CEFData/User Data/';
GlobalCEFApp.LogFile          := 'cef.log';
GlobalCEFApp.LogSeverity      := LOGSEVERITY_VERBOSE;   

Only this variable is false:

TempMissingFrm     := not(CheckDLLs(FFrameworkDirPath, FMissingLibFiles));

**Comment by baigtsa** [comment]
Hello, It is a pleasure to participate or at least try. My English is not good but I will try to explain.

Initially I tried to run my application under linux Mint, at first I couldn't even run it. I had to check the option "DisableLoadSymbolsForLibraries" under Tools-> Options-> Debugger-> General.

Then add the option "-dUseCThreads" without forgetting to add at the beginning of my code:
```PASCAL
{$IFDEF UNIX}{$IFDEF UseCThreads}
  cthreads,
  cmem,
  //heaptrc, //This is another attempt
  {$ENDIF}
```
However, I only got to show me a SIGABRT error, later I changed the declarations "stdcall" with "cdecl" and it opened but closed immediately. I use macros in my cef.inc:

```PASCAL
{$MACRO ON}
{$IFDEF WINDOWS}
  {$DEFINE stdcdecl:=stdcall}
{$ELSE}
  {$DEFINE stdcdecl:=cdecl}
{$ENDIF}
```
Such as:
```PASCAL
procedure _free_string(str: PChar16); stdcdecl;
begin
  if (str <> nil) then FreeMem(str);
end;
```
Now the project opens without errors but closes automatically.

Finally looking for information about it I found the following:
[https://bitbucket.org/chromiumembedded/cef/issues/2512](url)
I tried to do the implementation, but I didn't know what to do with "g_main_loop_run".

Some code that could be useful (lpr):
```PASCAL
uses
  {$IFDEF UNIX}{$IFDEF UseCThreads}
  cthreads,
  cmem,
  //heaptrc, //This is another attempt
  xlib,
  {$ENDIF}

  {$ENDIF}
  Interfaces, // this includes the LCL widgetset
  Forms, main
  { you can add units after this }
  ,uCEFApplication
  ,uCEFTypes
  ,uCEFConstants, Utilerias, fDownloads
  ;

{$R *.res}

begin
  XInitThreads;
  IsMultithread:=true;  
```
In my main form, I try to make a size change in xdisplay, but I can no longer complete it.

```PASCAL
procedure TMainForm.ViewerResize(Sender: TObject);
Var
  xdisplay: PXDisplay;
  xwindow: TWindow;
  changes: TXWindowChanges;
```
I hope this gives you some idea or help.

Regards

**Comment by salvadordf** [comment]
Thanks for all your help! :)

The latest update fixes this crash and this demo can navigate although it still has some other issues.

I'll add new issue pages in GitHub about them.
