### ISSUE TITLE
SimpleBrowser2 demo crashes in Linux

### ISSUE THREAD

**Issue by salvadordf** [salvadordf/CEF4Delphi#256]
The SimpleBrowser2 demo for Lazarus in Linux crashes at initialization with a '_RunError(232)_' error.

**Comment by RDL-28** [comment]
![Снимок экрана_2020-02-21_22-44-05](https://user-images.githubusercontent.com/33255217/75039306-b3e6e700-54fb-11ea-80fe-f4e71516283f.png)

**Comment by dibok** [comment]
I'm also having same issue. Without cthreads getting RunError(232), with cthreads getting SIGSEGV in file ../../base/threading/sequence_local_storage_map.cc
Tested on CEF standard distribution 80.0.3987.132 from there:
http://opensource.spotify.com/cefbuilds/cef_binary_80.0.7%2Bgd9fd476%2Bchromium-80.0.3987.132_linux64.tar.bz2
CEF log:
```
[0328/175420.404052:INFO:cpu_info.cc(53)] Available number of cores: 4
[0328/175420.404124:VERBOSE1:zygote_main_linux.cc(215)] ZygoteMain: initializing 0 fork delegates
[0328/175420.408671:VERBOSE1:pref_proxy_config_tracker_impl.cc(184)] 0x7fffc805b890: set chrome proxy config service to 0x7fffc805c2a0
[0328/175420.411637:VERBOSE1:webrtc_internals.cc(120)] Could not get the download directory.
```
Linux KDE Neon 5.18

**Comment by salvadordf** [comment]
The reason of this crash is the WidgetSet initialization done in the "Interfaces" unit. GTK must be initialized after the GlobalCEFApp.StartMainProcess call.

The SimpleOSRBrowser demo already has a fix for this with a custom "Interfaces" unit.

**Comment by salvadordf** [comment]
The latest update fixed this issue.

Thank you very much for all your help! :D
