### ISSUE TITLE
FMXExternalPumpBrowser

### ISSUE THREAD

**Issue by SoftacomDevelopment** [salvadordf/CEF4Delphi#257]
Win10x64, RAD 10.3.2, CEF4Delphi 78.3.9, CEF Release binaries
Is this a bug or feature: 
I moved initialization from project file to separate form (not FMXExternalPumpBrowserForm) and the app become broken: when I create FMXExternalPumpBrowserForm from my form - browser dont react on any comands and my form becames be cloned many times.    

(modified demo app sources and screenshots of the app behavior attached)
[FMXExternalPumpBrowser.zip](https://github.com/salvadordf/CEF4Delphi/files/3983350/FMXExternalPumpBrowser.zip)
![PumpBrowser](https://user-images.githubusercontent.com/29306435/71170377-2cb39380-226c-11ea-9778-0a704db06063.jpg)
![PumpBrowser-NewForm](https://user-images.githubusercontent.com/29306435/71170379-2cb39380-226c-11ea-8a4b-959b8f364cab.png)

**Comment by salvadordf** [comment]
Please, read these documents : 
http://www.chromium.org/developers/design-documents/multi-process-architecture
https://www.briskbard.com/index.php?lang=en&pageid=cef

CEF uses several processes for all the browser tasks. 

By default, CEF launches other processes using your application's EXE and you need to initialize it correctly or you will end up with several instances of your application running at the same time.

If you need to initialize CEF when an application is already running you need to use a different EXE for the subprocesses as you can see in the "_SubProcess_" demo, inside the /demos/Delphi_VCL directory.

Remember that CEF can only be initialized once per process. Usually, an application would initialize CEF once to create and destroy as many browsers as needed and then it would destroy GlobalCEFApp when all the browsers are properly closed.
