### ISSUE TITLE
TCefApplication.DisableExtensions := True causes Access Violation

### ISSUE THREAD

**Issue by zizzo81** [salvadordf/CEF4Delphi#258]
Setting

`GlobalCEFApp.DisableExtensions := True;`

causes a NULL pointer access violation when `cef_initialize` gets called at `uCEFApplicationCore.pas:1194`.

**Comment by salvadordf** [comment]
The official CEF sample application also crashes when you run it with these parameters : 
cefclient.exe --disable-extensions --no-sandbox --multi-threaded-message-loop

Perhaps this is a regression of this CEF issue : 
https://bitbucket.org/chromiumembedded/cef/issues/2777/cefclient-crash-with-disable-extensions

I'll take a look as soon as I can. Meanwhile, avoid setting that property.

**Comment by salvadordf** [comment]
I just added a new issue in the CEF project about this :
https://bitbucket.org/chromiumembedded/cef/issues/2852/cefclient-crash-with-disable-extensions

**Comment by salvadordf** [comment]
This issue was fixed in the update to CEF 79.1.3
https://github.com/salvadordf/CEF4Delphi/commit/c14be3764898a471b426660aaa11a73603c26054
