### ISSUE TITLE
<datalist> tag not working

### ISSUE THREAD

**Issue by grigandal625** [salvadordf/CEF4Delphi#259]
I don’t know what it depends on
But, for example, when I open [this site](https://jsfiddle.net/myfce5fL/), the datalist html tag on it does not work on click

Windows 10
Embarcadero RAD Studio 10.2

**Comment by salvadordf** [comment]
The official CEF sample application has the same issue with the datalist tag. 

I only could test it with Chromium 79.0.3945.79 on Linux and it works but CEF uses a slightly different version (Chromium 79.0.3945.88)

This seems to be a Blink issue and I can't do anything to fix it in CEF4Delphi.
