### ISSUE TITLE
Dropdown control appearing in wrong place after form moved

### ISSUE THREAD

**Issue by brianjford** [salvadordf/CEF4Delphi#26]
If you go to a page with an HTML dropdown control, open/close it, then move the browser window and reopen the control it will appear in the wrong place.  This issue can be seen using the SimpleBrowser demo.

It sounds just like this issue from CEF which has been resolved:  https://bitbucket.org/chromiumembedded/cef/issues/1208/combobox-drop-down-menu-is-displaced

It may require hooking something up to the WM_MOVE message; (I'm not too sure as I didn't look into it too much).

**Comment by brianjford** [comment]
I think if you call ICefBrowserHost.NotifyMoveOrResizeStarted anytime the delphi form is moved this resolves the issue..

This quick hack to the simplebrowser looks like it worked:

procedure OnMove(var Msg: TWMMove); message WM_MOVE;

procedure TForm1.OnMove(var Msg: TWMMove);
begin
  if ChromiumWindow1.ChromiumBrowser.Browser <> nil then
    ChromiumWindow1.ChromiumBrowser.Browser.Host.NotifyMoveOrResizeStarted;
end;

**Comment by salvadordf** [comment]
Thanks! :smile: 

I'll add this in the next version.

**Comment by salvadordf** [comment]
Please download the latest update
