### ISSUE TITLE
Touch screen PDF

### ISSUE THREAD

**Issue by prcubedigitalmedia** [salvadordf/CEF4Delphi#261]
How to intercept clicks on a PDF?

**Comment by salvadordf** [comment]
Hi,

In case of an application with a TChromium in normal mode you can use the TChromium.OnRenderCompMsg event. 

If your app runs in Windows 8/8.1/10 you would need to intercept the WM_POINTERUP and WM_POINTERDOWN messages.

If your application uses a browser in OSR mode you can use the TBufferPanel.OnPointerUp and TBufferPanel.OnPointerDown events.

Please, use our forum for more questions : 
https://www.briskbard.com/forum/

**Comment by prcubedigitalmedia** [comment]
Thank you for the answer.
TChromium.OnRenderCompMsg works but not with PDFs.
