### ISSUE TITLE
Application lock when cef_shutdown() with "--single-process" command switch

### ISSUE THREAD

**Issue by charoleizer** [salvadordf/CEF4Delphi#262]
When I active the Single Process Command,
`GlobalCEFApp.AddCustomCommandLine('--single-process');`

in the end of the project file, I cannot free the `GlobalCEFApp`, because it's lock when try to call `cef_shutdown();` from `libcef.dll`

It happens on `HEAD `revision with 79.1.36 of `licbcef.dll`

When I try with 77.x.x version of `libcef.dll`, the IDE's debugger give me an error message (Not a understandable message). Exatly like https://github.com/salvadordf/CEF4Delphi/issues/230

I just found it, tring to solve all leaks of memory and memory consumption.
So, if is there a correct way to make it free of leaks and with low memory consumption, please tell me.

PS: Switchs i'm using:

```
  GlobalCEFApp.AddCustomCommandLine('--single-process');
  GlobalCEFApp.AddCustomCommandLine('--disable-plugins');
  GlobalCEFApp.AddCustomCommandLine('--aggressive-cache-discard');
  GlobalCEFApp.AddCustomCommandLine('--aggressive-tab-discard');
  GlobalCEFApp.AddCustomCommandLine('--disable-3d-apis');
  GlobalCEFApp.AddCustomCommandLine('--no-experiments');
  GlobalCEFApp.AddCustomCommandLine('--no-pings');
  GlobalCEFApp.AddCustomCommandLine('--disable-hang-monitor');
  GlobalCEFApp.AddCustomCommandLine('--disable-metrics');
  GlobalCEFApp.AddCustomCommandLine('--disable-metrics-reporting');
  GlobalCEFApp.AddCustomCommandLine('--disable-extensions');
  GlobalCEFApp.AddCustomCommandLine('--no-sandbox');
```

**Comment by salvadordf** [comment]
Hi,

The single process mode is not supported by CEF and it should only be used for debugging purposes. It's known to cause issues.

Use the code in the demos as a template for your application and read this page for more information about debugging applications that use CEF4Delphi : 
https://www.briskbard.com/index.php?lang=en&pageid=cef

There's also a ton of information about CEF4Delphi in our forums : 
https://www.briskbard.com/forum/

Please, use the forums for more questions.
