### ISSUE TITLE
can not use outside var in GlobalCEFApp.OnContextCreated

### ISSUE THREAD

**Issue by kevinsui581** [salvadordf/CEF4Delphi#264]
I need bind a value in OnContextCreated by SetValueByKey, the value is variable, i define it outside the procedure in main process。
I found the value is not correct when access it in browser
how to use the var bind value by browser to use

**Comment by salvadordf** [comment]
Hi,

GlobalCEFApp.OnContextCreated is executed in the render process.. If you need to read that value you can use a JavaScript extension that sends the information to the browser process with a process message. 

Open the JSExtension or JSRTTIExtension demos and see the code for the "_sendresulttobrowser_" procedure in the uTestExtension unit for more details.

Read the code comments in the JSExtension demo for a detailed explanation about the JavaScript extensions.

Please, use our forum for more questions : 
https://www.briskbard.com/forum/
