### ISSUE TITLE
Issue with some content

### ISSUE THREAD

**Issue by kdevil88** [salvadordf/CEF4Delphi#267]
Hello, i have app for displaying video streams. Most of them are from youtube, twitch or with flash. I have enabled flash using "RunAllFlashInAllowMode" option, but youtube, twitch or video from some other sources still not wokring...
For example if i open MiniBrowser test project and navigate to youtube.com i got this - [https://pasteboard.co/IZuMhP2.png](https://pasteboard.co/IZuMhP2.png)

How to enable html5 video support, why even youtube is not opening? Thanks!

**Comment by salvadordf** [comment]
Hi,

YouTube.com needs a special workaround to show the page. Read this forum thread for more information : 
https://www.briskbard.com/forum/viewtopic.php?f=8&t=1193

You may have to build the CEF binaries with proprietary codec support to watch those videos. Read this for more information : 
https://www.briskbard.com/index.php?lang=en&pageid=cef#codecs

Read this guide to build the CEF binaries : 
https://www.briskbard.com/forum/viewtopic.php?f=10&t=1097
