### ISSUE TITLE
Incorrect browser size when form is resized in OSR mode with a high DPI screen

### ISSUE THREAD

**Issue by salvadordf** [salvadordf/CEF4Delphi#271]
The CEF library has a resize issue in OSR mode with high DPI screens :
https://bitbucket.org/chromiumembedded/cef/issues/2833/osr-gpu-consume-cpu-and-may-not-draw

Usually, when the browser is resized the application calls TChromium.WasResized. That call will trigger the TChromium.OnGetViewRect event to allow CEF to get the new browser size, render the contents and trigger the TChromium.OnPaint. 

However, the TChromium.OnGetViewRect event is not always triggered when you have a high DPI screen and the browser will not be rendered with the new size.    

According to this comment in the previous CEF issue, there's a workaround : 
https://bitbucket.org/chromiumembedded/cef/issues/2833/osr-gpu-consume-cpu-and-may-not-draw#comment-55908363

This issue only happens when GlobalCEFApp.EnableGPU is TRUE.

You will avoid this issue if you always set the "rect" parameter in the TChromium.OnGetViewRect event with values that will be converted to integer when you apply the screen scale.

**Comment by salvadordf** [comment]
This seems to be fixed in the latest CEF binaries

**Comment by ange007** [comment]
Thats bug not only in OSR.

Last version (80.1.15):
![image](https://user-images.githubusercontent.com/2736539/78473402-19f49a00-7749-11ea-962a-d43c0fe36dcb.png)

In OSR now all is fine.

**Comment by salvadordf** [comment]
I can't reproduce this issue in "normal mode" using the FMXTabbedBrowser demo on Windows 7 and Delphi 10.3.3.

TBrowserFrame.WindowParentLay should trigger the OnResize event and execute TBrowserFrame.WindowParentLayResize, which executes TBrowserFrame.ResizeBrowser to set the TFMXWindowParent bounds with the TBrowserFrame.GetFMXWindowParentRect information.

If you use a different Delphi version please check that all those steps are executed.

**Comment by ange007** [comment]
Windows 10, Delphi 10.3.3, Screen Resolution: 2560*1440, Scale: 125%

TBrowserFrame.WindowParentLayResize it works.
This bug reproduse and in ```FMXToolBoxBrowser``` and ```SimpleFMXBrowser``` for me.

![image](https://user-images.githubusercontent.com/2736539/78539428-394bff80-77fb-11ea-99ff-64f0e54504fb.png)

![image](https://user-images.githubusercontent.com/2736539/78539521-5e407280-77fb-11ea-81a0-dd50ff497361.png)

If use Screen Resolution: 1920*1080, Scale: 100% - thats ok:
![image](https://user-images.githubusercontent.com/2736539/78540268-94322680-77fc-11ea-8b04-b1e80f561bf7.png)

![image](https://user-images.githubusercontent.com/2736539/78540202-7664c180-77fc-11ea-9c7a-f9aceb8f1615.png)
