### ISSUE TITLE
Wrong TFMXWindowParent size and position with high DPI monitor

### ISSUE THREAD

**Issue by ange007** [salvadordf/CEF4Delphi#273]
Hello.
I'm trying to position the TFMXChromium on a TMultiView form but the browser ignores the display layers.

![image](https://user-images.githubusercontent.com/2736539/78498560-ab690980-7753-11ea-83bd-40bbb1b75062.png)

This can be implemented without OSR _(it spoils the display quality)_.

**Comment by salvadordf** [comment]
This is probably caused by the same reason you mentioned here : 
https://github.com/salvadordf/CEF4Delphi/issues/271

Please check that the resize event in TBrowserFrame.WindowParentLay is executed.

**Comment by ange007** [comment]
Screen Resolution: 1920*1080, Scale: 100%:
![image](https://user-images.githubusercontent.com/2736539/78539936-07876880-77fc-11ea-8db8-b471a18dfa95.png)

There is no bug with size, but positioning is violated.

**Comment by salvadordf** [comment]
Now I can reproduce this issue. Thanks!

I'll try to fix it as soon as I can.

**Comment by salvadordf** [comment]
Please, download CEF4Delphi again. The latest commit fixes the size and position of TFMXWindowParent.

It may be scaled with a 1 px error sometimes, specially with monitors that use a 125% scale. 

If anyone knows a better solution to get the real coordinates and dimensions please let me know or create a "pull request" with the code changes. 

Thanks!

**Comment by ange007** [comment]
The size issue is really resolved. But the overlap by the browser of other elements remained. Is there any solution?

![image](https://user-images.githubusercontent.com/2736539/78985137-abd91a00-7b30-11ea-9800-cbd4027d1c43.png)

**Comment by salvadordf** [comment]
This is what I get with the unmodified FMXTabbedBrowser demo on Windows 10, Delphi 10.3.3 and a monitor with 125% scaling.
![Sin título](https://user-images.githubusercontent.com/17946341/78990053-b0540180-7b35-11ea-948c-a678b97c8dec.png)

I also tested that demo with 150% and 175% scaling and the browser position was correct. 
Have you applied any patch or update to Delphi?

I'll see if I can find an alternative method to get the real coordinates.

**Comment by ange007** [comment]
No-no, now i told about layer position (z-index).
I try to use TMultiView component, this is a drop down panel. Which should be drawn on top of the element.

**Comment by salvadordf** [comment]
Sorry, I forgot about the TMultiView.

As you can see in the code, TFMXWindowParent inherits from a TCommonCustomForm and it's created at run-time as a child of the main form.

This is probably the cause of the z-index issue you see. In this case I would recommend you to use a browser in off-screen mode (OSR mode).

Use the **FMXExternalPumpBrowser** demo as a template for your application.
