### ISSUE TITLE
Insert form into html page

### ISSUE THREAD

**Issue by yarockiisergei** [salvadordf/CEF4Delphi#276]
Hi. Tell me is it possible to embed a Delphi Form in the html page and output it in the right place using the tag? Many players are installed as extensions and displayed in special tags.

**Comment by salvadordf** [comment]
Hi,

CEF support for browser extensions is limited at this moment and as far as I know, it's not possible to embed those Delphi controls using an extension.

However, you can add HTML controls and create a JavaScript extension to communicate to Delphi. This way you can send all the control values, events, etc to Delphi.

Please, use our forum for more questions :
https://www.briskbard.com/forum/
