### ISSUE TITLE
Constants already defined

### ISSUE THREAD

**Issue by petko** [salvadordf/CEF4Delphi#277]
Some constants added in the recent CEF4Delphi version are already defined in winuser.h. They give the following error:
`[bcc32 Error] uCEFConstants.hpp(509): E2040 Declaration terminated incorrectly`

When I comment them out in the uCEFConstants.hpp, my app compiles. The constants are:
```
WM_TOUCH                 = $0240;
WM_POINTERUPDATE         = $0245;
WM_POINTERDOWN           = $0246;
WM_POINTERUP             = $0247;
USER_DEFAULT_SCREEN_DPI = 96;
```

I have also had to comment out the `RtlGetVersion` and because of this the `GetWindowsMajorMinorVersion` in the uCEFMiscFunctions.pas, because `RtlGetVersion` gave me a similar error.

**Comment by salvadordf** [comment]
I renamed RtlGetVersion and I also added some compiler directives to check if those constants are declared.
Please, check this is fixed in your Delphi installation and close this issue.

**Comment by petko** [comment]
The defines work fine, but the RtlGetVersion gives me the following error:
```
[ilink32 Error] Error: Unresolved external 'RtlGetVersion' referenced from ...\UCEFMISCFUNCTIONS.OBJ
```

**Comment by salvadordf** [comment]
I removed the CustomRtlGetVersion function and I also modified the GetWindowsMajorMinorVersion function to load it dynamically. This should fix this issue.
