### ISSUE TITLE
Old demos.

### ISSUE THREAD

**Issue by TAGRUAT0** [salvadordf/CEF4Delphi#279]
**SimpleFMXBrowser** from **demos** not compiling and is the old, please update.
Others demos i don't checked.

**Comment by salvadordf** [comment]
I just tested all demos again with Delphi 10.3.3 and I could build them without issues. Perhaps the recent changes in some constants are causing issues with older Delphi versions.

What Delphi version are you using?
What's the error message?

**Comment by TAGRUAT0** [comment]
Version 10.2.
![image](https://user-images.githubusercontent.com/65071735/82121534-875b0800-9796-11ea-8d2f-dbcd3c55053d.png)

**Comment by salvadordf** [comment]
Please make sure CEF4Delphi was installed with the "CEF4Delphi_FMX.dproj" project file and not with "CEF4Delphi.dproj".

**Comment by TAGRUAT0** [comment]
I installed **CEF4Delphi** again, but this is time I installed only **CEF4Delphi_FMX.dproj**.
Sorry, I thought that **CEF4Delphi.dproj** installs everything, and I forgot about this
![image](https://user-images.githubusercontent.com/65071735/82122530-f20f4200-979c-11ea-807c-144b3a683912.png)
