### ISSUE TITLE
Not TUrlParts ?

### ISSUE THREAD

**Issue by Topgen** [salvadordf/CEF4Delphi#28]
Why removed TUrlParts?

(dcef3 )

> var
>   u: TUrlParts;
> begin
>   u.host := 'github.com';
>   request.Url := CefCreateUrl(u);

(dcef4)

> E2003 Undeclared identifier: 'TUrlParts'
> E2003 Undeclared identifier: 'CefCreateUrl'

**Comment by salvadordf** [comment]
TURLParts is defined in uCEFTypes.pas

I'll add the missing URL functions in the next version of CEF4Delphi.

Thanks!

**Comment by salvadordf** [comment]
Please download the latest version of CEF4Delphi. 
Let me know if you need more functions from DCEF3.
