### ISSUE TITLE
Exception instead of dialogue

### ISSUE THREAD

**Issue by Echelon78** [salvadordf/CEF4Delphi#280]
https://github.com/salvadordf/CEF4Delphi/blob/c44023cb21b315b30b3f62d7e39d39d905d00511/source/uCEFApplicationCore.pas#L938

I suggest using an exception instead of a dialogue. If the application can be run without Chromium support, the exception can be handled, the dialog cannot.

            raise Exception.Create(TempString);
//            ShowErrorMessageDlg(TempString);

**Comment by salvadordf** [comment]
I added a new property to GlobalCEFApp called "_MissingBinariesException_" to raise that exception. Thanks for the suggestion! :)
