### ISSUE TITLE
Slowdown problem (Please Help)

### ISSUE THREAD

**Issue by yesilcimenahmet** [salvadordf/CEF4Delphi#281]
Hi,

The project I developed with Javascript + WebGL works incredibly fast on Chrome. But when I use CEF4 with Delphi, it is also incredibly slow. I compile it as 64bit + Release. I also use CEF binary files as Release. (I also tried 32 Bit)
I do not add anything to the Delphi project, in the examples you wrote, I just enter the link in my project address that runs on localhost. Please suggest a way for me to solve this.

Thanks

**Comment by salvadordf** [comment]
Hi,

Try enabling hardware acceleration. Add this before the _GlobalCEFApp.StartMainProcess_ call in the DPR file :
`GlobalCEFApp.EnableGPU := True;`

**Comment by yesilcimenahmet** [comment]
thanks a lot! worked.
