### ISSUE TITLE
CEF bug the modal stack in application

### ISSUE THREAD

**Issue by betonetotbo** [salvadordf/CEF4Delphi#282]
I'm using CEF4Delphi to display some charts. This charts are created using [ApexCharts](apexcharts.com). 

At this charts, there are a "hamburguer" icon on the right, who opens a popupmenu (pure html). When my user click on it my delphi application bug the modals. 

All modals after clicking on the hamburguer are created behind the main form. And I cannot access them anymore.

Here is the bug:

![bug-cef](https://user-images.githubusercontent.com/5444923/85028997-300fd500-b152-11ea-9cd6-e6a87a09ebce.gif)

And here is the code:

[bug-cef.zip](https://github.com/salvadordf/CEF4Delphi/files/4798960/bug-cef.zip)

My application is build with Delphi 7.1 enterprise (I'm not able to migrate to a new delphi version because incompatible routines).

And the windows host is Windows 7 x64 (6.1.7601). On Windows 10 (for example) it doesn't occurs.
The problem also occurred in WIndows 2008 R2 (6.1.7601).

**Comment by betonetotbo** [comment]
As workaround (for now) I created the class `TFixChromiumWindow = class(TChromiumWindow)`, and
override the `procedure WndProc(var Message: TMessage);`, and put inside this:
```
procedure TFixChromiumWindow .WndProc(var Message: TMessage);
  inherited;
  if Message.msg = WM_PARENTNOTIFY then
    with Application.MainForm do
      SetWindowPos(Handle, HWND_NOTOPMOST, Left, Top, Width, Height, SWP_NOMOVE or SWP_NOSIZE);
end;
```
I identified that after the message `WM_PARENTNOTIFY` the problem starts, so this guarantee the Main Form to stay where it need to stay.

**Comment by betonetotbo** [comment]
Here we can see the active windows on my device, note that the window stack precedence is from the topmost to the bottommost.

![image](https://user-images.githubusercontent.com/5444923/85131115-92c5a700-b20c-11ea-873d-c5807ab2592a.png)

**Comment by salvadordf** [comment]
Thank you for reporting this issue! 
This could be caused by several things and right now I'm very busy but I'll try to take a look as soon as possible.

**Comment by salvadordf** [comment]
This seems to be a Delphi 7 issue : 
https://stackoverflow.com/questions/8007449/delphi-messagebox-appearing-behind-other-form

Replace the MessageDlg line with this : 
`if Application.MessageBox('Deseja realmente fechar?','Title', + MB_APPLMODAL + MB_TOPMOST + MB_ICONQUESTION + MB_YESNO) = IDNO then exit;`

**Comment by betonetotbo** [comment]
The problem is that this bug occurs with other modals of my application and not only the MessageDlg.

**Comment by salvadordf** [comment]
Please, use our forums and provide all the details to find workarounds like the previous MessageBox example.

https://www.briskbard.com/forum/

**Comment by betonetotbo** [comment]
@salvadordf , I tried to change your code at `uCEFChromiumCore.pas` at the method `InitializeWindowInfo`, I just added `WS_EX_NOACTIVATE` at the call to `WindowInfoAsChild` and seems to worked!

I will to test harder this solution and will report.

This change was based on post: https://www.briskbard.com/forum/viewtopic.php?t=723#p3299

**Comment by salvadordf** [comment]
I'm glad that it worked for you but please, also read the linked CEF issue. Another developer using CEF4Delphi pointed out some possible side effects : 
https://bitbucket.org/chromiumembedded/cef/issues/1856/branch-2526-cef-activates-browser-window

**Comment by salvadordf** [comment]
I just uploaded a new version of CEF4Delphi with a new TChromium.DefaultWindowInfoExStyle property to modify the ExStyle easily. 

Try setting it to WS_EX_NOACTIVATE before the TChromium.CreateBrowser call.

**Comment by betonetotbo** [comment]
> I just uploaded a new version of CEF4Delphi with a new TChromium.DefaultWindowInfoExStyle property to modify the ExStyle easily.
> 
> Try setting it to WS_EX_NOACTIVATE before the TChromium.CreateBrowser call.

Solved! Thanks!

PS: there will be a release or just download the master version?

**Comment by salvadordf** [comment]
That feature is only available at the master version at this moment. 
I'll create a new release with this in a few weeks when CEF4Delphi is updated to CEF 84.

**Comment by betonetotbo** [comment]
@salvadordf sorry to inform, but this not solved the problem at all. Sometimes the bug continues to occur...

I also found this at chromium repository: https://bitbucket.org/chromiumembedded/cef/issues/1856/branch-2526-cef-activates-browser-window

I think this problem is a "old friend" of CEF....

As ~~ugly~~ workaround I'll use this:

```
// TMyChromiumWindow = class(TChromiumWindow)
procedure TMyChromiumWindow.WndProc(var aMessage: TMessage);
begin
  inherited;
  SetWindowPos(Application.MainForm.Handle, HWND_NOTOPMOST, 0, 0, 0, 0, SWP_NOSIZE or SWP_NOMOVE);
end;
```

**Comment by salvadordf** [comment]
CEF and Chromium have a special way to create the embedded browsers that can create issues as the one you linked.

Delphi also has its own issues with modal forms created behind the visible form but most of them were fixed in the latest Delphi version. 

In fact, the MessageDlg issue you describe here can only be reproduce in Delphi 7. When I tried it in Delphi 10 it worked perfectly which means that it's probably a Delphi 7 issue.

It can be tricky to find a fix when you mix all of these possible focus issues in one application.

If you can't find a workaround for Delphi 7 then you can try 2 other browser configurations :
- Use an "Enternal Pump" as described in the SimpleExternalPumpBrowser demo. Some developers use this to fix some issues with popup menus.
- Use the "Off-screen mode" (OSR mode) found in the SimpleOSRBrowser demo. This mode gives you total control at the cost of browser performance. If you still have focus issues with this demo it means that it's a Delphi 7 issue.

Please, use our forums for more questions : 
https://www.briskbard.com/forum/
