### ISSUE TITLE
AddCustomCommandLine seems not to work with BrowserSubprocessPath

### ISSUE THREAD

**Issue by betonetotbo** [salvadordf/CEF4Delphi#283]
I created a executable only to process the CEF IPC.

In the main application I create `TCEFApplication` pointing to it, like this:

```
  GlobalCEFApp := TCefApplication.Create;

  // disable proxy config from internet options
  GlobalCEFApp.AddCustomCommandLine('--no-proxy-server', '1');
  // https://bitbucket.org/chromiumembedded/cef/issues/1856/branch-2526-cef-activates-browser-window#comment-50492309
  GlobalCEFApp.AddCustomCommandLine('--no-activate');
  GlobalCEFApp.AddCustomCommandLine('--off-screen-rendering-enabled');

  GlobalCEFApp.StartMainProcess;
```
This 3 args isn't set to the subprocess when them launch. Why?

**Comment by salvadordf** [comment]
Some switches are defined in the CEF sample application (cefclient) and some of them are defined in Chromium's code.

You can configure the proxy settings with TChromium.ProxyType, TChromium.ProxyScheme , TChromium.ProxyServer , TChromium.ProxyPort , TChromium.ProxyUsername , TChromium.ProxyPassword , TChromium.ProxyScriptURL , TChromium.ProxyByPassList and TChromium.MaxConnectionsPerProxy
Read this document for more information about those properties : 
https://www.chromium.org/administrators/policy-list-3#Proxy
https://www.briskbard.com/index.php?lang=en&pageid=cef#usage                                          

'--no-activate' and '--off-screen-rendering-enabled' are defined in cefclient's code and we can't use them in CEF4Delphi. You need to use alternative switches or properties that have the same effect.

'--no-activate' adds a WS_EX_NOACTIVATE value to ExStyle when the browser calls CreateWindowEx. If you set TCefWindowInfo.ex_style with WS_EX_NOACTIVATE then you should have the same effect. In the latest master version of CEF4Delphi you can do this by setting the TChromium.DefaultWindowInfoExStyle property directly.

If you want to test the "off-screen mode" then use the code in the SimpleOSRBrowser demo as a template for your application.

The "off-screen mode" or (OSR mode) gives you total control of the focus, events, etc but it's slower than the "normal mode" you see in the SimpleBrowser2 demo, for example.
