### ISSUE TITLE
Browser closed after RecreateWnd called

### ISSUE THREAD

**Issue by jazlee** [salvadordf/CEF4Delphi#29]
When host form position property changed, by default it would call RecreateWnd API, this function makes the browser closed, it is however CreateBrowser does not bring it back.

**Comment by salvadordf** [comment]
RecreateWnd destroys the underlying Windows screen object to recreate it again from scratch. 

Call CreateBrowser after all the form properties are set and avoid any call to RecreateWnd after that.

**Comment by jazlee** [comment]
Already tried to call CreateBrowser all initialization process completed but it doesnt bring the browser back because CreateBrowser check and stop if FClientHandler is not nil. 

https://github.com/salvadordf/CEF4Delphi/blob/master/source/uCEFChromium.pas#L717

**Comment by salvadordf** [comment]
Sorry. I wasn't clear before. 

I meant that you should not call CreateBrowser twice. 
If you need to set some form properties, do it before calling CreateBrowser.

If you call RecreateWnd then you'll have to destroy TChromium too following the steps described in the MDIBrowser demo but it's just much easier setting the form properties before calling CreateBrowser.

Another possibility if you really need to call RecreateWnd is to use TChromium in OSR mode. In that mode you don't need to destroy TChromium and you can call RecreateWnd whenever you want.

**Comment by jazlee** [comment]
got it, thanks
