### ISSUE TITLE
Crash when visiting chrome://version

### ISSUE THREAD

**Issue by DelphiGit** [salvadordf/CEF4Delphi#290]
Hi,

An application crashes if "chrome://version" is the first url being visited.
This can be reproduced with the MiniBrowser demo, by altering line 75 of unit uMiniBrowser to,
MINIBROWSER_HOMEPAGE = 'about:blank';

Run the application
Type chrome://version in the url-combobox
Click the Go-button

If I visit any other url before chrome://version then the version page is displayed correctly.
I don't know if this is a bug in CEF4Delphi, or in the Framework itself.

**Comment by salvadordf** [comment]
This is a CEF issue and it affects all URLs with a "chrome" scheme : 
https://bitbucket.org/chromiumembedded/cef/issues/2967/cefclient-crash-or-incorrect-display

Workarounds : 

- Set TChromium.DefaultURL to 'chrome://version' before the TChromium.CreateBrowser call.

- Load any URL with a chrome scheme after you have loaded another URL, excluding 'about:blank'.

**Comment by DelphiGit** [comment]
I don't think this issue exists any more. I don't know when the bug was fixed, but it works for me.

**Comment by salvadordf** [comment]
You're right! Thanks! :D
