### ISSUE TITLE
SingleProcess=True - Process is not closed

### ISSUE THREAD

**Issue by giovanierthal** [salvadordf/CEF4Delphi#291]
In the SimpleBrowser demo, when I set SingleProcess = True, when closing the application the process continues to run.

**Comment by salvadordf** [comment]
The single process mode is not supported by CEF and it can only be used for debugging purposes.

**Comment by giovanierthal** [comment]
I'm using it for debugging only. It is sometimes tiring. I just thought it could be fixed. Thank you for your attention.

**Comment by salvadordf** [comment]
I found this issue in the CEF project that explains why this issue won't be fixed : 
https://bitbucket.org/chromiumembedded/cef/issues/1993/cef-2785-shutdown-hangs-in-single-process

Fixing this issue would require changes in Chromium's code and the CEF project will not maintain that kind of changes for an unsupported run mode.

The official CEF sample application also has this issue when you enable the single process mode and the multithreaded message loop like this : 
`cefclient.exe --multi-threaded-message-loop --single-process`

I just added some more procedures to disable some events while the application is shutting down but you will still see a hanged process when you close applications in single process mode.

**Comment by zrfisaac** [comment]
> 1993/cef-2785-shutdown-hangs-in-single-process

Thansk for the explanation, I just want to add that this link is borken, at last for me it is,  here is the correct link : https://github.com/chromiumembedded/cef/issues/1993
