### ISSUE TITLE
CEF4Delphi no longer builds with Delphi 2007 and earlier

### ISSUE THREAD

**Issue by davidimagitech** [salvadordf/CEF4Delphi#292]
TCEFJson.LoadFromFile() makes use of TEncoding, which was introduced in Delphi 2009 (I believe) and is not present in non-Unicode versions of Delphi.

Commenting out TCEFJson.LoadFromFile() does enable the package to build, so it is only this method that is preventing CEF4Delphi from building under Delphi 2007.

Cheers.

**Comment by salvadordf** [comment]
Please, download the latest version from this repository : 
https://github.com/salvadordf/CEF4Delphi/archive/master.zip

That issue was fixed recently : 
https://github.com/salvadordf/CEF4Delphi/blob/master/source/uCEFJson.pas#L80
