### ISSUE TITLE
can't send "." use SendKeyEvent

### ISSUE THREAD

**Issue by weechatfly** [salvadordf/CEF4Delphi#293]
Hi,
When I use TChromium.SendKeyEvent to send characters, it can't send ".", but can send other characters. 
my codes:

TempKeyEvent.kind                    := KEYEVENT_RAWKEYDOWN;
        TempKeyEvent.modifiers               := 0;
        TempKeyEvent.windows_key_code        := ord('.');
        TempKeyEvent.native_key_code         := 0;
        TempKeyEvent.is_system_key           := ord(False);
        TempKeyEvent.character               := #0;
        TempKeyEvent.unmodified_character    := #0;
        TempKeyEvent.focus_on_editable_field := ord(False);
        Chromium1.SendKeyEvent(@TempKeyEvent);

        // WM_CHAR
        TempKeyEvent.kind := KEYEVENT_CHAR;
        Chromium1.SendKeyEvent(@TempKeyEvent);

        // WM_KEYUP
        TempKeyEvent.kind := KEYEVENT_KEYUP;
        Chromium1.SendKeyEvent(@TempKeyEvent);

Thanks!

**Comment by salvadordf** [comment]
Hi,

Build the **SimpleOSRBrowser** demo and log all the information used as parameters in the TChromium.SendKeyEvent calls when you press the dot key.

Please, use our forum for more questions : 
https://www.briskbard.com/forum/
