### ISSUE TITLE
CEF4Delphi_FMX and CEF4Delphi  Install

### ISSUE THREAD

**Issue by arthurj58** [salvadordf/CEF4Delphi#294]
CEF4Delphi_FMX and CEF4Delphi  Install at the same time ？
it contains unit 'uCEFjson',  which is also contained in package CEF4Delphi

**Comment by salvadordf** [comment]
The CEF4Delphi.dproj file only contains the VCL components.
CEF4Delphi_FMX.dproj on the other hand contains the VCL and FMX components in one package.

Please use our forum for more questions : 
https://www.briskbard.com/forum/
