### ISSUE TITLE
crash DomVisitor

### ISSUE THREAD

**Issue by flashermedia** [salvadordf/CEF4Delphi#296]
eroor crash..

[https://prntscr.com/tvvgga](url)

**Comment by salvadordf** [comment]
Please provide a step by step guide to reproduce that error and the details about your operating system and Delphi version. 
Remember that Google is now blocking all athentication made directly with an embedded browser. You will need to use OAuth2 and a different web browser to login to their services.

**Comment by flashermedia** [comment]
I just ran your sample demo, then logged in to my Google account ... the error notification continued to appear ...

**Comment by flashermedia** [comment]
how to download on google drive APi

**Comment by flashermedia** [comment]
so that you can access the upload download as in the picture. how [https://prnt.sc/tz21hk](url)

**Comment by salvadordf** [comment]
I couldn't reproduce this issue with the latest CEF4Delphi version.
