### ISSUE TITLE
 how to download on google drive

### ISSUE THREAD

**Issue by flashermedia** [salvadordf/CEF4Delphi#297]
download files on google drive with components CEFUrlRequestClientComponent and CEFServerComponent .. what about progressbar and can be repeated

**Comment by flashermedia** [comment]
help me
[https://github.com/salvadordf/CEF4Delphi](url)

**Comment by flashermedia** [comment]
help me [https://prnt.sc/ty483b](url)

**Comment by salvadordf** [comment]
Please, use the GitHub issues only for bugs and use our forum for questions : 
https://www.briskbard.com/forum/
