### ISSUE TITLE
What happened to DLLs

### ISSUE THREAD

**Issue by mlhkr** [salvadordf/CEF4Delphi#298]
Hi,
I've downloaded latest version but sample application requires a lot of DLLs (says missing).
Last time I use it couple of years ago we were downloading those DLLs but now only I can see is:
cef_binary_83.5.0+gbf03589+chromium-83.0.4103.106_windows64 inside
cef_binary_83.5.0+gbf03589+chromium-83.0.4103.106_windows64.tar

So single file. I try to open it with winrar but again DLLs are missing. How can I achieve those DLLs.

Or new cef_binary files are combined into one single file?

Thanks

**Comment by salvadordf** [comment]
The binaries package has a ".tar.bz2" extension. That means that you have to decompress it first (the ".bz2" part) and then unpack it (the ".tar" part).
Some decompressors will do the 2 steps automatically and you will see the folders and files immediately. 
Other decompressors requiere that you decompress and unpack the file manually by double-clicking the file 2 times.

Please, read this forum thread to know all the "breaking changes" in the recent CEF versions : 
https://www.briskbard.com/forum/viewtopic.php?f=8&t=739
