### ISSUE TITLE
“TChromium.MaxConnectionsPerProxy” has no effect.

### ISSUE THREAD

**Issue by gmxyb** [salvadordf/CEF4Delphi#302]
The default value for TChromium.MaxConnectionsPerProxy is 32.

In my application  ...AddCustomCommandLine('--proxy-server', 'socks5://localhost:1080');

I test load a page has many pictures,  **but cannot create more than 6 connections**.

If setting TChromium.MaxConnectionsPerProxy = 64 (in OnAfterCreated event), **still no effect.**

**Comment by salvadordf** [comment]
Try using the TChromium properties to configure your proxy : 

- TChromium.ProxyType
- TChromium.ProxyScheme
- TChromium.ProxyServer
- TChromium.ProxyPort
- TChromium.ProxyUsername
- TChromium.ProxyPassword
- TChromium.ProxyScriptURL
- TChromium.ProxyByPassList
- TChromium.MaxConnectionsPerProxy

You can set the values just before the TChromium.CreateBrowser call.

Read this forum thread for more information : 
https://www.briskbard.com/forum/viewtopic.php?t=1000

**Comment by gmxyb** [comment]
Thanks.

I configure proxy using TChromium properties as you said.  Unfortunately, same as before.

May be "net.max_connections_per_proxy" options was no longer supported by CEF DLL.

But it's strange, why default value 32 no effect also ?

**Comment by gmxyb** [comment]
I create multiple TChomiums in one process and load same page. 
The process concurrent connections cannot exceed 6 .

**Comment by salvadordf** [comment]
Perhaps there's an issue in Chromium or there's a new requirement to use that preference that CEF is not implementing.
Have you tried other proxy servers ?

**Comment by gmxyb** [comment]
My proxy server no problem. It work fine in Firefox/IE test cases (modified browser related setting).

My proxy server output detailed log, so I can seen the browser connections counts realtime.

**Comment by salvadordf** [comment]
It seems that Chromium doesn't allow setting any value to this preference : 
https://source.chromium.org/chromium/chromium/src/+/master:services/network/network_service.cc;drc=d0506dd8ce985c439d0904b6862fd66dfe48c5b0;l=602
It clamps the new value between a minimum and a maximum limit.
In addition to that, not all browser preferences can be modified and sometimes they are "read-only" and we can't do much about it from CEF4Delphi.
I can't test this issue but I would like to know what other users have experienced before removing this feature.
Closing this issue for now...
