### ISSUE TITLE
TFileStream.Create fails in uCEFMiscFunctions.GetDLLHeaderMachine on concurent access

### ISSUE THREAD

**Issue by mterrisse** [salvadordf/CEF4Delphi#303]
Hello,

(Windows 10, CEF 85.3.11, code updated today 2020-09-30, 048a812b)
In uCEFMiscFunctions.GetDLLHeaderMachine you can read
          TempStream := TFileStream.Create(aDLLFile, fmOpenRead);
This fails if another process has loaded the dll because fmOpenRead is equivalent to fmOpenRead OR fmShareExclusive.
It works fine if you change it to
          TempStream := TFileStream.Create(aDLLFile, fmOpenRead or fmShareDenyWrite);

Regards,

Michel Terrisse

**Comment by salvadordf** [comment]
I added your solution. Thank you very much!
