### ISSUE TITLE
[Vcl] TChromium event handlers in TChromiumWindow not threadsafe

### ISSUE THREAD

**Issue by Vasek-gh** [salvadordf/CEF4Delphi#305]
For example ````WebBrowser_OnAfterCreated```` invoke PostMessage with Handle property. But this property is complex and can create window handle internaly. For most cases when ````WebBrowser_OnAfterCreated```` raised, window handle already created and all work fine. But because ````WebBrowser_OnAfterCreated```` raised in not main thread, some times(for example change parent for TChromiumWindow) he can create window handle not in main thread. This in turn causes errors during the destruction of the window handle in the main thread.

**Comment by salvadordf** [comment]
The source code have several warnings about this. You have to consider that all TChromium and GlobalCEFApp events (among others) are executed in CEF threads that are not the same as the main application thread.

The VCL is not thread safe so you should not create, destroy or modify any VCL control inside those events. The demos try to be as simple as possible and they ignore this but you should move all that code away from CEF events.

Try adding this code before using a handle inside a CEF event : 
`if HandleAllocated then`

Please, use our forums for more questions : 
https://www.briskbard.com/forum/
