### ISSUE TITLE
Crash with CEF3 branch 3112

### ISSUE THREAD

**Issue by Usever** [salvadordf/CEF4Delphi#31]
Please, make CEF4Delphi work with the latest CEF3 branch (3112).

**Comment by salvadordf** [comment]
I'll add support for the latest stable branch as soon as I can.

The CEF3 binaries for the 3071 branch were released in Spotify yesterday.

**Comment by salvadordf** [comment]
I just updated CEF4Delphi to the latest stable CEF3 branch (3071).

The 3112 branch will probably be available on August 1st according to the Chromium development calendar : https://www.chromium.org/developers/calendar

**Comment by Usever** [comment]
Thank you!
