### ISSUE TITLE
SendDevToolsMessage - does it work ?

### ISSUE THREAD

**Issue by stepel** [salvadordf/CEF4Delphi#311]
Hi,

Does SendDevToolsMessage send message like I try to do it by console in developer tools ? 
I would like to execute JS but not by ExecuteJavaScript method. 

I try to do it by SendDevToolsMessage  but there is no result.

**Comment by salvadordf** [comment]
That procedure is intended for a different usage. Read the code comments for TChromium.SendDevToolMessage [here](https://github.com/chromiumembedded/cef/blob/c3aa36323b59f130b18b7ee25a6911bfbef36574/include/capi/cef_browser_capi.h#L489).

The TChromium.ExecuteDevToolsMethod procedure is explained [here](https://github.com/chromiumembedded/cef/blob/c3aa36323b59f130b18b7ee25a6911bfbef36574/include/capi/cef_browser_capi.h#L526).

The events related to the DevTools are these : TChromium.OnDevToolsMessage, TChromium.OnDevToolsMethodResult, TChromium.OnDevToolsEvent, TChromium.OnDevToolsAgentAttached and TChromium.OnDevToolsAgentDetached.
Read [this](https://github.com/chromiumembedded/cef/blob/c3aa36323b59f130b18b7ee25a6911bfbef36574/include/capi/cef_devtools_message_observer_capi.h#L61) for all the details about those events.

If you need to execute javascript with the devtool then these DevTools methods might be what you are looking for : 
https://chromedevtools.github.io/devtools-protocol/tot/Runtime/

You can try those methods with TChromium.ExecuteDevToolsMethod and TChromium.OnDevToolsMethodResult as you can see in the MiniBrowser demo.

Please, use our forum for more questions : 
https://www.briskbard.com/forum/
