### ISSUE TITLE
For keyboards messages, lParam is not the native key code

### ISSUE THREAD

**Issue by mterrisse** [salvadordf/CEF4Delphi#312]
Hello,
In the demos comming with CEF4Delphi you can read many times
      TempKeyEvent.windows_key_code        := Msg.wParam;
      TempKeyEvent.native_key_code         := Msg.lParam;
but this is wrong, lParam is a consolidate set of flags and not the value of the key, see for example
https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-keyup
I could see that in 64 bits because lParam can be greater then High (Integer) and native_key_code is an Integer.
This works fine if I set
      TempKeyEvent.native_key_code         := 0;
instead, I presume this lets CEF compute native_key_code from windows_key_code.

Regards,

Michel Terrisse

**Comment by salvadordf** [comment]
The demos are a rough translation of the official cefclient code in the CEF project. The code that assigns the lParam to native_key_code in cefclient is [here](https://bitbucket.org/chromiumembedded/cef/src/c3aa36323b59f130b18b7ee25a6911bfbef36574/tests/cefclient/browser/osr_window_win.cc#lines-782).

The FMX demos also set native_key_code to 0 and they still work.
https://github.com/salvadordf/CEF4Delphi/blob/b118999a56e270f70727669ea83adac738cedf0b/demos/Delphi_FMX/FMXExternalPumpBrowser/uFMXExternalPumpBrowser.pas#L351

I haven't checked the CEF or Chromium sources but they probably assume that native_key_code is a raw copy of lParam.
