### ISSUE TITLE
TCefCookieManagerRef.New 

### ISSUE THREAD

**Issue by dtamade** [salvadordf/CEF4Delphi#313]
I find TCefCookieManagerRef.New It's been erased,

Is it that the creation of cookiemanager instance is no longer supported after CEF 75?

**Comment by dtamade** [comment]
I have a code based on tcefcookiemanagerref that tchromium is independent of each other's cookie data. After the code is updated, it can't work. Please advise the new method. Thank you

**Comment by dtamade** [comment]
Hi,

CEF removed the possibility to use a different directory for the cookies several months ago.
If you use the latest CEF libraries then you can only set the cache directory. The cookies will be stored in the same directory as the cache.

If you want to create a bunch of independent browsers in one application you can use a very similar code than the one you gave.

You would only have to create a request context with an independent "cache" parameter for each browser.
The MDIBrowser demo has all the code you need :
https://github.com/salvadordf/CEF4Delphi/blob/d444bb29e12ac5bd86be7df70e15caa03eb17e86/demos/Delphi_VCL/MDIBrowser/uChildForm.pas#L217

This forum thread has more detials :
https://www.briskbard.com/forum/viewtopic.php?f=8&t=1122

OK, I have found the above information

https://www.briskbard.com/forum/viewtopic.php?f=10&t=1501&p=6261&hilit=cookie#p6261

**Comment by salvadordf** [comment]
Closing as it seems that you found the solution in our forum.
