### ISSUE TITLE
How to get value using 'document.getElementById("id")'

### ISSUE THREAD

**Issue by shariful2011** [salvadordf/CEF4Delphi#314]
I need to get value from the browser's DOM object by `document.getElementById("id")`. Is there any way to achive this?

**Comment by salvadordf** [comment]
There're several ways to do that and most of them are in the DOMVisitor, JSExtension and JSRTTIExtension demos.

The easiest way would be to execute some JS code to get the value and send it back to the browser using a console log message. This is the "console tick" explained in the DOMVisitor demo.

If you need a more robust solution then register a JS extension as exaplined in the JSExtension or JSRTTIExtension demos.

Read the code in those demos for more details and don't hesitate to use our forum if you have more questions :
https://www.briskbard.com/forum/
