### ISSUE TITLE
OSR type CEF with mathQuill LaTeX

### ISSUE THREAD

**Issue by shariful2011** [salvadordf/CEF4Delphi#316]
I am doing a mathQuill LaTeX with CEF. Getting one strange behiviour with multiple tabs. On the active tab, my data is showing perfectly if I change the tab the LaTeX symbols changes to "?". I am using the same OSR demo code just added the pagecontrol. I put the bufferpanel in tabsheet. If I don't use OSR mode then the mathQuill editing functionality does not work, so I have to use OSR mode. Any idea why the symbols changes to "?"?

**Comment by salvadordf** [comment]
I loaded http://mathquill.com/ in the TabbedBrowser2 and FMXTabbedOSRBrowser demos and typed the same equation as the example.

I created several other tabs and the symbols remained correct even when I selected other tabs.

TabbedBrowser2 uses browsers in normal mode and FMXTabbedOSRBrowser uses browsers in OSR mode.
I use Delphi 10.4.1 on Windows 10 64 bits.

**Comment by salvadordf** [comment]
CEF has an issue loading fonts on Windows 7. Are you using that OS?

**Comment by shariful2011** [comment]
I am using VCL with Windows 10 and Delphi 10.4.1

**Comment by salvadordf** [comment]
Then try the TabbedBrowser2 and FMXTabbedOSRBrowser demos and compare the code with your application. 
Check the console messsages in the DevTools and enable the CEF debug log to see if that log has some errors.
I've never used mathquill and I can only guess what's happening.

**Comment by shariful2011** [comment]
How do I check console messages in the tabbed browser?

**Comment by salvadordf** [comment]
This doesn't seem to be an issue. 

Please, register in our forum and we'll continue this conversation there.
https://www.briskbard.com/forum/
