### ISSUE TITLE
Interact with Selenium WebDriver

### ISSUE THREAD

**Issue by barlone** [salvadordf/CEF4Delphi#317]
Many thank for great job, @salvadordf!

Do you know if it is possible use embedded Chromium Framework with Selenium WebDriver  (https://chromedriver.chromium.org/)?
I try to find answer on https://bitbucket.org/chromiumembedded/cef/src/master/, but unfortunately I did not find

**Comment by salvadordf** [comment]
Thanks! 

I've never tried Selenium WebDriver but according to this wiki page at the CEF project you would only have to set the GlobalCEFApp.RemoteDebuggingPort property in your application : 
https://bitbucket.org/chromiumembedded/cef/wiki/UsingChromeDriver.md

Let me know if it works.
