### ISSUE TITLE
Turn off local fonts with Chrome 86

### ISSUE THREAD

**Issue by PlanetIrata** [salvadordf/CEF4Delphi#318]
Hi, Google Web Fonts are not working with CEF under Windows 7 & 8 due to the way Windows manage local fonts.

From Chrome 86 it seems to be possible to disable local fonts (ref: https://stackoverflow.com/a/64309347).

Since the master branch of CEF4Delphi is now using Chrome 86, is there a way to do this with a global configuration variable like **DisableLocalFonts** ? Or any other way ?

Thanks!

**Comment by salvadordf** [comment]
The _CSS.setLocalFontsEnabled_ DevTools method seems to be what you're looking for : 
https://chromedevtools.github.io/devtools-protocol/tot/CSS/#method-setLocalFontsEnabled

Check the MiniBrowser and DOMVisitor demos for more information about calling DevTools methods.

**Comment by PlanetIrata** [comment]
Tried it this way:

```pascal
      crmPreview.CreateBrowser(crwPreview);
      try
        TempParams := TCefDictionaryValueRef.New;
        TempParams.SetBool('enabled', false);
        crmPreview.ExecuteDevToolsMethod(0, 'CSS.setLocalFontsEnabled', TempParams);
      finally
        TempParams := nil;
      end;
```

When I checked in the `OnDevToolsMethodResult`  event, the `success` parameter is set to `true` (was `false` with Chrome 85, so semmes to work), but the `local(...)` fonts are still used... if I manually remove the `local(...)` parameters returned by fonts.googleapis.com`, it works.
  
Does it means that the `CSS.setLocalFontsEnabled`option only works if the DevTools are opened/attached to the TChromium component ?

**Comment by salvadordf** [comment]
You need to wait until the browser is fully initialized before calling TChromium.ExecuteDevToolsMethod.
In this case, call TChromium.CreateBrowser and wait until the TChromium.OnAfterCreated event is executed. 
Only then you can call TChromium.ExecuteDevToolsMethod.

**Comment by PlanetIrata** [comment]
Did this, `OnDevToolsMethodResult` still returns `success = true`, but under Windows 7 & 8 the Google fonts are still missing . If I manually remove the `local(...)` parameters from the CSS, it works.

**Comment by salvadordf** [comment]
This CEF issue might be the cause of that problem : 
https://bitbucket.org/chromiumembedded/cef/issues/2858/fonts-not-loading-look-wrong-on-windows-7

This workaround might be helpful : 
https://bitbucket.org/chromiumembedded/cef/issues/2858/fonts-not-loading-look-wrong-on-windows-7#comment-56199002
