### ISSUE TITLE
Double clicking on the OSR based browser without any error program crashes.

### ISSUE THREAD

**Issue by shariful2011** [salvadordf/CEF4Delphi#319]
I am using the latest Cef version 86.0.14.0. With your SimpleOSRdemo and my application double clicking on the browser, app crashes without any error messege. Any idea how to overcome? 
Also I tried to create an account on the briskbard forum with 3 of my emails around 6 days ago but unfortunatly yet to recive account activation email.

**Comment by salvadordf** [comment]
I can't reproduce the crash with the SimpleOSRBrowser demo on Windows 10 (64 bits), Delphi 10.4.1 and the latest CEF4Delphi.
Please, provide a step-by-step description of this issue to reproduce it in my computer.

I also activated the user "SharifulAlam" manually. Then I tried to send you an email about the activation but the message was returned.
The forum account should work with the same password you selected. Let me know if you have any problem accessing the forum.

**Comment by shariful2011** [comment]
I am using WIndow 10 (64bit), Delphi 10.4.1 and latest CEF4Delphi 86.0.21.0. I just ran the SimpleOSRDemo and few times double click. You can from the attached gif file in action.
![osr](https://user-images.githubusercontent.com/634779/98445591-a1bcdf80-2142-11eb-8287-11d17282d288.gif)

**Comment by salvadordf** [comment]
I tried double-clicking outside the search box and then inside the search box like you do in the gif but I can't reproduce it.

...however, I see debug messages like this one : 
`Debug Output:
onecore\com\combase\dcomrem\resolver.cxx(2491)\combase.dll!76365101: (caller: 763634BF) ReturnHr(6) tid(d54) 80040154 Class not registered
Process SimpleOSRBrowser.exe (3552)` 

Those messages apear when I move the mouse between the 2 clicks in the double click. The demo thinks it's doing "drag and drop".

Can you do a test to confirm if this is a drag and drop issue? Please delete this call and repeat the test : 
` chrmosr.InitializeDragAndDrop(Panel1)`
https://github.com/salvadordf/CEF4Delphi/blob/4db7d899380271058d5bfc9a3f24b6789e734cf2/demos/Delphi_VCL/SimpleOSRBrowser/uSimpleOSRBrowser.pas#L816

**Comment by shariful2011** [comment]
Sorry, same thing.

**Comment by salvadordf** [comment]
I'm sorry for my ignorance about your language but, are you using some kind of IME or "input method editor" to input text ?
If so, can you disable it for a moment and do the test again?

**Comment by shariful2011** [comment]
No, I am just running the SimpleOSRDemo without changing any code. For my own application, I am using MathQuill. It refers to libcef.dll on the debug stack while the crash occurs.

**Comment by salvadordf** [comment]
Sorry for the delay.
I see that the browser is not showing you the search suggestions and that could be a clue. Perhaps this is a problem inside libcef.dll.
In my case, I see a box with some suggestions as soon as I click on the search box.
Please, try the official CEF sample application and repeat the double click test.
The official CEF sample application is available here : 
https://cef-builds.spotifycdn.com/cef_binary_86.0.21%2Bg6a2c8e7%2Bchromium-86.0.4240.183_windows64_client.tar.bz2

**Comment by shariful2011** [comment]
With official CEF sample, the error doesn't occur.

**Comment by salvadordf** [comment]
I'm running out of ideas to solve this problem.

Please, run the demo inside the Delphi IDE, do the double click test and post the Delphi call stack. 

Then try using WinDbg with the instructions in this post to get the call stack in libcef before the crash.
https://www.briskbard.com/forum/viewtopic.php?f=10&t=1050

**Comment by salvadordf** [comment]
Are you using the CEF binaries found in the "_Release_" directory or in the "_Debug_" directory?

**Comment by shariful2011** [comment]
I am using debug.

**Comment by salvadordf** [comment]
I was editing my previous comment while you replied.
I saw that you mentioned before that you were using the "_Debug_" binaries and that's the cause of this problem.
Those binaries have a lot of extra checks that cause issues like this one.
Use the CEF binaries from the "_Release_" directory to avoid this problem.
