### ISSUE TITLE
How to use TCefRequestContextRef.ResolveHost? Thanks!

### ISSUE THREAD

**Issue by qq18436558** [salvadordf/CEF4Delphi#32]
How to use TCefRequestContextRef.ResolveHost? 
I want to dynamically modify www.***.com to 111.111.111.111
Thanks!

**Comment by salvadordf** [comment]
I've never used TCefRequestContextRef but I guess you should do this : 
1. Create a new class inherited from TCefResolveCallbackOwn and define OnResolveCompleted.
2. Call TCefRequestContextRef.ResolveHost with the origin parameter (domain) and an instance of the class created in point 1.
3. The IP addresses will be in the resolvedIps paramenter of OnResolveCompleted.

It's much easier to use the Indy components to resolve addresses. Use TIdDNSResolver.Resolve(domain) and then read the QueryResult property.

**Comment by qq18436558** [comment]
Thank you. I'll try it.
