### ISSUE TITLE
Capture Full Size Screenshot

### ISSUE THREAD

**Issue by shariful2011** [salvadordf/CEF4Delphi#320]
Is there any way I can capture a full-size screenshot as Chrome does? On the MiniBrowser demo, there is a Popup menu item "Take screenshot" which has code 
`
procedure TMiniBrowserFrm.akescreenshot1Click(Sender: TObject);
begin
  inc(FDevToolsMsgID);
  FScreenshotMsgID := FDevToolsMsgID;
  Chromium1.ExecuteDevToolsMethod(FScreenshotMsgID, 'Page.captureScreenshot', nil);
end;
`
but on the exe that popup menu item is not showing. Take snapshot is available not Take screenshot.

![image](https://user-images.githubusercontent.com/634779/99395550-cd8e5100-290a-11eb-9793-9b70b4a6ac7b.png)

**Comment by salvadordf** [comment]
There are 2 functions to capture the screen in the MiniBrowser demo :

- The "_Take snapshot..._" option in the context menu uses the old function which needs a browser with hardware acceleration disabled to work.
- The "_Take screenshot_" option available when you click on the upper-right button with the 3 lines. It uses the new DevTools method and it always works.

**Comment by shariful2011** [comment]
How to use full size screenshot like the demo has 'Page.captureScreenshot'?

**Comment by salvadordf** [comment]
All the code you need is in the MiniBrowser demo.

Call TChromium.ExecuteDevToolsMethod with that method like this : 
https://github.com/salvadordf/CEF4Delphi/blob/db361ed6d8ba155be78584cd5e3ece71cebae733/demos/Delphi_VCL/MiniBrowser/uMiniBrowser.pas#L1117

Then receive the image data in the TChromium.OnDevToolsMethodResult event : 
https://github.com/salvadordf/CEF4Delphi/blob/db361ed6d8ba155be78584cd5e3ece71cebae733/demos/Delphi_VCL/MiniBrowser/uMiniBrowser.pas#L1120

And save the image like this : 
https://github.com/salvadordf/CEF4Delphi/blob/db361ed6d8ba155be78584cd5e3ece71cebae733/demos/Delphi_VCL/MiniBrowser/uMiniBrowser.pas#L1173

**Comment by shariful2011** [comment]
It only captures the viewable area, not the whole page. I tried with the MiniBrowser demo code but didn't work.

**Comment by salvadordf** [comment]
The methods to capture the screen described here can only capture the visible browser contents.
As far as I know, CEF doesn't have any API method to capture the whole web page.
Try taking several screenshots while the page is scrolling and then putting all of them in one big image.
