### ISSUE TITLE
App Crash on Windows 7

### ISSUE THREAD

**Issue by calixtojb** [salvadordf/CEF4Delphi#321]
Hi,

I am using the last stable cef version: CEF4Delphi-85.0.4183.121.
This error ocorrurs when i close the application only on windows 7 64 bits:

-----------------
Assinatura do problema:
  Nome do Evento de Problema:	APPCRASH
  Nome do Aplicativo:	MetricsPrintWare.exe
  Versão do Aplicativo:	0.0.0.0
  Carimbo de Data/Hora do Aplicativo:	2a425e19
  Nome do Módulo de Falhas:	libcef.dll
  Versão do Módulo de Falhas:	85.3.12.0
  Carimbo de Data/Hora do Módulo de Falhas:	5f654c60
  Código de Exceção:	c0000005
  Deslocamento de Exceção:	01f02853
  Versão do sistema operacional:	6.1.7600.2.0.0.256.1
  Identificação da Localidade:	1046
  Informações Adicionais 1:	0a9e
  Informações Adicionais 2:	0a9e372d3b4ad19135b953a78882e789
  Informações Adicionais 3:	0a9e
  Informações Adicionais 4:	0a9e372d3b4ad19135b953a78882e789

Leia nossa declaração de privacidade online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0416

Se a declaração de privacidade online não estiver disponível, leia nossa declaração de privacidade offline:
  C:\Windows\system32\pt-BR\erofflps.txt

----------------------------
Sorry the message above is in pt-BR
----------------------------

It´s not necessarily a issue, but i managed to solve it change the order of FreeLibcefLibrary is executed, i changed it by exec before the shudown:

destructor TCefApplicationCore.Destroy;
begin
  if (GlobalCEFApp = Self) then
    GlobalCEFApp := nil;

  try
    FreeLibcefLibrary; --Add this line

    if (FProcessType = ptBrowser) then
      ShutDown;

    FreeLibcefLibrary; --Remove this line

    if (FCustomCommandLines      <> nil) then FreeAndNil(FCustomCommandLines);
    if (FCustomCommandLineValues <> nil) then FreeAndNil(FCustomCommandLineValues);
    if (FSupportedSchemes        <> nil) then FreeAndNil(FSupportedSchemes);
  finally
    inherited Destroy;
  end;
end;

I am not sure why this solved, but i am share for your knowledge.

Tks,

**Comment by salvadordf** [comment]
Hi,

I can't reproduce this issue with the demos of CEF4Delphi-85.0.4183.121 on Windows 7 (64 bits)

This is usually caused by an incomplete implementation of the destruction steps described in the code comments of the demo you used as a template for your application.

Please, test the demos on your computer to see if you can reproduce this issue.
