### ISSUE TITLE
Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by shariful2011** [salvadordf/CEF4Delphi#322]
I tried to use html2canvas to capture full page screenshot but got the said error. Please help me. I added below
`
  GlobalCEFApp.SitePerProcess := False;
  GlobalCEFApp.AddCustomCommandLine('--disable-websecurity')
`
but got the error.

**Comment by salvadordf** [comment]
I'm not a JavaScript expert but this seems to be related to that issue : 
https://stackoverflow.com/questions/46984372/todataurl-on-htmlcanvaselement-tainted-canvases-may-not-be-exported

The  `--disable-websecurity` switch is not in the official list of command line switches : 
https://peter.sh/experiments/chromium-command-line-switches/

Try using `GlobalCEFApp.DisableWebSecurity := True;` or `GlobalCEFApp.AddCustomCommandLine('--disable-web-security');`
