### ISSUE TITLE
Spell checker not working

### ISSUE THREAD

**Issue by salvadordf** [salvadordf/CEF4Delphi#324]
The spell checker in the latest CEF4Delphi version doesn't work. 

This issue has been reported to the CEF project : 
https://github.com/chromiumembedded/cef/issues/3055

_Workaround_ : Keep using the version in last CEF4Delphi release.
https://github.com/salvadordf/CEF4Delphi/releases/latest

**Comment by salvadordf** [comment]
Another workaround : Adding this code line before the GlobalCEFApp.StartMainProcess call in the DPR file 
`GlobalCEFApp.DisableFeatures := 'WinUseBrowserSpellChecker';`

**Comment by willisnou** [comment]
Hi.
I added the line `GlobalCEFApp.DisableFeatures := 'WinUseBrowserSpellChecker';` in my code but the spell checker continues working (failing in this case). EN seems work, but PT-BR don't. Do we have another workaround to disable spell checker?

I using as html editor.
![image](https://github.com/salvadordf/CEF4Delphi/assets/42159242/e06b090f-8c54-455e-882a-3047e551bbc4)

**Comment by salvadordf** [comment]
Try using the TChromium.SpellChecking and TChromium.SpellCheckerDicts properties [like this](https://www.briskbard.com/forum/viewtopic.php?f=8&t=509).

**Comment by willisnou** [comment]
Works really fine, thanks. But in my tests it must be setted before TChromium created event (i.e OnFormCreate), if it be set on BrowserCreatedMsg, seems not works.

**Comment by salvadordf** [comment]
Fixed upstream
