### ISSUE TITLE
Hide subprocess

### ISSUE THREAD

**Issue by ange007** [salvadordf/CEF4Delphi#325]
Hi.
I create application from FMXTabbedOSRBrowser, but my program show all subprocess on taskbar.

![image](https://user-images.githubusercontent.com/2736539/100551819-e2180500-328b-11eb-8ca2-24701a3efee7.png)

![image](https://user-images.githubusercontent.com/2736539/100551822-ec3a0380-328b-11eb-9b0d-4e7db5a7614e.png)

![image](https://user-images.githubusercontent.com/2736539/100551832-f4923e80-328b-11eb-8cef-20e30dd4eaa5.png)

![image](https://user-images.githubusercontent.com/2736539/100551840-0247c400-328c-11eb-8281-8f6ff79a4441.png)

What could i have done wrong and how to fix it?
Unfortunately, for some reason, I cannot write on the forum now, although I did it earlier.
Thanks.

**Comment by vekunz** [comment]
In the subprocess, you must not call any Application.* procedures, but only GlobalCEFApp.StartMainProcess or GlobalCEFApp.StartSubProcess.

**Comment by salvadordf** [comment]
If your application initializes CEF after the Application.Run call then you have to use a different EXE for the subprocesses or you will have the problem that you describe.

Take a look at the **SubProcess** demo, copy the SubProcess.dpr file and set 
`GlobalCEFApp.BrowserSubprocessPath := 'SubProcess.exe';`

Please, use our forum for more questions related to this.
https://www.briskbard.com/forum/

**Comment by ange007** [comment]
But I don't use subprocesses, I took FMXTabbedOSRBrowser as a basis and added functionality.
Examples of application initialization are shown above in the screenshots.

**Comment by salvadordf** [comment]
Then you need to initialize CEF as you can see in that demo : 
https://github.com/salvadordf/CEF4Delphi/blob/80b1140db6c2db7c75b1b0043c852890eb94f33c/demos/Delphi_FMX/FMXTabbedOSRBrowser/FMXTabbedOSRBrowser.dpr#L60

**Comment by ange007** [comment]
> Then you need to initialize CEF as you can see in that demo :
> https://github.com/salvadordf/CEF4Delphi/blob/80b1140db6c2db7c75b1b0043c852890eb94f33c/demos/Delphi_FMX/FMXTabbedOSRBrowser/FMXTabbedOSRBrowser.dpr#L60

Sorry, can you see my screenshots?
I have implemented `CreateGlobalCEFApp;` in module TChromiumUtils, and call on `dpr` file.

```pascal
class function TChromiumUtils.CreateGlobalChromiumApp(const path: string): Boolean;
begin
  Result := True;

  {}
  if Assigned(GlobalCEFApp) then Exit;

  {}
  GlobalFMXWorkScheduler := TFMXWorkScheduler.Create(nil);

  {}
  GlobalCEFApp := TCefApplication.Create;
  GlobalCEFApp.Locale := 'ru';
  GlobalCEFApp.DeleteCache := True;
  GlobalCEFApp.DeleteCookies := True;

  {}
  GlobalCEFApp.ShowMessageDlg := False;
  GlobalCEFApp.EnableHighDPISupport := True;
  GlobalCEFApp.EnableGPU := True;
  GlobalCEFApp.WindowlessRenderingEnabled := True;
  GlobalCEFApp.FlashEnabled := False;
  GlobalCEFApp.ExternalMessagePump := True;
  GlobalCEFApp.SingleProcess := False;
  GlobalCEFApp.MultiThreadedMessageLoop := False;
  GlobalCEFApp.DisableReadingFromCanvas := True; // unique fingerprint

  GlobalCEFApp.OnScheduleMessagePumpWork := OnScheduleMessagePumpWork;
  // GlobalCEFApp.OnContextInitialized := GlobalGlobalChromiumAppInitialized;

  GlobalCEFApp.Cache := path + 'chromiumlib\cache';
  GlobalCEFApp.FrameworkDirPath := path + 'chromiumlib\';
  GlobalCEFApp.ResourcesDirPath := path + 'chromiumlib\';
  GlobalCEFApp.LocalesDirPath := path + 'chromiumlib\locales\';

  {}
  Result := GlobalCEFApp.StartMainProcess;
end;
```

```pascal
loadState := TChromiumUtils.CreateGlobalChromiumApp(_mainPath);

if loadState then
  begin
    GlobalCEFApp.OnContextInitialized := GlobalCEFApp_OnContextInitialized;

    //
    Application.Initialize;
    Application.CreateForm(TSplashF, SplashF);
    Application.Run;

    // The form needs to be destroyed *BEFORE* stopping the scheduler.
    MainF.Free;

    //
    GlobalFMXWorkScheduler.StopScheduler;
  end;
```

**Comment by salvadordf** [comment]
There seems to be something else in the DPR file initializing the application before the TChromiumUtils.CreateGlobalChromiumApp call. 

Perhaps some unit in the "uses" section is the culprit.

Please, move this conversation to our forum. GitHub is only for CEF4Delphi issues.
https://www.briskbard.com/forum/
