### ISSUE TITLE
Best approach for a server-side HTML to image/pdf converter ?

### ISSUE THREAD

**Issue by EricGrange** [salvadordf/CEF4Delphi#329]
Hi,

I am experimenting with using CEF4Delphi server-side to convert HTML to an image or PDF, as a replacement for outdated webkit-based tools like phantomjs or wkhtmltopdf.

What would the simplest / safest way be ? an OSR mode browser or a normal mode one ?
The difference with the demos being there would never be a visible TForm, and it would operate in command line mode.

Just looking for pointers in the right direction in case one option is known dead-end...

**Comment by salvadordf** [comment]
Hi,

I've never tried to use CEF4Delphi in a server but you would need to use a browser in OSR mode.
If you need to use it in command line mode then you will have to use a different EXE for the subprocesses too.
It would be tricky to lock the thread while the the browser navigates to the web page, take the screenshot, close the browser and then unlock the thread to return the screenshot.

Please, use our forum to continue this conversation :
https://www.briskbard.com/forum/
