### ISSUE TITLE
Compiler crash (F2084 Internal Error) caused by enabling Range checking compiler option

### ISSUE THREAD

**Issue by nevcook** [salvadordf/CEF4Delphi#333]
We are early in the process of trying to integrate CEF4Delphi into one of our Delphi 2007 projects.
Thank you for the demo projects, which have been priceless during the learning process.

We have found that if we have the "Range checking" compiler option enabled, the Delphi compiler crashes with the following error "[DCC Error] uCEFOLEDragAndDrop.pas(223): F2084 Internal Error: C1264" on line 223 of uCEFOLEDragAndDrop.pas.

Unfortunately we are still too new to the code base to be able to isolate the cause.

The simplest duplication of the problem we were able to come up with was to open the SimpleBrowser_D7 demo project, to modify the project's compiler options, enabling the "range checking" option, and then re-compiling.

This causes the error when using Delphi 2007. We are unable to test this using other versions of the Delphi compiler at this time, but as you still support D7, I suspect at least that version (and maybe also others) is likely to have the same issue.

**Comment by salvadordf** [comment]
Thanks for reporting this issue!
I just added a quick workaround to some PAS units to disable range checking with Delphi 2007 or older. 
Please, download CEF4Delphi again and let me know if this fixes this problem.
