### ISSUE TITLE
Unsupported CEF version

### ISSUE THREAD

**Issue by razielucas** [salvadordf/CEF4Delphi#336]
Hi.

I've download the CEF4 and the dll from the link on the readme.
But when I try to use, the message above is presented.

![image](https://user-images.githubusercontent.com/6809207/105989533-0754a400-6080-11eb-963d-3c0c8a11ba3b.png)

Any ideas about it?
Thank you.

**Comment by salvadordf** [comment]
It's necessary to uninstall CEF4Delphi and install it again. 
Read this step-by-step guide for all the details :
https://www.briskbard.com/forum/viewtopic.php?f=8&t=772#p3481

**Comment by razielucas** [comment]
Hi... I've tried it, downloaded the master branch of GitHub and used this link https://cef-builds.spotifycdn.com/cef_binary_88.1.6%2Bg4fe33a1%2Bchromium-88.0.4324.96_windows64.tar.bz2

But when the app tried to start it pop's the message.

![image](https://user-images.githubusercontent.com/6809207/105999360-599bc200-608c-11eb-8437-54570d6403c1.png)

So the steps are correct.

Any other ideas?

![image](https://user-images.githubusercontent.com/6809207/105999455-7a641780-608c-11eb-8907-64a32be57a73.png)

**Comment by salvadordf** [comment]
If the app is expecting an older version of the CEF binaries and you installed the latest CEF4Delphi version it means that Delphi is using an old BPL or DCU file insteand of compiling a new one.

You need to locate and delete the old BPL and DCU files created when you installed CEF4Delphi and you built your application.

The BPL files are located here :
C:\Users\Public\Documents\Embarcadero\Studio\<Delphi_version>\BPL

CEF4Delphi also creates DCU files here : 
<path_to_cef4delphi>\packages\Win32
<path_to_cef4delphi>\packages\Win64

The DCU files are usually stored inside the directory of your application : 
<path_to_your_app>\Win32
<path_to_your_app>\Win64
