### ISSUE TITLE
Linux64 - Cannot print a page

### ISSUE THREAD

**Issue by klunch** [salvadordf/CEF4Delphi#337]
I added a button "print" implemented as "Cromium1.Browser.Host.Print" to the demo SimpleBrowser2.
Despite the installed virtual PDF printer, during the printing I get an error message about opposite
![screenshot](https://user-images.githubusercontent.com/78145799/106127549-b45a1a00-616f-11eb-9bdc-668631d47648.png)

CEF Version:      88.1.6+g4fe33a1+chromium-88.0.4324.96
Source code is also attached
[simplebrowser.tar.gz](https://github.com/salvadordf/CEF4Delphi/files/5886566/simplebrowser.tar.gz)

**Comment by salvadordf** [comment]
Printing with CEF in Linux requires using the Printer Handler events in GlobalCEFApp and I still haven't had time to translate that code from the official CEF demo.
https://github.com/salvadordf/CEF4Delphi/blob/8d5797b01fa9ff752dcfff333fde2ffdb8d249da/demos/Lazarus_Linux/MiniBrowser/uMiniBrowser.pas#L377

That feature is in my "to do" list but I don't know when I'll be able to implement it.

**Comment by salvadordf** [comment]
This is the print handler code in cefclient, the official CEF demo : 
https://bitbucket.org/chromiumembedded/cef/src/master/tests/cefclient/browser/print_handler_gtk.cc

**Comment by klunch** [comment]
Great international thanks from cold Russia to warm Spain, Salvador! Eugene and Vova(not Putin), head developer Nich.

**Comment by klunch** [comment]
I tryed to translate code, but I cannot do this. Sorry, I really wanted to help CEF4Delphi.

**Comment by salvadordf** [comment]
Thanks anyway for the effort! :)

I'm still busy with several other issues in Linux but I realize that this is also important.

**Comment by salvadordf** [comment]
The latest MiniBrowser version has the first steps implementing this feature but it's incomplete. I'll keep fixing it in the coming days.

**Comment by salvadordf** [comment]
Please, download CEF4Delphi again and try the MiniBrowser demo for Lazarus.
I used the Lazarus CUPS printer instead of the GTK2 API.
