### ISSUE TITLE
Add link to the repository on your web site

### ISSUE THREAD

**Issue by petko** [salvadordf/CEF4Delphi#34]
Hi, I am just playing with your implementation of CEF for Delphi. I've found it through the page on your web site (https://www.briskbard.com/index.php?lang=en&pageid=cef), but I don't see a link to this repository there. It would be useful to link it directly to this repository, so it will be easier to go here without googling.

**Comment by salvadordf** [comment]
There're two links from 
https://www.briskbard.com/index.php?lang=en&pageid=cef
to this GitHub repository in the "CEF4Delphi" words but I'll add a "links" section.

Thanks!

**Comment by salvadordf** [comment]
Links section added in https://www.briskbard.com/index.php?lang=en&pageid=cef
