### ISSUE TITLE
uCEFApplicationCore fails to compile

### ISSUE THREAD

**Issue by EricGrange** [salvadordf/CEF4Delphi#342]
The procedure TCefApplicationCore.InitLibLocationFromArgs does not seem to have been fully converted from C++, however it does not seem to be used just yet either (and can be commented out as whole)

```
[dcc32 Error] uCEFApplicationCore.pas(885): E2003 Undeclared identifier: 'argc'
[dcc32 Error] uCEFApplicationCore.pas(887): E2003 Undeclared identifier: 'argv'
```

**Comment by salvadordf** [comment]
I just uploaded the fix for this. Please, download CEF4Delphi again.
