### ISSUE TITLE
How to get html source code after all elements rendered?

### ISSUE THREAD

**Issue by wodsoe** [salvadordf/CEF4Delphi#351]
Hi,
How to get html source code after all elements rendered?

**Comment by salvadordf** [comment]
Hi,

Use TChromium.OnLoadingStateChange and check the "isLoading" parameter to know when the page has finished loading and then call TChromium.RetrieveHTML. After that use the TChromium.OnTextResultAvailable event to get the HTML text.

See the MiniBrowser demo for all the details.

Please, use our forum for more questions : 
https://www.briskbard.com/forum/
