### ISSUE TITLE
old cef version support?

### ISSUE THREAD

**Issue by loveacat** [salvadordf/CEF4Delphi#354]
is there an old cefdelphi x64 version support  cef 63.0.3 x64? my program have to embed into a platform, they use cefsharp 63.0.3 
https://github.com/cefsharp/CefSharp/releases/tag/v63.0.3. so my program have to use the same version . i have searched the  forum , and your oldest tag is 68.0.3. what should i do ?

**Comment by salvadordf** [comment]
That version of CefSharp used Chromium 63.0.3239.132 and the equivalent CEF4Delphi version would be this one : 
https://github.com/salvadordf/CEF4Delphi/tree/fed1c04a3f01e867961508c99a1b4480054b19cd

That version is extremely old and unsupported. Please, consider upgrading your application to the latest CEF version.

For more questions, please use our forums at : 
https://www.briskbard.com/forum/
