### ISSUE TITLE
LastErrorMessage property for TCefApplicationCore

### ISSUE THREAD

**Issue by EricGrange** [salvadordf/CEF4Delphi#356]
With the current version, when an error occurs during execution such as in TCefApplicationCore.CheckCEFResources, there is a nice error message string that is displayed with ShowErrorMessageDlg

However when the code is executed in a command-line environment or without a display, that error message is lost, leaving just the Status to report about the actual error.

It would be convenient if the error message, instead of being placed in a TempString local variable, would be made available in a LastErrorMessage string property, this way the calling code can check the status and in case of error, log the error message, report in on the command-line or through other means.

**Comment by salvadordf** [comment]
This feature was added in the latest commit. 

Thanks!
