### ISSUE TITLE
Some already defined constants in C++Builder

### ISSUE THREAD

**Issue by petko** [salvadordf/CEF4Delphi#36]
I have a slight problem with three constants that are already defined in C++Builder (in winnt.h and winuser.h respectively):
```c++
IMAGE_FILE_LARGE_ADDRESS_AWARE
USER_TIMER_MINIMUM
USER_TIMER_MAXIMUM
```

I can easily comment them out, but it is a repetitive work to do after each update of CEF4Delphi, so I was wondering is there a way to fix this?

**Comment by salvadordf** [comment]
USER_TIMER_MINIMUM and USER_TIMER_MAXIMUM have been renamed.
IMAGE_FILE_LARGE_ADDRESS_AWARE was added to uCefApplication for simplicity. I just removed it so all DPRs need to add Windows to the uses section.
