### ISSUE TITLE
Exceptions while using an own scheme handler and closing browser

### ISSUE THREAD

**Issue by TetrisSQC** [salvadordf/CEF4Delphi#361]
Hi,

I'm aware that this is most likely not an issue of your work. I want to achieve a CE-HTML browser. To do so I have an own ResourceHandler for downloads and local files. I load the HbbTV/CE-HTML apps with this handler and inject some javascript to simulate the proper behavior. Unluckily the local webm file is not loaded like it should. When I put it on a web server it is handled properly. I assume the seek implementation is corrupt. The most annoying thing are the random exceptions inside libcef and somehow closing the class takes up to 10 minutes.

**Comment by TetrisSQC** [comment]
I'm not sure but it does not crash if I run the application as SingleProcess. Do I have to secure my TCefResourceHandlerOwn somehow?

`type
  TCustomResourceHandler = class(TCefResourceHandlerOwn)
  protected
    FResponseHeader: TStringlist;
    FResponseContent: TMemoryStream;
    FResponseCode: Integer;
    FResponseText: String;

    function open(const request: ICefRequest; var handle_request: boolean;
      const callback: ICefCallback): boolean; override;
    procedure GetResponseHeaders(const response: ICefResponse;
      out responseLength: int64; out redirectUrl: ustring); override;
    procedure Cancel(); override;
    function skip(bytes_to_skip: int64; var bytes_skipped: int64;
      const callback: ICefResourceSkipCallback): boolean; override;
    function read(const data_out: Pointer; bytes_to_read: Integer;
      var bytes_read: Integer; const callback: ICefResourceReadCallback)
      : boolean; override;
  public
    constructor Create(const browser: ICefBrowser; const frame: ICefFrame;
      const schemeName: ustring; const request: ICefRequest); override;
    destructor Destroy; override;
  end;

  TCustomSchemeHandler = class(TCustomResourceHandler)
  protected
    function open(const request: ICefRequest; var handle_request: boolean;
      const callback: ICefCallback): boolean; override;
  end;

  { TCustomResourceHandler }
constructor TCustomResourceHandler.Create(const browser: ICefBrowser;
  const frame: ICefFrame; const schemeName: ustring;
  const request: ICefRequest);
begin
  inherited Create(browser, frame, schemeName, request);

  FResponseHeader := TStringlist.Create;
  FResponseContent := TMemoryStream.Create;
end;

destructor TCustomResourceHandler.Destroy;
begin
  FResponseHeader.Free;
  FResponseContent.Free;
  inherited;
end;

function TCustomResourceHandler.open(const request: ICefRequest;
  var handle_request: boolean; const callback: ICefCallback): boolean;
var
  http: THTTPClient;
  response: IHTTPResponse;

  headStart, headEnd, i: Integer;
  Head: string;
  str: String;
  Stream: TStringStream;
  url: string;

  procedure AddJs(const AHead, AJS: String; var str: string);
  var
    inject: string;
  begin
    inject := AHead + sLineBreak +
      '<script id="hbbtvpolyfill" type="text/javascript" ' + 'src="' +
      ClientSchemeUri + AJS + '"></script>' + sLineBreak;

    str := StringReplace(str, AHead, inject, [rfReplaceAll]);
  end;

begin
  url := request.getUrl;
  http := THTTPClient.Create;
  try
    http.HandleRedirects := true;
    http.UserAgent := HbbTVAgent;
    response := http.Get(request.url);
    for i := 0 to high(response.Headers) do
      FResponseHeader.Values[response.Headers[i].Name] :=
        response.Headers[i].Value;

    FResponseHeader.Values['Access-Control-Allow-Origin'] := '*';
    FResponseCode := response.StatusCode;
    FResponseText := response.StatusText;
    str := response.ContentAsString(TEncoding.UTF8);
    headStart := pos('<head', str);
    headEnd := headStart + 5;
    while headEnd < length(str) do
    begin
      if str[headEnd] = '>' then
        break;
      inc(headEnd);
    end;
    Head := Copy(str, headStart, headEnd - headStart + 1);

    AddJs(Head, 'js/xmlhttprequest_quirks.js', str);
    AddJs(Head, 'js/xhook.js', str);
    AddJs(Head, 'js/ajaxhook.js', str);
    AddJs(Head, 'js/hbbtv_polyfill.js', str);
    AddJs(Head, 'js/video_quirks.js', str);
    AddJs(Head, 'js/focus.js', str);

    str := StringReplace(str, '</body>',
      sLineBreak + '<script type="text/javascript" src="' + ClientSchemeUri +
      'js/beforeend.js"></script></body>', []);
    str := StringReplace(str, '</body>',
      sLineBreak +
      '<div id="_video_color_overlay_" style="visibility:hidden;position: absolute; background-color: rgb(254, 46, 154); z-index: 999;"></div></body>',
      []);

    Stream := TStringStream.Create(str, TEncoding.UTF8);
    Stream.SaveToStream(FResponseContent);
    Stream.Free;
  finally
    http.Free;
  end;

  FResponseContent.Position := 0;

  if (callback <> nil) then
    callback.Cont;

  Result := true;
end;

procedure TCustomResourceHandler.Cancel();
begin
  inherited;
end;

procedure TCustomResourceHandler.GetResponseHeaders(const response
  : ICefResponse; out responseLength: int64; out redirectUrl: ustring);
begin
  if (response <> nil) then
  begin
    response.Status := FResponseCode;
    response.StatusText := FResponseText;
    response.MimeType := FResponseHeader.Values['Content-Type'];
    if IsHbbTV(response.MimeType) then
      response.MimeType := 'application/xhtml+xml';
    response.SetHeaderByName('Cache-Control', 'no-store', true);
  end;

  responseLength := FResponseContent.Size
end;

function TCustomResourceHandler.read(const data_out: Pointer;
  bytes_to_read: Integer; var bytes_read: Integer;
  const callback: ICefResourceReadCallback): boolean;
begin
  if (data_out <> nil) and (FResponseContent.Size > 0) then
  begin
    bytes_read := FResponseContent.read(data_out^, bytes_to_read);
    Result := bytes_read > 0;
  end
  else
  begin
    bytes_read := 0;
    Result := False;
  end;
end;

function TCustomResourceHandler.skip(bytes_to_skip: int64;
  var bytes_skipped: int64; const callback: ICefResourceSkipCallback): boolean;
begin
  bytes_to_skip := min(bytes_to_skip, FResponseContent.Size -
    FResponseContent.Position);

  FResponseContent.Position := FResponseContent.Position + bytes_to_skip;
  bytes_skipped := bytes_to_skip;
  Result := true;
  if assigned(callback) then
   callback.Cont(bytes_skipped);
end;

{ TCustomSchemeHandler }
function TCustomSchemeHandler.open(const request: ICefRequest;
  var handle_request: boolean; const callback: ICefCallback): boolean;
var
  filename, url: string;
begin
  url := request.getUrl;

  filename := request.getUrl;
  Delete(filename, 1, pos('://', filename) + 2);
  if FileExists(filename) then
  begin
    FResponseHeader.Values['Content-Type'] := DetectMimeType(filename);
    FResponseCode := 200;
    FResponseContent.LoadFromFile(filename);
    FResponseContent.Position := 0;
    FResponseText := 'OK';
  end
  else
  begin
    FResponseCode := 404;
    FResponseText := 'Not Found';
  end;

  FResponseContent.Position := 0;

  if (callback <> nil) then
    callback.Cont;

  Result := true;
end;
`

**Comment by salvadordf** [comment]
The single process mode is not supported by CEF and it's known to cause shutdown issues : 
https://github.com/salvadordf/CEF4Delphi/issues/291

**Comment by TetrisSQC** [comment]
The problem is not the single process mode which does not triggers the exceptions. It seem to be that my TCustomSchemeHandler is not only called in the UI thread. Do you have an idea how to deal with CefCurrentlyOn(TID_UI) in this case?

**Comment by salvadordf** [comment]
Sorry for the delay.

CEF has some issues with some of the CefResourceHandler methods like read and skip:
https://magpcss.org/ceforum/viewtopic.php?f=6&t=17253#p44056

The SchemeRegistrationBrowser and CustomResourceBrowser demos use ProcessRequest, ReadResponse and GetResponseHeaders to avoid those issues.

Use the code in those demos as a template for your application.
