### ISSUE TITLE
Error: Identifier not found "PGdkEventKey"

### ISSUE THREAD

**Issue by TB1234** [salvadordf/CEF4Delphi#362]
I tried to install CEF4Delphi on my Lazarus installation and failed.

Lazarus: 2.0.12
FPC: 3.2.0 and 3.2.2-RC1

I was following [this](https://www.briskbard.com/index.php?lang=en&pageid=cef#installation) instruction and downloaded the latest release and also made a github clone (both versions with same result). Then I started Lazarus, opened the .lpk file and tried to compile. It stopped with the following messages:

```
uCEFLinuxFunctions.pas(61,46) Error: Identifier not found "PGdkEventKey"
uCEFLinuxFunctions.pas(64,43) Error: Identifier not found "PGdkEventKey"
```

Did I missed something? Of course "DCPcrypt" is installed.

**Comment by salvadordf** [comment]
CEF4Delphi had a lot of Linux and MacOS changes in the last months.

Try uninstalling CEF4Delphi, rebuild Lazarus and let it restart the IDE. 
Then delete the old CEF4Delphi directory, decompress the new version and install CEF4Delphi again in Lazarus.

**Comment by TB1234** [comment]
Fresh install of CEF4Delphi. I did not use it before. So I made it like you wrote

**Comment by salvadordf** [comment]
What OS and version are you using?

**Comment by TB1234** [comment]
ArchLinux, rolling release.

Lazarus with QT5 installed with fpcupdeluxe

**Comment by salvadordf** [comment]
I'll install it in a VM this weekend to see what's going on.

PGdkEventKey is declared in an include file inside the "gdk2" unit and perhaps the LCLGTK2 conditional in uCEFLinuxFunctions is not enabled.

**Comment by TB1234** [comment]
I tried it with Lazarus with gtk (not qt5). Same problem...

**Comment by salvadordf** [comment]
I just tried the latest Manjaro version which is based on Arch Linux and I installed Lazarus 2.0.12 with Pamac.

I installed DCPCrypt with the online package manager and then I downloaded the latest CEF4Delphi version from GitHub to install it with the LPK file.

I build and installed CEF4Delphi without problems and I could also build the MiniBrowser demo.

Perhaps it's necessary to configure fpcupdeluxe to install Lazarus with GTK2 support.

**Comment by TB1234** [comment]
As I wrote in my last post, I tried a GTK Lazarus an got the same result.

**Comment by TB1234** [comment]
I have an addtional information. I run also CEF4Delphi under Windows and this works fine. If I try to compile a project with 
 `LCLWidgetType:=qt5` I got the same error. So I think it is a problem with the QT5 widget. I don't know why I cannot use it with the GTK-Version of Lazarus on my Linux

**Comment by salvadordf** [comment]
CEF4Delphi doesn't support QT5 applications, only GTK2 in Linux. 

Open the CEF4Delphi package in Linux and then open the uCEFLinuxFunctions unit. 
See if the "gdk2" unit is enabled or grayed out in the "uses" section at the begining. 

You can only build CEF4Delphi if "gdk2" is enabled because the LCLGTK2 conditional is enabled by Lazarus.

**Comment by TB1234** [comment]
OK, that explains why I have problem to compile my QT5 applications. It also explains, why it does not work with Lazarus and QT5.

I created a new installation of Lazarus with GTK with fpcupdeluxe and now it is working. I do not know, why this does not work on the weekend.

So, the issue is closed.
