### ISSUE TITLE
CEF4 can't be used in Twitter

### ISSUE THREAD

**Issue by ddiiccoo** [salvadordf/CEF4Delphi#366]
When I use this control to access Twitter, I cannot update my account avatar, nor can I upload pictures。my system is win10 x64.when i use it to access www.youku.com . When I watch the video, it prompts that the browser version is too low.but my control version is 90.6.0
![捕获](https://user-images.githubusercontent.com/79918458/116500046-46450080-a8e0-11eb-9ee8-90444912a5e6.JPG)

**Comment by salvadordf** [comment]
This discussion was moved to this forum thread : 
https://www.briskbard.com/forum/viewtopic.php?f=8&t=1746
