### ISSUE TITLE
MacOs aarch64/x86_64 builds

### ISSUE THREAD

**Issue by PeterKieu** [salvadordf/CEF4Delphi#369]
Hi All,
I am building demos for Mac ARM64 CPU.

1. Device: MacOS Macbook M1
2. IDE Lazarus 2.1
3. FPC 3.2.2 intel-arm64 
4. CEF-builds: 91.1.17+g1845583+chromium-91.0.4472.101 / Chromium 91.0.4472.101 [Link]([https://cef-builds.spotifycdn.com/index.html#macosarm64])
5. CEF4Delphi 91.1.12

**Comment by salvadordf** [comment]
Hi,

If you find any issue building CEF4Delphi in an M1 CPU please let us know and provide all the details you can. 
I don't have a Macbook M1 computer and I can't do any test.

**Comment by PeterKieu** [comment]
Hi @salvadordf,

On Mac M1, I can run your CEF4Delphi Mac/AnyOS demos in Lazarus 2.1, FPC 3.2.2 with Project options: Darwin-x86_64 builds. This runs via Rosetta 2 interpreter - slower than normal as startup, but fast in HTML5 benchmark (521/555 point) and fast in almost website.

For Darwin-aarch64 demo builds (of course including Cef4Delphi Lib), the demo crash on startup. 
I realize that the 91.x version seems to run slower than 90.x one, not sure about internal security or any checking.

Can you please keep previous github branch for 90.x version? I need to debug Cef4Delphi 90.x + CEF 90.x MacOS ARM from Spotify builds.

Or please tell me the config params inside the CEF4Delphi package to match CEF version checking (e.g 90.x).

**Comment by salvadordf** [comment]
I'm glad that it works on that CPU too!

The latest release using CEF 90 was this one : 
https://github.com/salvadordf/CEF4Delphi/releases/tag/90.0.4430.212

I've never deleted any release version and you will always find it there.

The CEF binaries in the links from the release announcement are these : 
Windows 32 bits -> https://cef-builds.spotifycdn.com/cef_binary_90.6.7%2Bg19ba721%2Bchromium-90.0.4430.212_windows32.tar.bz2
Windows 64 bits -> https://cef-builds.spotifycdn.com/cef_binary_90.6.7%2Bg19ba721%2Bchromium-90.0.4430.212_windows64.tar.bz2
Linux x86 32 bits -> https://cef-builds.spotifycdn.com/cef_binary_90.6.7%2Bg19ba721%2Bchromium-90.0.4430.212_linux32.tar.bz2
Linux x86 64 bits -> https://cef-builds.spotifycdn.com/cef_binary_90.6.7%2Bg19ba721%2Bchromium-90.0.4430.212_linux64.tar.bz2
Linux ARM 32 bits -> https://cef-builds.spotifycdn.com/cef_binary_90.6.7%2Bg19ba721%2Bchromium-90.0.4430.212_linuxarm.tar.bz2
Linux ARM 64 bits -> https://cef-builds.spotifycdn.com/cef_binary_90.6.7%2Bg19ba721%2Bchromium-90.0.4430.212_linuxarm64.tar.bz2
MacOS x86 64 bits -> https://cef-builds.spotifycdn.com/cef_binary_90.6.7%2Bg19ba721%2Bchromium-90.0.4430.212_macosx64.tar.bz2

These are the packages for MacOS M1 (ARM64) used by that CEF4Delphi release version : 

- **Standard Distribution** : https://cef-builds.spotifycdn.com/cef_binary_90.6.7%2Bg19ba721%2Bchromium-90.0.4430.212_macosarm64.tar.bz2
- **Minimal Distribution** : https://cef-builds.spotifycdn.com/cef_binary_90.6.7%2Bg19ba721%2Bchromium-90.0.4430.212_macosarm64_minimal.tar.bz2
- **Sample Application** : https://cef-builds.spotifycdn.com/cef_binary_90.6.7%2Bg19ba721%2Bchromium-90.0.4430.212_macosarm64_client.tar.bz2
- **Debug Symbols** : https://cef-builds.spotifycdn.com/cef_binary_90.6.7%2Bg19ba721%2Bchromium-90.0.4430.212_macosarm64_debug_symbols.tar.bz2
- **Release Symbols** : https://cef-builds.spotifycdn.com/cef_binary_90.6.7%2Bg19ba721%2Bchromium-90.0.4430.212_macosarm64_release_symbols.tar.bz2

All the CEF binaries are here : 
https://cef-builds.spotifycdn.com/index.html

I've never debugged on MacOS but according to the CEF project maintainer you need to download “Debug Symbols” (dSYM) for the same CEF version, extract, and place the dSYM next to the “Chromium Embedded Framework” binary in the app bundle.
https://bitbucket.org/chromiumembedded/cef/issues/3144/mac-cefclient-crash-on-closing-after#comment-60666323

**Comment by PeterKieu** [comment]
Thanks much @salvadordf ,

Today, the new MacOs-arm64 CEF release 91.1.21+g9dd45fe+chromium-91.0.4472.114 / Chromium 91.0.4472.114 https://cef-builds.spotifycdn.com/index.html#macosarm64

But the sample cefclient  app ARM64 version still crashes on MacOS M1 BigSur 11.4, XCode 12.5.
Thus, I will report this on the official CEF issue tracker. All the cefclient apps should run well first, then our CEF4Delphi ones :)

UPDATE: I build CEF samples in Xcode then my cefclient runs well, not crash as the original cefclient sample. From crash info, I saw librosetta call on CEF Arm64 app/lib, thus FPC 3.2.2 intel-armmacos may have mis-leading building/linking flags.

**Comment by PeterKieu** [comment]
Looking around many links, I cannot find out the best solution for Lazarus MacOs codesigning.
Thus, let me close this issue which belongs to FreePascal-Lazarus-XCode.

What I can tell here is that:
- CEF4Delphi apps runs well on classic x86_64 or Rosetta2-interpreter Apple Silicon MacOS 
- CEF apps must be re-built and signed by Xcode to run well natively on MacOS Silicon/M1
- For CEF4Delphi native Darwin-ARM64 apps, signing must have been applied for the main app and app helper.
