### ISSUE TITLE
Google login problem

### ISSUE THREAD

**Issue by xiaonaiquan** [salvadordf/CEF4Delphi#370]
Have you solved this problem?
![image](https://user-images.githubusercontent.com/16412671/123402470-59233b00-d5da-11eb-87d9-0c3be85154b6.png)

**Comment by salvadordf** [comment]
Google is blocking all direct login attempts made by embedded browsers. Read this for more information :
https://www.briskbard.com/forum/viewtopic.php?f=8&t=1488&p=6201

Try using a different user agent string or the experimental _chrome runtime_ mode.
