### ISSUE TITLE
delphi chromium basic authentication in open link iframe

### ISSUE THREAD

**Issue by yarockiisergei** [salvadordf/CEF4Delphi#371]
Подскажите как включить запрос пользователя и пароль basic авторизацию в chromium ?

**Comment by salvadordf** [comment]
I'm sorry but I don't understand Russian. 

If the online translator is correct and you are asking about basic user authentication then use the **TChromium.OnGetAuthCredentials** event.

Read this document to know all the details about that event : 
https://magpcss.org/ceforum/apidocs3/projects/(default)/CefRequestHandler.html#GetAuthCredentials(CefRefPtr%3CCefBrowser%3E,constCefString&,bool,constCefString&,int,constCefString&,constCefString&,CefRefPtr%3CCefAuthCallback%3E)

Please, use our forums for more questions : 
https://www.briskbard.com/forum/
