### ISSUE TITLE
TChromium.SaveAsBitmapStream Fails 

### ISSUE THREAD

**Issue by MiG3000** [salvadordf/CEF4Delphi#374]
The method `TChromium.SaveAsBitmapStream` does not accept any descendants of `TStream`. If trying to call it with a `TMemoryStream` parameter, for example, the compiler throws: "[DCC Error] E2033 Types of actual and formal var parameters must be identical"

Even if called with a `TStream` parameter, it fails at runtime with "TStream.Seek not implemented" when executing line `aStream.position := 0;` in `TChromiumCore.CopyDCToBitmapStream`.

This issue can be fixed by changing:

`function TChromium.SaveAsBitmapStream(var aStream : TStream) : boolean;`
to
`function TChromium.SaveAsBitmapStream(const aStream : TStream) : boolean;`

...and...

`function  TChromiumCore.CopyDCToBitmapStream(aSrcDC : HDC; const aSrcRect : TRect; var aStream : TStream) : boolean;`
to
`function  TChromiumCore.CopyDCToBitmapStream(aSrcDC : HDC; const aSrcRect : TRect; const aStream : TStream) : boolean;`

**Comment by salvadordf** [comment]
Thanks for reporting and fixing this issue!
