### ISSUE TITLE
the component not working with cxGrid

### ISSUE THREAD

**Issue by hzmnet** [salvadordf/CEF4Delphi#376]
It always crashes when the app including the component cxGrid which uses unit cxDataControllerConditionalFormattingRulesManagerDialog
frxCtrls.

**Comment by hzmnet** [comment]
they are not the same issue

**Comment by salvadordf** [comment]
Keep in mind that by default CEF creates many child processes using the same EXE as your application and all the "initialization" and "finalization" sections are executed even in the subprocesses. 

That can create problems if you open the same resources (files, DDBB, etc) in those sections. Use a different EXE for the CEF subprocesses in your application. 

Please, search the support center at the DevExpress website and use our forum if you have more questions : 
https://www.briskbard.com/forum/

**Comment by hzmnet** [comment]
the issue also happens on other  company components

**Comment by hzmnet** [comment]
i think is not about the mult process lock problem , because i only put the component on the form did not load anything or write any codes
