### ISSUE TITLE
Add to get cookie from CEFUrlRequestClientComponent1

### ISSUE THREAD

**Issue by hzmnet** [salvadordf/CEF4Delphi#377]
we could not get the cookies when we GET a website. both response and request's cookies are blank！！！！

**Comment by salvadordf** [comment]
Please, provide a simple example to reproduce that problem in my computer.

Try using TCefCookieManagerRef.Global to get the global cookie manager. This is the cookie manager you used if you passed a nil as the "requestContext" parameter in the TCefUrlRequestRef.New call.

Then use a TCefFastCookieVisitor to get the cookies in the "visitor" procedure.
