### ISSUE TITLE
How To set timeout for the request?

### ISSUE THREAD

**Issue by hzmnet** [salvadordf/CEF4Delphi#379]
TCEFUrlRequestClientComponent has a big bug that it could not set the timeout for target require. also could no get any return status code. is there any way to handle these kinds of situations?

**Comment by salvadordf** [comment]
As far as I know, it's not possible to modify the timeout in Chromium connections.
https://superuser.com/questions/633648/how-can-i-change-the-default-website-connection-timeout-in-chrome

Try keeping a reference to the TCefUrlRequestRef and call TCefUrlRequestRef.cancel if a Delphi timer is triggered before completing the request.
