### ISSUE TITLE
request not invoke when using release BIN files

### ISSUE THREAD

**Issue by hzmnet** [salvadordf/CEF4Delphi#381]
there a big problem 

when using debug Bin files it crashes with cxGrid and InfoPower Grid. if change to using Release Bin file it will do not crash but all the URL requests are not invoked

**Comment by salvadordf** [comment]
Always use the binaries from the "Release" folder. The "Debug" binaries can create unexpected issues.

Read the "Additional notes" at the bottom : 
https://github.com/salvadordf/CEF4Delphi/wiki/Before-you-run-the-demos

Please, provide all the necessary code and details to reproduce the issue. Keep in mind that I can't test proprietary components.
Read this forum post : 
https://www.briskbard.com/forum/viewtopic.php?f=10&t=1050
