### ISSUE TITLE
uCEFChromiumCore.pas rare bug

### ISSUE THREAD

**Issue by Curtyop** [salvadordf/CEF4Delphi#384]
FChromium                         := TChromium.Create(nil);
  FChromium.Options.BackgroundColor := CefColorSetARGB($FF, $FF, $FF, $FF); //error line
In some rare cases, this error occurs(Rad Studio 10.3.3, CEF 92.0.27, Win10): 
Access violation at address 00000000008B086D in module 'project.exe'. Write of address 0000000000000048

**Comment by salvadordf** [comment]
Thanks for reporting this issue!
Please, download CEF4Delphi again to get the fix.
