### ISSUE TITLE
Thread-Safe AllocateHwnd and  DeallocateHwnd

### ISSUE THREAD

**Issue by Curtyop** [salvadordf/CEF4Delphi#386]
It would be very helpful if they became thread safe following an example like this.  https://stackoverflow.com/questions/8820294/how-can-i-make-allocatehwnd-threadsafe . It's just that I often create and kill Chromium in threads. Thanks for the development.

**Comment by Curtyop** [comment]
Or something like this https://github.com/TheLazyTomcat/lib.WndAlloc/blob/master/WndAlloc.pas

**Comment by Curtyop** [comment]
TBufferPanel is not thread safe too.

**Comment by Curtyop** [comment]
Made with replacement MakeObjectInstance and FreeObjectInstance. So it seems to be more correct.  https://pastebin.com/65zXQTwp

**Comment by salvadordf** [comment]
I could replace the custom messages in TChromiumCore.WndProc by a thread with a TEvent to avoid this patch but TBufferPanel inherits from TCustomPanel and VCL is not thread safe.

CEF uses multiple processes and threads by default and the main application thread shouldn't use much CPU time.

You can try adding the unit given in the answer from the first link to the DPR file of your application to see if it still works in Delphi 11 but I would suggest that you create all the TChromium components in the main application thread, or perhaps suggest this patch to Embarcadero at quality.embarcadero.com.

I'm sorry but this change would require **a lot** of testing before accepting it in the main branch.
