### ISSUE TITLE
cef4delphi support iframe?

### ISSUE THREAD

**Issue by jfhyn** [salvadordf/CEF4Delphi#39]
hello,  
In HTML, I put an iframe.
For example: <iframe class = "preview_iframe" id = "preview_mobile_iframe" src = "./ pre_mobile.html" frameborder = "0"> </ iframe>
It's normal to open the HTML in FireFox and operate,
But in CEF4D open, when sending data to the iframe, 
for example: html:		function DO_INIT_ON_WIN(a){
			var skyIframe = document.getElementById("preview_mobile_iframe");
			var iframeW = skyIframe.contentWindow;
			console.info(iframeW);
                        alert("1"); //reponse
			iframeW\["DO_INIT_ON_WIN_2"\](a);
                    alert("2"); // no reponse!!!!!
		};
delphi:
Chromium4.ExecuteJavaScript('DO_INIT_ON_WIN(' + AJson + ')', URLCbx.Text, 0);
it's failed,No response.  
why?
thanks.

**Comment by salvadordf** [comment]
Yes, iframes are supported by the Blink rendering engine. 
This looks like a pure HTML/JS problem outside the CEF4Delphi scope.
Please, test this code in Chrome and check the console messages inside the developer tools.

**Comment by jfhyn** [comment]
I test html again,
I found   html works well in firefox,but html doesn't work in chrome. 
Operate ifame must be flexible in chrome.
