### ISSUE TITLE
I can't open the whatsapp api in Chromium

### ISSUE THREAD

**Issue by ConciliarFacil** [salvadordf/CEF4Delphi#392]
Hello,

How do I open Whatsapp Web on Chromium?

When loading, the page is blank.

Thanks.

**Comment by salvadordf** [comment]
I just tried it with the MiniBrowser demo on Windows 10 and the latest CEF binaries and it seems to work fine. 
I loaded https://web.whatsapp.com, selected the option to link a device in the app and then I scanned the QR code with my phone.
After that I could see all my chats inside MiniBrowser.

If you need to handle videos and audio you will have to build the CEF binaries with proprietary codecs. 

Please, use our forum for more questions : 
https://www.briskbard.com/forum/

**Comment by ConciliarFacil** [comment]
I didn't give you the correct information.

web.whatsapp.com works correctly, but api.whatsapp.com does not.

Whenever I try to use wa.me/<number> the page is blank.
![whats](https://user-images.githubusercontent.com/40368334/140305419-ef9ccb32-9f42-4dc1-ade0-28c4276ca477.png)

**Comment by salvadordf** [comment]
The MiniBrowser demo shows this error when it opens https://wa.me with   : 
Failed to load URL whatsapp://chat/ with error ERR_UNKNOWN_URL_SCHEME (-302).

Any other browser redirects from wa.me to api.whatsapp.com correctly and MiniBrowser can load api.whatsapp.com without problems. This means that it could be necessary to handle unknown protocols and perhaps redirections.

Please, use our forum for more questions :
https://www.briskbard.com/forum/

**Comment by salvadordf** [comment]
I forgot to add that the network tab in the DevTools may have some interesting information.
Compare the DevTools in MiniBrowser and Chrome when you load that webpage.
