### ISSUE TITLE
Conflicting types

### ISSUE THREAD

**Issue by alex-vlaskin** [salvadordf/CEF4Delphi#393]
[bcc32c Error] uCEFMiscFunctions.hpp(75): conflicting types for 'TzSpecificLocalTimeToSystemTime'

on line:
extern "C" System::LongBool __stdcall TzSpecificLocalTimeToSystemTime(Winapi::Windows::PTimeZoneInformation lpTimeZoneInformation, Winapi::Windows::PSystemTime lpLocalTime, Winapi::Windows::PSystemTime lpUniversalTime);

 timezoneapi.h(73): previous declaration is here
TzSpecificLocalTimeToSystemTime(
    _In_opt_ CONST TIME_ZONE_INFORMATION* lpTimeZoneInformation,
    _In_ CONST SYSTEMTIME* lpLocalTime,
    _Out_ LPSYSTEMTIME lpUniversalTime
    );

C++ Builder 11 Alexandria

**Comment by salvadordf** [comment]
Hi,

TzSpecificLocalTimeToSystemTime is not defined in uCEFMiscFunctions.pas

However, uCEFMiscFunctions.pas uses **Winapi.Windows** and TzSpecificLocalTimeToSystemTime is defined in Winapi.Windows like this in Delphi 11 :
`function TzSpecificLocalTimeToSystemTime(lpTimeZoneInformation: PTimeZoneInformation;
  var lpLocalTime, lpUniversalTime: TSystemTime): BOOL; stdcall;`

I'm not an expert in C++ Builder but perhaps there's an option to install CEF4Delphi without adding all the code from the units in the "_uses_" section. 

Or perhaps the parameter types are defined the same way but with different names and C++ Builder is too strict.

In any case, this seems to be an issue Embarcadero should fix.

**Comment by salvadordf** [comment]
Closing because this seems to be a C++ Builder issue.
