### ISSUE TITLE
How do I disable the reaction to clicking the mouse wheel?

### ISSUE THREAD

**Issue by yarockiisergei** [salvadordf/CEF4Delphi#398]
How do I disable the reaction to clicking the mouse wheel?

**Comment by salvadordf** [comment]
Hi,

Try intercepting the Windows message in the TChromium.OnRenderCompMsg event if you're using a browser in normal mode.

If you use the off-screen rendering mode (OSR) then you can delete the code in your app that handles the WM_MOUSEWHEEL message.

Please, use our forums for more questions : 
https://www.briskbard.com/forum/index.php
