### ISSUE TITLE
Access violation error on StartMainProcess

### ISSUE THREAD

**Issue by aestemp** [salvadordf/CEF4Delphi#4]
Hi
Thanks for your worthwhile efforts.
I'm using Delphi XE8 under Windows 10. My application is 32 bit so I use the 32 bit equivalent for your recommended libcef.dll:
Windows 64-bit Builds: CEF 3.2924.1561.g06fde99 / Chromium 56.0.2924.76
Windows 32-bit Builds: CEF 3.2924.1564.g0ba0378 / Chromium 56.0.2924.76
But I get error (access violation read of a memory address) when calling StartMainProcess (the same error raised when  running the demos).
I trace the error: I reached cef_initialize in TCefApplication.InitializeLibrary.
Can you guide me what should I do?
Thanks in advance.

**Comment by salvadordf** [comment]
Use only the supported version of CEF3. Other version will probably crash your app.

For win32 applications use this : http://opensource.spotify.com/cefbuilds/cef_binary_3.2924.1561.g06fde99_windows32.tar.bz2

For win64 applications use this : 
http://opensource.spotify.com/cefbuilds/cef_binary_3.2924.1561.g06fde99_windows64.tar.bz2

It has been reported that win64 apps crash even with the supported libraries. I'll take a look as soon as I can.

**Comment by aestemp** [comment]
Thanks for your fast reply.
I downloaded and used it but the circumstances has not changed.
The same error raised!

**Comment by salvadordf** [comment]
Download the latest version. Now it works in 64bit.
