### ISSUE TITLE
Differences between CEF4Delphi and dcef3 focus/window messaging handling

### ISSUE THREAD

**Issue by petko** [salvadordf/CEF4Delphi#40]
I am trying to use my own popup menu component with CEF4Delphi. I use the `BeforeContextMenu` event to clear the `ICefMenuModel` parameter and then show my own popup menu. 

It used to work just fine with dcef3, but now with CEF4Delphi there are two issues:
1. If I use the DevExpress `dxBarPopupMenu`, it will show, but then clicking in the Chromium window or anywhere else in the application does not hide it and in most cases it even causes `Systen Error Code 5: access is denied` error (related to the `DestroyWindow` function I think).
2. I tried using the standard `TPopupMenu` instead in a sample project, but it will no even show when using `Popup(x, y)`.

So, what have changed in this regard between the two components that could cause this problem?

**Comment by petko** [comment]
After more tests, it seems that CEF4Delphi does not allow the DevExpress popup menu to be focused and this leads to the other problems. When I show it, using the keyboard does not move between the menu items, but scroll the page in the browser, so this is why I think the menu it is not focused.

In dcef3 it worked as expected. I am wondering what is different in CEF4Delphi..

**Comment by salvadordf** [comment]
CEF4Delphi is configured to use multiple processes and threads by default. 
Some TChromium events are called from different threads and the VCL doesn't like that.
If you create, modify or destroy any component in different threads you may get the "Systen Error Code 5: access is denied" error message.
For example, if you modify a component property and the VCL calls "RecreateWnd" internally, you may get that error message.
If you want to be safe, store the event parameters and send a custom message to the form. When you receive that message you can do whatever you want with your components but be careful because not all event parameters can be used outside the scope of the event.

**Comment by petko** [comment]
Thanks. I will try that and let you know if it solves the problem.

**Comment by petko** [comment]
Ok, this fixes the System Error. TPopupMenu also works as expected. 

The only remaining problem is that DevExpress popup menu still does not get the focus. I am wondering what could be causing the difference between CEF4Delphi and dcef3 in this regard..

**Comment by salvadordf** [comment]
Try to use the application.onmessage event to send the keyboard messages to your component if it's visible.

**Comment by petko** [comment]
Unfortunately key messages (`WM_KEYDOWN`, `WM_KEYUP`) and mouse messages (`WM_LBUTTONDOWN`, `WM_RBUTTONDOWN`, etc) are not trapped by `Application.OnMessage` while the CEF component is focused. `KeyPreview := True` for the main form does not help too.

You can reproduce that with the MiniBrowser demo too.

**Comment by salvadordf** [comment]
Try using TChromium.SetFocus(False) when other components have the focus and TChromium.SetFocus(True) when you wan to give the focus back to the browser. 

If you use TChromium in OSR mode, use TChromium.SendFocusEvent in the same way.

I forgot that the previous trick with application.onmessage is used for keyboard shortcuts. It's used with the TChromium.OnPreKeyEvent event to define each keyboard shortcut.

**Comment by petko** [comment]
`TChromium.SetFocus(False)` does not help unfortunately. The `OnMessage` event is still not fired for keyboard or mouse events. Probably for some reason `SetFocus(false)` does not unfocus the browser.

**Comment by salvadordf** [comment]
I have similar problems to hide some panels in BriskBard when the user clicks in the browser. 

You have 3 possible solutions : 

1. Use other TChromium events to hide context menus : OnGotFocus, OnPreKeyEvent, OnBeforeBrowse, etc.
2. Use a timer in the OnMouseLeave event (if it's available) and hide the component a second after the user moves the mouse out of that component.
3. Use a Hook to capture mouse or keyboard events. Read more about this here : 
https://msdn.microsoft.com/en-us/library/windows/desktop/ms644990(v=vs.85).aspx

**Comment by petko** [comment]
I've found this code that could help: https://stackoverflow.com/questions/8712974/override-mouse-using-chromium-embedded-framework

Is that OnCreate event available anyhow in CEF4Delphi?

**Comment by petko** [comment]
It turned out that there are other more complex issues with DevExpress menu and toolbar components, so I disabled multi-threaded support for CEF, where everything works as expected. 

I am closing the issue.

**Comment by krystian-broniszewski** [comment]
i have problems with dcef4 - only blank screen. old cef3 workith without problems

**Comment by salvadordf** [comment]
Use one of the demos as a template for your application.

Please use our forum for more questions : 
https://www.briskbard.com/forum/
