### ISSUE TITLE
Error compiling "uCEFMiscFunctions.pas" for Lazarus on macOS Big Sur

### ISSUE THREAD

**Issue by uniho** [salvadordf/CEF4Delphi#401]
Could you check it?

CEF4Delphi: 97.1.1
OS: MacOS Big Sur
CPU: x86_64
Lazarus: 2.2.0 (instaled from Lazarus-2.2.0-0-x86_64-macosx.pkg)
fpc: 3.2.2 (instaled from fpc-3.2.2.intelarm64-macosx.dmg, fpc-src-3.2.2-20210709-macosx.dmg)

Incidentally I fixed it to use "CocoaAll" unit in implementation section in uCEFMiscFunctions.pas.

**Comment by salvadordf** [comment]
I'll try to check it as soon as I can. I don't have a Mac and I have to ask a for favors with every test.

**Comment by uniho** [comment]
You might test it on VM. 
See [https://www.makeuseof.com/tag/macos-windows-10-virtual-machine/](https://www.makeuseof.com/tag/macos-windows-10-virtual-machine/)

**Comment by salvadordf** [comment]
We couldn't build the ide in that OS. We had this error about a missing "idewindowintf" unit : 
https://forum.lazarus.freepascal.org/index.php?topic=57752.msg429772#msg429772

I guess you are using fpcupdeluxe with a development version of Lazarus and FPC.
I decided to add the CocoaAll unit anyway. Please, let me know if this solves this issue.

**Comment by uniho** [comment]
I have not been using fpcupdeluxe.
I just installed  fpc-3.2.2.intelarm64-macosx.dmg, fpc-src-3.2.2-20210709-macosx.dmg, and Lazarus-2.2.0-0-x86_64-macosx.pkg as described in [the wiki](https://wiki.lazarus.freepascal.org/Installing_Lazarus_on_macOS).
And see [here](https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/39535).

**Comment by uniho** [comment]
I confirmed that it can be compiled at f6f2539 for now.
Thanks.
