### ISSUE TITLE
Demos don't resize the browser when the form is resized with Lazarus 2.2.0 on macOS Big Sur.

### ISSUE THREAD

**Issue by uniho** [salvadordf/CEF4Delphi#402]
Demos don't resize the browser when the form is resized  with Lazarus 2.2.0 on macOS Big Sur.

CEF4Delphi: f6f2539
CEF3: 97.1.5
OS: MacOS Big Sur
CPU: x86_64
Lazarus: 2.2.0 (instaled from Lazarus-2.2.0-0-x86_64-macosx.pkg)
fpc: 3.2.2 (instaled from fpc-3.2.2.intelarm64-macosx.dmg, fpc-src-3.2.2-20210709-macosx.dmg)

I checked [`/demos/Lazarus_Mac/ExternalPumpBrowser/`](https://github.com/salvadordf/CEF4Delphi/tree/master/demos/Lazarus_Mac/ExternalPumpBrowser) and [`/demos/Lazarus_any_OS/BrowserWindow/`](https://github.com/salvadordf/CEF4Delphi/tree/master/demos/Lazarus_any_OS/BrowserWindow) at least.

**Comment by uniho** [comment]
I found a solution.
```
TForm1 = class(TForm)
  ：
protected
  procedure RealizeBounds; override;
  ：
end;

  ：
procedure TForm1.RealizeBounds;
var
  size: NSSize;
begin
  inherited;
  size.width:= Self.ClientWidth;
  size.height:= Self.ClientHeight;
  NSView(Self.Chromium.WindowHandle).setFrameSize(size);
end;
  ：
```
Thanks!

**Comment by salvadordf** [comment]
The last update includes your fix in TCEFLinkedWinControlBase.UpdateSize.
Let me know if it works correctly.
Thanks!

**Comment by uniho** [comment]
[BeBop](https://github.com/uniho/BeBop) on MacOS became almost perfect.
Thanks!
