### ISSUE TITLE
Macos ARM M1:  invalid type cast in uCEFv8Handler unit

### ISSUE THREAD

**Issue by TimKieu** [salvadordf/CEF4Delphi#406]
Hi, 
I am back to build and test for Macos silicon Arm CPU.
Context:
- IDE Delphi 11 on Windows 11 ARM virtual on Macbook M1 => cross compiler: Delphi x64 on Windows Arm then link Macos SDK on M1
- Demo source: FMXExternalPumpBrowser
- Build error message in the  uCEFv8Handler unit:
[dccosxarm64 Error] uCEFv8Handler.pas(732): E2089 Invalid typecast
ud.SetValueByIndex(1, TCefv8ValueRef.NewInt(Integer(v.AsInterface)));

[dccosxarm64 Error] uCEFv8Handler.pas(866): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
TThread.Synchronize(nil, procedure begin
                            ret := pr.GetValue(val);
                          end);
...

**Comment by TimKieu** [comment]
This issue can be fixed as this way:
Line 732 Replace: ud.SetValueByIndex(1, TCefv8ValueRef.NewInt(Integer(v.AsInterface)));
By: ud.SetValueByIndex(1, TCefv8ValueRef.NewInt(Integer(Pointer(v.AsInterface))));

**Comment by salvadordf** [comment]
Hi,

I don't have a Mac computer and I can't test this but I recently added a new TARGET_64BITS conditional to fix issues building apps in Raspberry Pi OS 64 bits which also has an ARM CPU.

I forgot to update the conditionals in that unit and perhaps this was causing the build issue you describe.

Please, download CEF4Delphi again and see if this build issue is now fixed.
