### ISSUE TITLE
problem reading page with digital certificate

### ISSUE THREAD

**Issue by rodrigo-ogioni** [salvadordf/CEF4Delphi#408]
Good afternoon,
When I open a page with a digital certificate, it doesn't show the popup to select the certificate, what can I do to fix this?
Grateful

**Comment by salvadordf** [comment]
Hi Rodrigo,

You need to use the TChromium.OnSelectClientCertificate event and show a custom dialog with the certificates to the user.

Read these forum threads for more information : 
https://www.briskbard.com/forum/viewtopic.php?f=8&t=1443
https://www.briskbard.com/forum/viewtopic.php?f=8&t=604

**Comment by rodrigo-ogioni** [comment]
Thanks for the answer! Do you have an example where I can guide myself?
Grateful

**Comment by salvadordf** [comment]
No, sorry. The demos don't have an example of that feature but those threads have all the information you need.
Don't hesitate to register in our forum. There's a ton of information about CEF4Delphi there.

**Comment by rodrigo-ogioni** [comment]
I believe that it is not difficult for you, but I could not understand how to use this feature, so it would be interesting to have a demo of how to do it.
Grateful

**Comment by salvadordf** [comment]
Download the latest CEF4Delphi version. 
The MiniBrowser VCL demo now has a certificate selection form.

**Comment by rodrigo-ogioni** [comment]
> Download the latest CEF4Delphi version. The MiniBrowser VCL demo now has a certificate selection form.

Thank you, it helped a lot. And is there a way to select the certificate right when the page is loaded? instead of waiting for a user to click the button to invoke the certificate selection window? Like, onloadend already call the certificate.
Grateful

**Comment by salvadordf** [comment]
The browser will use the first certificate automatically if you don't use the TChromium.OnSelectClientCertificate event.
You can also use that event, call callback.Select with the right certificate as the parameter and set Result to True.

Please, use our forums for more questions : 
https://www.briskbard.com/forum/

**Comment by rodrigo-ogioni** [comment]
> The browser will use the first certificate automatically if you don't use the TChromium.OnSelectClientCertificate event. You can also use that event, call callback.Select with the right certificate as the parameter and set Result to True.
> 
> Please, use our forums for more questions : https://www.briskbard.com/forum/

Good morning, I tried to register on the forum, but the confirmation email is not sent and I cannot enter the forum. On some sites it works the way you said, but on a specific site, it doesn't call the certificate for choice. But in chrome it calls correctly. So I was thinking about forcing the certificate call on site sign-in. It is possible? Grateful

**Comment by salvadordf** [comment]
I just activated your forum user manually. Let's continue this conversation there.
