### ISSUE TITLE
Building Designtime Package in XE7

### ISSUE THREAD

**Issue by Pamoho** [salvadordf/CEF4Delphi#409]
(OK I know we should have moved on!  But as one of our Apps needs a package that still requires XE7, we need to have CEF4delphi built with that ancient compiler!)

The Runtime Package is fine, but there are two errors that prevent CEF4DelphiFMXRTL Package from being built:

1. uCEFFMXBufferPanel.pas compile fails with "Property 'OnResized' does not exist in base class"
2. uCEFFMXWorkScheduler.pas compile fails with "Undeclared identifier: 'ForceQueue'"

I got around problem #1 just by commenting out the reference to "OnResized".  This does not seem to have caused any problems for XE7 or any of the later versions of Delphi.

I got around problem #2 by changing the Conditional Variable before the reference to "ForceQueue" from "Delphi18_up" to "Delphi22_up". 

Any suggestions?

Cheers, Paul

**Comment by salvadordf** [comment]
Thanks for reporting this issue!
Please, download CEF4Delphi again to get the fix for those bugs.
