### ISSUE TITLE
Differect directory  FrameworkDirPath and ResourcesDirPath - App not start

### ISSUE THREAD

**Issue by dimmaq** [salvadordf/CEF4Delphi#41]
Example
```
  GlobalCEFApp.FrameworkDirPath     := 'cef\';
  GlobalCEFApp.ResourcesDirPath     := 'cef\resources\';
```
cef.log
> [0717/154140.059:ERROR:icu_util.cc(173)] Invalid file descriptor to ICU data received.
> [0717/154140.060:ERROR:CEF4Delphi(1)] TCefApplication.InitializeLibrary error : External exception 80000003

**Comment by salvadordf** [comment]
I fixed a bug in the CEF3 binaries checking functions but I'm afraid I can't fix your bug because some files are hard-coded in Chromium.
https://bitbucket.org/chromiumembedded/cef/issues/1398

Use the same directory for the framework and the resources.
