### ISSUE TITLE
Twitch streams not playing

### ISSUE THREAD

**Issue by toxicdream** [salvadordf/CEF4Delphi#412]
Any videostreams from twitch.com not playing.
Video areas show next message:
`This video is either unavailable or not supported in this browser. (Error #4000)`

I try modify any parameters but it's unsuccessfully.
```
  GlobalCEFApp.EnableGPU            := True;      // Enable hardware acceleration
  GlobalCEFApp.EnableMediaStream    := True;
  GlobalCEFApp.EnableUsermediaScreenCapturing := True;
  GlobalCEFApp.EnableSpeechInput    := True;
  GlobalCEFApp.EnableHighDPISupport := True;
```

**Comment by salvadordf** [comment]
Hi,
The Twitch videos use proprietary codecs and the CEF binaries available at Spotify only include open source codecs.
You need to build the CEF binaries with proprietary codecs following this guide : 
https://www.briskbard.com/forum/viewtopic.php?f=10&t=1097
