### ISSUE TITLE
Error Building on XE2

### ISSUE THREAD

**Issue by bemgiz** [salvadordf/CEF4Delphi#414]
Error Building  CEF4Delphi on Delphi XE2 update 4

Message Build Error : 
    [DCC Error] uCEFArgCopy.pas(112): E2003 Undeclared identifier: 'StrDispose'

Complete code at line 112  on file uCEFArgCopy.pas:   
    {$IFNDEF FPC}System.AnsiStrings.{$ENDIF}StrDispose(FArgVCopy[i]);

I put this Path at Delphi Library : 
    D:\Projetos\Bibliotecas\Chromium - Tortoise\trunk\source

Complete Error Messages : 
Checking project dependencies...
Building CEF4DelphiVCLRTL.dproj (Debug, Win32)
brcc32 command line for "CEF4DelphiVCLRTL.vrc"
  c:\program files (x86)\embarcadero\rad studio\9.0\bin\cgrc.exe -c65001 "CEF4DelphiVCLRTL.vrc" -foCEF4DelphiVCLRTL.res 
dcc command line for "CEF4DelphiVCLRTL.dpk"
  c:\program files (x86)\embarcadero\rad studio\9.0\bin\dcc32.exe -$O- -$W+ --no-config -B -Q -TX.bpl 
  -AGenerics.Collections=System.Generics.Collections;Generics.Defaults=System.Generics.Defaults;WinTypes=Windows;WinProcs=Windows;DbiTypes=BDE;
  DbiProcs=BDE;DbiErrs=BDE -DDEBUG -E.\Win32\Debug -I"c:\program files (x86)\embarcadero\rad studio\9.0\lib\Win32\debug";"c:\program files 
  (x86)\embarcadero\rad studio\9.0\RaveReports\Lib";"D:\Projetos\Bibliotecas\Jedi - XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\lib\d16\win32\debug";
  D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\lib\d16\win32\debug;"c:\program files (x86)\embarcadero\rad studio\9.0\lib\Win32\release";
  "C:\Users\Joao\OneDrive\João\1 - Projetos\RAD Studio\9.0\Imports";"c:\program files (x86)\embarcadero\rad studio\9.0\Imports";
  "C:\Users\Public\Documents\RAD Studio\9.0\Dcp";"c:\program files (x86)\embarcadero\rad studio\9.0\include";"c:\program files (x86)\embarcadero\rad 
  studio\9.0\RaveReports\Lib";"C:\Program Files (x86)\Raize\CS5\Lib\RS-XE2\Win32";"D:\Projetos\Bibliotecas\Jedi - 
  XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\lib\d16\win32";"D:\Projetos\Bibliotecas\Jedi - XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\source\include";
  D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\lib\d16\win32;D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\source\include;
  D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\lib\D16\win32;D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\common;
  D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\Resources;D:\Projetos\Bibliotecas\ZEOS\packages\DelphiXE2\Win32\Debug;
  D:\Projetos\Bibliotecas\tdbf701\packages\DelphiXE2\dcu;"D:\Projetos\Bibliotecas\Chromium - Tortoise\trunk\source" -LE"C:\Users\Public\Documents\RAD 
  Studio\9.0\Bpl" -LN"C:\Users\Public\Documents\RAD Studio\9.0\Dcp" -N0.\Win32\Debug -NSWinapi;System.Win;Data.Win;Datasnap.Win;Web.Win;Soap.Win;
  Xml.Win;Bde;System;Xml;Data;Datasnap;Web;Soap;Vcl;Vcl.Imaging;Vcl.Touch;Vcl.Samples;Vcl.Shell; -O"c:\program files (x86)\embarcadero\rad 
  studio\9.0\lib\Win32\release";"C:\Users\Joao\OneDrive\João\1 - Projetos\RAD Studio\9.0\Imports";"c:\program files (x86)\embarcadero\rad 
  studio\9.0\Imports";"C:\Users\Public\Documents\RAD Studio\9.0\Dcp";"c:\program files (x86)\embarcadero\rad studio\9.0\include";"c:\program files 
  (x86)\embarcadero\rad studio\9.0\RaveReports\Lib";"C:\Program Files (x86)\Raize\CS5\Lib\RS-XE2\Win32";"D:\Projetos\Bibliotecas\Jedi - 
  XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\lib\d16\win32";"D:\Projetos\Bibliotecas\Jedi - XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\source\include";
  D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\lib\d16\win32;D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\source\include;
  D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\lib\D16\win32;D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\common;
  D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\Resources;D:\Projetos\Bibliotecas\ZEOS\packages\DelphiXE2\Win32\Debug;
  D:\Projetos\Bibliotecas\tdbf701\packages\DelphiXE2\dcu;"D:\Projetos\Bibliotecas\Chromium - Tortoise\trunk\source" -R"c:\program files 
  (x86)\embarcadero\rad studio\9.0\lib\Win32\release";"C:\Users\Joao\OneDrive\João\1 - Projetos\RAD Studio\9.0\Imports";"c:\program files 
  (x86)\embarcadero\rad studio\9.0\Imports";"C:\Users\Public\Documents\RAD Studio\9.0\Dcp";"c:\program files (x86)\embarcadero\rad studio\9.0\include";
  "c:\program files (x86)\embarcadero\rad studio\9.0\RaveReports\Lib";"C:\Program Files (x86)\Raize\CS5\Lib\RS-XE2\Win32";"D:\Projetos\Bibliotecas\Jedi 
  - XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\lib\d16\win32";"D:\Projetos\Bibliotecas\Jedi - XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\source\include";
  D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\lib\d16\win32;D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\source\include;
  D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\lib\D16\win32;D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\common;
  D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\Resources;D:\Projetos\Bibliotecas\ZEOS\packages\DelphiXE2\Win32\Debug;
  D:\Projetos\Bibliotecas\tdbf701\packages\DelphiXE2\dcu;"D:\Projetos\Bibliotecas\Chromium - Tortoise\trunk\source" -U"c:\program files 
  (x86)\embarcadero\rad studio\9.0\lib\Win32\debug";"c:\program files (x86)\embarcadero\rad studio\9.0\RaveReports\Lib";"D:\Projetos\Bibliotecas\Jedi - 
  XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\lib\d16\win32\debug";D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\lib\d16\win32\debug;"c:\program files 
  (x86)\embarcadero\rad studio\9.0\lib\Win32\release";"C:\Users\Joao\OneDrive\João\1 - Projetos\RAD Studio\9.0\Imports";"c:\program files 
  (x86)\embarcadero\rad studio\9.0\Imports";"C:\Users\Public\Documents\RAD Studio\9.0\Dcp";"c:\program files (x86)\embarcadero\rad studio\9.0\include";
  "c:\program files (x86)\embarcadero\rad studio\9.0\RaveReports\Lib";"C:\Program Files (x86)\Raize\CS5\Lib\RS-XE2\Win32";"D:\Projetos\Bibliotecas\Jedi 
  - XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\lib\d16\win32";"D:\Projetos\Bibliotecas\Jedi - XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\source\include";
  D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\lib\d16\win32;D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\source\include;
  D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\lib\D16\win32;D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\common;
  D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\Resources;D:\Projetos\Bibliotecas\ZEOS\packages\DelphiXE2\Win32\Debug;
  D:\Projetos\Bibliotecas\tdbf701\packages\DelphiXE2\dcu;"D:\Projetos\Bibliotecas\Chromium - Tortoise\trunk\source" -V -VN --description:"CEF4Delphi 
  Runtime" -JL -NB"C:\Users\Public\Documents\RAD Studio\9.0\Dcp" -NH"C:\Users\Public\Documents\RAD Studio\9.0\hpp" -NO"C:\Users\Public\Documents\RAD 
  Studio\9.0\Dcp"   CEF4DelphiVCLRTL.dpk   
[DCC Warning] uCEFApplicationCore.pas(2066): W1000 Symbol 'GetLocaleFormatSettings' is deprecated: 'Use TFormatSettings.Create(Locale)'
[DCC Warning] uCEFApplicationCore.pas(2066): W1002 Symbol 'GetLocaleFormatSettings' is specific to a platform
[DCC Error] uCEFArgCopy.pas(112): E2003 Undeclared identifier: 'StrDispose'
[DCC Error] uCEFArgCopy.pas(143): E2003 Undeclared identifier: 'StrCopy'
[DCC Fatal Error] CEF4DelphiVCLRTL.dpk(225): F2063 Could not compile used unit 'uCEFArgCopy.pas'
Failed
Elapsed time: 00:00:02.2

What I do, please ? 
Thank you

**Comment by salvadordf** [comment]
Embarcadero's wiki is still partially down and I had to use web.archive.org to search for information about those units.

I don't have XE2 and I can't test this issue but it should be fixed now. Please, download CEF4Delphi again and let me know if you have any other issue.

PS : Older Delphi versions had FMX issues. If your application only uses VCL then you can build and install CEF4Delphi.dpk instead of CEF4Delphi_group.groupproj

**Comment by bemgiz** [comment]
Thank you Salvador,

I use only VCL on Delphi XE2.

I downloaded the new version of CEF4Delphi and I tried the new orientation
but, now, have another error when compiling CEF4Delphi.dpk :

[image: image.png]


Messages :

Checking project dependencies...
Building CEF4Delphi.dproj (Debug, Win32)
brcc32 command line for "CEF4Delphi.vrc"
  c:\program files (x86)\embarcadero\rad studio\9.0\bin\cgrc.exe -c65001
"CEF4Delphi.vrc" -foCEF4Delphi.res
dcc command line for "CEF4Delphi.dpk"
  c:\program files (x86)\embarcadero\rad studio\9.0\bin\dcc32.exe -$O- -$W+
--no-config -B -Q -Z -TX.bpl

-AGenerics.Collections=System.Generics.Collections;Generics.Defaults=System.Generics.Defaults;WinTypes=Windows;WinProcs=Windows;DbiTypes=BDE;
  DbiProcs=BDE;DbiErrs=BDE -DDEBUG -I"c:\program files
(x86)\embarcadero\rad
studio\9.0\lib\Win32\release";"C:\Users\Joao\OneDrive\João\1 -
  Projetos\RAD Studio\9.0\Imports";"c:\program files (x86)\embarcadero\rad
studio\9.0\Imports";"C:\Users\Public\Documents\RAD Studio\9.0\Dcp";
  "c:\program files (x86)\embarcadero\rad studio\9.0\include";"c:\program
files (x86)\embarcadero\rad studio\9.0\RaveReports\Lib";"C:\Program Files
  (x86)\Raize\CS5\Lib\RS-XE2\Win32";"D:\Projetos\Bibliotecas\Jedi -
XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\lib\d16\win32";"D:\Projetos\Bibliotecas\Jedi
-

XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\source\include";D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\lib\d16\win32;

D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\source\include;D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\lib\D16\win32;

D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\common;D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\Resources;

D:\Projetos\Bibliotecas\ZEOS\packages\DelphiXE2\Win32\Debug;D:\Projetos\Bibliotecas\tdbf701\packages\DelphiXE2\dcu;"D:\Projetos\Bibliotecas\Chromium

  - Tortoise\trunk\source" -LE"C:\Users\Public\Documents\RAD
Studio\9.0\Bpl" -LN"C:\Users\Public\Documents\RAD Studio\9.0\Dcp"
-NSWinapi;System.Win;

Data.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;Bde;Vcl;Vcl.Imaging;Vcl.Touch;Vcl.Samples;Vcl.Shell;System;Xml;Data;Datasnap;Web;Soap;
-O"c:\program
  files (x86)\embarcadero\rad
studio\9.0\lib\Win32\release";"C:\Users\Joao\OneDrive\João\1 - Projetos\RAD
Studio\9.0\Imports";"c:\program files
  (x86)\embarcadero\rad studio\9.0\Imports";"C:\Users\Public\Documents\RAD
Studio\9.0\Dcp";"c:\program files (x86)\embarcadero\rad studio\9.0\include";
  "c:\program files (x86)\embarcadero\rad
studio\9.0\RaveReports\Lib";"C:\Program Files
(x86)\Raize\CS5\Lib\RS-XE2\Win32";"D:\Projetos\Bibliotecas\Jedi
  -
XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\lib\d16\win32";"D:\Projetos\Bibliotecas\Jedi
- XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\source\include";

D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\lib\d16\win32;D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\source\include;

D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\lib\D16\win32;D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\common;

D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\Resources;D:\Projetos\Bibliotecas\ZEOS\packages\DelphiXE2\Win32\Debug;

D:\Projetos\Bibliotecas\tdbf701\packages\DelphiXE2\dcu;"D:\Projetos\Bibliotecas\Chromium
- Tortoise\trunk\source" -R"c:\program files
  (x86)\embarcadero\rad
studio\9.0\lib\Win32\release";"C:\Users\Joao\OneDrive\João\1 - Projetos\RAD
Studio\9.0\Imports";"c:\program files
  (x86)\embarcadero\rad studio\9.0\Imports";"C:\Users\Public\Documents\RAD
Studio\9.0\Dcp";"c:\program files (x86)\embarcadero\rad studio\9.0\include";
  "c:\program files (x86)\embarcadero\rad
studio\9.0\RaveReports\Lib";"C:\Program Files
(x86)\Raize\CS5\Lib\RS-XE2\Win32";"D:\Projetos\Bibliotecas\Jedi
  -
XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\lib\d16\win32";"D:\Projetos\Bibliotecas\Jedi
- XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\source\include";

D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\lib\d16\win32;D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\source\include;

D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\lib\D16\win32;D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\common;

D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\Resources;D:\Projetos\Bibliotecas\ZEOS\packages\DelphiXE2\Win32\Debug;

D:\Projetos\Bibliotecas\tdbf701\packages\DelphiXE2\dcu;"D:\Projetos\Bibliotecas\Chromium
- Tortoise\trunk\source" -U"c:\program files
  (x86)\embarcadero\rad
studio\9.0\lib\Win32\release";"C:\Users\Joao\OneDrive\João\1 - Projetos\RAD
Studio\9.0\Imports";"c:\program files
  (x86)\embarcadero\rad studio\9.0\Imports";"C:\Users\Public\Documents\RAD
Studio\9.0\Dcp";"c:\program files (x86)\embarcadero\rad studio\9.0\include";
  "c:\program files (x86)\embarcadero\rad
studio\9.0\RaveReports\Lib";"C:\Program Files
(x86)\Raize\CS5\Lib\RS-XE2\Win32";"D:\Projetos\Bibliotecas\Jedi
  -
XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\lib\d16\win32";"D:\Projetos\Bibliotecas\Jedi
- XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\source\include";

D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\lib\d16\win32;D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\source\include;

D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\lib\D16\win32;D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\common;

D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\Resources;D:\Projetos\Bibliotecas\ZEOS\packages\DelphiXE2\Win32\Debug;

D:\Projetos\Bibliotecas\tdbf701\packages\DelphiXE2\dcu;"D:\Projetos\Bibliotecas\Chromium
- Tortoise\trunk\source" -K00400000 --description:CEF4Delphi
  -NB"C:\Users\Public\Documents\RAD Studio\9.0\Dcp"
-NH"C:\Users\Public\Documents\RAD Studio\9.0\hpp"   CEF4Delphi.dpk
[DCC Error] CEF4Delphi.dpk(32): E2029 'END' expected but identifier
'rrequires' found
[DCC Error] CEF4Delphi.dpk(231): E2029 '.' expected but end of file found
Failed
Elapsed time: 00:00:00.2






I also tryed to compile CEF4Delphi_group.groupproj an the error is another,
now on CEF4DelphiFMXRTL  :


[image: image.png]



Messages :

Checking project dependencies...
Compiling CEF4Delphi_designtime.dproj (Debug, Win32)
dcc command line for "CEF4Delphi_designtime.dpk"
  c:\program files (x86)\embarcadero\rad studio\9.0\bin\dcc32.exe -$O- -$W+
--no-config -M -Q -TX.bpl

-AGenerics.Collections=System.Generics.Collections;Generics.Defaults=System.Generics.Defaults;WinTypes=Windows;WinProcs=Windows;DbiTypes=BDE;
  DbiProcs=BDE;DbiErrs=BDE -DDEBUG -E.\Win32\Debug -I"c:\program files
(x86)\embarcadero\rad studio\9.0\lib\Win32\debug";"c:\program files
  (x86)\embarcadero\rad
studio\9.0\RaveReports\Lib";"D:\Projetos\Bibliotecas\Jedi -
XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\lib\d16\win32\debug";

D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\lib\d16\win32\debug;"c:\program
files (x86)\embarcadero\rad studio\9.0\lib\Win32\release";
  "C:\Users\Joao\OneDrive\João\1 - Projetos\RAD
Studio\9.0\Imports";"c:\program files (x86)\embarcadero\rad
studio\9.0\Imports";
  "C:\Users\Public\Documents\RAD Studio\9.0\Dcp";"c:\program files
(x86)\embarcadero\rad studio\9.0\include";"c:\program files
(x86)\embarcadero\rad
  studio\9.0\RaveReports\Lib";"C:\Program Files
(x86)\Raize\CS5\Lib\RS-XE2\Win32";"D:\Projetos\Bibliotecas\Jedi -

XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\lib\d16\win32";"D:\Projetos\Bibliotecas\Jedi
- XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\source\include";

D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\lib\d16\win32;D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\source\include;

D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\lib\D16\win32;D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\common;

D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\Resources;D:\Projetos\Bibliotecas\ZEOS\packages\DelphiXE2\Win32\Debug;

D:\Projetos\Bibliotecas\tdbf701\packages\DelphiXE2\dcu;"D:\Projetos\Bibliotecas\Chromium
- Tortoise\trunk\source" -LE"C:\Users\Public\Documents\RAD
  Studio\9.0\Bpl" -LN"C:\Users\Public\Documents\RAD Studio\9.0\Dcp"
-N0.\Win32\Debug
-NSWinapi;System.Win;Data.Win;Datasnap.Win;Web.Win;Soap.Win;
  Xml.Win;Bde;System;Xml;Data;Datasnap;Web;Soap; -O"c:\program files
(x86)\embarcadero\rad
studio\9.0\lib\Win32\release";"C:\Users\Joao\OneDrive\João\1
  - Projetos\RAD Studio\9.0\Imports";"c:\program files
(x86)\embarcadero\rad studio\9.0\Imports";"C:\Users\Public\Documents\RAD
Studio\9.0\Dcp";
  "c:\program files (x86)\embarcadero\rad studio\9.0\include";"c:\program
files (x86)\embarcadero\rad studio\9.0\RaveReports\Lib";"C:\Program Files
  (x86)\Raize\CS5\Lib\RS-XE2\Win32";"D:\Projetos\Bibliotecas\Jedi -
XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\lib\d16\win32";"D:\Projetos\Bibliotecas\Jedi
-

XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\source\include";D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\lib\d16\win32;

D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\source\include;D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\lib\D16\win32;

D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\common;D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\Resources;

D:\Projetos\Bibliotecas\ZEOS\packages\DelphiXE2\Win32\Debug;D:\Projetos\Bibliotecas\tdbf701\packages\DelphiXE2\dcu;"D:\Projetos\Bibliotecas\Chromium

  - Tortoise\trunk\source" -R"c:\program files (x86)\embarcadero\rad
studio\9.0\lib\Win32\release";"C:\Users\Joao\OneDrive\João\1 - Projetos\RAD
  Studio\9.0\Imports";"c:\program files (x86)\embarcadero\rad
studio\9.0\Imports";"C:\Users\Public\Documents\RAD
Studio\9.0\Dcp";"c:\program files
  (x86)\embarcadero\rad studio\9.0\include";"c:\program files
(x86)\embarcadero\rad studio\9.0\RaveReports\Lib";"C:\Program Files
  (x86)\Raize\CS5\Lib\RS-XE2\Win32";"D:\Projetos\Bibliotecas\Jedi -
XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\lib\d16\win32";"D:\Projetos\Bibliotecas\Jedi
-

XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\source\include";D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\lib\d16\win32;

D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\source\include;D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\lib\D16\win32;

D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\common;D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\Resources;

D:\Projetos\Bibliotecas\ZEOS\packages\DelphiXE2\Win32\Debug;D:\Projetos\Bibliotecas\tdbf701\packages\DelphiXE2\dcu;"D:\Projetos\Bibliotecas\Chromium

  - Tortoise\trunk\source" -U"c:\program files (x86)\embarcadero\rad
studio\9.0\lib\Win32\debug";"c:\program files (x86)\embarcadero\rad
  studio\9.0\RaveReports\Lib";"D:\Projetos\Bibliotecas\Jedi -
XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\lib\d16\win32\debug";

D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\lib\d16\win32\debug;"c:\program
files (x86)\embarcadero\rad studio\9.0\lib\Win32\release";
  "C:\Users\Joao\OneDrive\João\1 - Projetos\RAD
Studio\9.0\Imports";"c:\program files (x86)\embarcadero\rad
studio\9.0\Imports";
  "C:\Users\Public\Documents\RAD Studio\9.0\Dcp";"c:\program files
(x86)\embarcadero\rad studio\9.0\include";"c:\program files
(x86)\embarcadero\rad
  studio\9.0\RaveReports\Lib";"C:\Program Files
(x86)\Raize\CS5\Lib\RS-XE2\Win32";"D:\Projetos\Bibliotecas\Jedi -

XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\lib\d16\win32";"D:\Projetos\Bibliotecas\Jedi
- XE2\jcl-2.4.1.4571\jcl-2.4.1.4571\source\include";

D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\lib\d16\win32;D:\Projetos\Bibliotecas\Jedi\jcl-master\jcl-master\jcl\source\include;

D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\lib\D16\win32;D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\common;

D:\Projetos\Bibliotecas\Jedi\jvcl-master\jvcl-master\jvcl\Resources;D:\Projetos\Bibliotecas\ZEOS\packages\DelphiXE2\Win32\Debug;

D:\Projetos\Bibliotecas\tdbf701\packages\DelphiXE2\dcu;"D:\Projetos\Bibliotecas\Chromium
- Tortoise\trunk\source" -V -VN --description:CEF4Delphi -JL
  -NB"C:\Users\Public\Documents\RAD Studio\9.0\Dcp"
-NH"C:\Users\Public\Documents\RAD Studio\9.0\hpp"
-NO"C:\Users\Public\Documents\RAD Studio\9.0\Dcp"
    CEF4Delphi_designtime.dpk
[DCC Fatal Error] CEF4DelphiFMXRTL.dpk(34): E2202 Required package 'fmx'
not found
[DCC Fatal Error] CEF4Delphi_designtime.dpk(36): E2202 Required package
'CEF4DelphiFMXRTL' not found
Failed
Elapsed time: 00:00:00.7

Thank you
João Carlos


Em ter., 26 de abr. de 2022 às 07:22, Salvador Díaz Fau <
***@***.***> escreveu:

**Comment by bemgiz** [comment]
The instalation is Ok but anyone demo works. Each one have a problem.

Thank you, I will search another solution.


João Carlos

Em ter., 26 de abr. de 2022 às 14:22, Salvador Díaz Fau <
***@***.***> escreveu:
