### ISSUE TITLE
Custom path for libraries/dependencies

### ISSUE THREAD

**Issue by chmichael** [salvadordf/CEF4Delphi#419]
Hello,
  Currently we have to place the "dll dependencies"  within our app folder.
  Can you add a Path variable do define where to search those dependencies in order to be more clean ?

eg chromiumlibs := 'c:\mychromiumlibs';

Thank you

**Comment by salvadordf** [comment]
Hi,

Set the path to the CEF binaries using GlobalCEFApp.FrameworkDirPath, GlobalCEFApp.ResourcesDirPath and GlobalCEFApp.LocalesDirPath before the GlobalCEFApp.StartMainProcess call as you can see here : 
https://github.com/salvadordf/CEF4Delphi/blob/959d152d9c5ca7420c9eed3ac73e4226cd034e6f/demos/Delphi_VCL/SimpleBrowser2/SimpleBrowser2.dpr#L65

**Comment by salvadordf** [comment]
I forgot to add that in case your application is executed from another application you should set GlobalCEFApp.SetCurrentDir to True.

**Comment by chmichael** [comment]
Thank you
