### ISSUE TITLE
Printing diferent components that are in the area of CEFWWindowParent when taking snapshot

### ISSUE THREAD

**Issue by afeliuNexus** [salvadordf/CEF4Delphi#420]
When I want to use TakeSnapshot of a chromium also prints elements that are in the same area of the CEFWindowParent and even I change visisbility of those components like buttons, text area, etc

**Comment by salvadordf** [comment]
The TChromium.TakeSnapshot function uses BitBlt to take the browser screenshot. This function works as long as you don't enable the hardware acceleration but I would suggest that you use the **Page.captureScreenshot** DevTools method as you can see in the MiniBrowser demo : 
https://github.com/salvadordf/CEF4Delphi/blob/983ed5d1d2b406c86b6c660455a44f34c496c6c6/demos/Delphi_VCL/MiniBrowser/uMiniBrowser.pas#L1392
https://github.com/salvadordf/CEF4Delphi/blob/983ed5d1d2b406c86b6c660455a44f34c496c6c6/demos/Delphi_VCL/MiniBrowser/uMiniBrowser.pas#L1468

Read this for more details about the Page.captureScreenshot method : 
https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot

If you want to remove the scrollbars from the screenshots you can add this before the GlobalCEFApp.StartMainProcess call in the DPR file : 
`GlobalCEFApp.BlinkSettings := 'hideScrollbars';`
https://github.com/salvadordf/CEF4Delphi/blob/983ed5d1d2b406c86b6c660455a44f34c496c6c6/demos/Delphi_VCL/ConsoleBrowser2/uEncapsulatedBrowser.pas#L151

Use this if you try to hide HTML elements before printing : 
https://www.geeksforgeeks.org/how-to-hide-an-element-when-printing-a-web-page-using-css/

Please, use our forum for more questions related to browser settings : 
https://www.briskbard.com/forum/
