### ISSUE TITLE
Delphi 11

### ISSUE THREAD

**Issue by sergiokawahara** [salvadordf/CEF4Delphi#423]
---------------------------
Error
---------------------------
Cannot load package 'CEF4DelphiVCLRTL.'  It contains unit 'uCEFCommandHandler', which is also contained in package 'CEF4Delphi'.
---------------------------
OK   
---------------------------

**Comment by sergiokawahara** [comment]
Resolvido....

**Comment by salvadordf** [comment]
If you used CEF4Delphi.dpk to install CEF4Delphi and later you decided that you needed the FMX components too then you have to uninstall CEF4Delphi.dpk, restart delphi and then install CEF4Delphi_group.groupproj.
