### ISSUE TITLE
Redirecting itself to about:blank.

### ISSUE THREAD

**Issue by paulolezak** [salvadordf/CEF4Delphi#424]
lately the component is redirecting itself to about:blank.

Leave the current page for no apparent reason.

**Comment by salvadordf** [comment]
If the render process crashes the browser shows a white screen.

Enable the log [like this](https://github.com/salvadordf/CEF4Delphi/blob/337cabaa18bebec7a9f20560cccd6e62ee8fa13b/demos/Delphi_VCL/MiniBrowser/uMiniBrowser.pas#L314) : 
`  GlobalCEFApp.LogFile             := 'debug.log';

  GlobalCEFApp.LogSeverity         := LOGSEVERITY_INFO;`

You can also implement the TChromium.OnRenderProcessTerminated event to see if the render process crashed.

If you can't see anything relevant in the log and TChromium.OnRenderProcessTerminated is not triggered then provide some code to reproduce this issue in my computer.
