### ISSUE TITLE
CopyCEFDlls swiftshader folder not found

### ISSUE THREAD

**Issue by fraurino** [salvadordf/CEF4Delphi#425]
⚠️ **swiftshader** folder is being required by tools, but **version 102.0.10**, the folder no longer exists, but the dll libEGL.dll and libGLESv2.dll that made the swiftshader folder, is in the previous folder, release.
👍 **solved** by commenting out the lines of code referring to the swiftshader folder;

  {
  if not DirectoryExists(GetRootDir + '\Release\swiftshader') then
  begin
    AddLog('\Release\swiftshader directory does not exist');
    exit;
  end;
  }

//CopyFilesToFolder('\Release\swiftshader', DestDir, '\swiftshader', CopyCount, ErrorCount);

**Comment by salvadordf** [comment]
The latest update includes your fix. 
Thank you very much! :)
