### ISSUE TITLE
The language combinator is displayed. 

### ISSUE THREAD

**Issue by sojimara** [salvadordf/CEF4Delphi#426]
Hello.

The MiniBrowser sample displays the language combinator.

It is not visible in the Chrome browser.

I am using CEF 102.0.9
![image](https://user-images.githubusercontent.com/8443912/175465008-3cbf684a-ec6e-413e-9ad0-292c19d8d500.png)

**Comment by salvadordf** [comment]
Hi，

Please download the official CEF sample application from [here](https://cef-builds.spotifycdn.com/cef_binary_102.0.10%2Bgf249b2e%2Bchromium-102.0.5005.115_windows64_client.tar.bz2) and test this issue again.

There are some unresolved issues in CEF with the IME and this could be one of them.

**Comment by sojimara** [comment]
hi salvadordf.

It was tested in several versions of CEF.

It worked fine in CEF 98.2.1 version

![image](https://user-images.githubusercontent.com/8443912/175839813-4a7d2685-0e9d-461c-9e97-428bed44be73.png)
![image](https://user-images.githubusercontent.com/8443912/175839825-f4962677-2410-4f9d-b2b8-90f7a5df4d01.png)
![image](https://user-images.githubusercontent.com/8443912/175839835-926ca94a-304d-493e-a9da-a3a454363815.png)
![image](https://user-images.githubusercontent.com/8443912/175839841-73a15305-244d-415d-ad01-033492879b9c.png)
![image](https://user-images.githubusercontent.com/8443912/175839848-f9d74f97-0508-48ac-ae5c-08ac08a1b882.png)

**Comment by uniho** [comment]
> Hi，
> 
> Please download the official CEF sample application from [here](https://cef-builds.spotifycdn.com/cef_binary_102.0.10%2Bgf249b2e%2Bchromium-102.0.5005.115_windows64_client.tar.bz2) and test this issue again.
> 
> There are some unresolved issues in CEF with the IME and this could be one of them.

Hi,
As far as I tested, also the official CEF sample cause the same issue on Windows 10 with Microsoft's Japanese IME.

**Comment by salvadordf** [comment]
Related CEF issues : 
https://bitbucket.org/chromiumembedded/cef/issues/3306/windows-ime-not-positioned-correctly-with
https://bitbucket.org/chromiumembedded/cef/issues/3313/windows-fix-ime-popup-and-selection-issues

**Comment by sxmxta** [comment]
latest version has solved this problem
