### ISSUE TITLE
Delphi XE compile problem.

### ISSUE THREAD

**Issue by grig27** [salvadordf/CEF4Delphi#43]
In Delphi XE any units compile problem.

uCEFMiscFunctions.pas

- "UITypes" unit not found in this XE. Change to "Controls".

uCEFDragAndDropMgr.pas

- System.AnsiStrings change to AnsiStrings at function TCEFDragAndDropMgr.HtmlToCFHtml, procedure TCEFDragAndDropMgr.CFHtmlToHtml.

uHelloScheme.pas

- function THelloScheme.ProcessRequest - FStream.WriteData not found in Delphi XE rewrite this...

uSimpleTextViewer.pas

- uses block change to 

  {$IFDEF DELPHI16_UP}
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, Vcl.StdCtrls
  {$ELSE}
  Forms, Classes, Windows, SysUtils, Controls, StdCtrls
  {$ENDIF}
  ;

**Comment by salvadordf** [comment]
Thanks! I'll modify them as soon as possible.
