### ISSUE TITLE
DCPcrypt retired - Link broken - searching for latest

### ISSUE THREAD

**Issue by PizzaProgram** [salvadordf/CEF4Delphi#431]
Tried to install latest stable package v102.0.10 for Lazarus and it demands **DCPcrypt** package preinstalled.  

Looking at the link on the main page (Readme.md file), realized: that link is dead.  
The ["main page"](https://cityinthesky.co.uk/opensource/) still exists, where the author says:

> _Sadly due to time constraints (and the fact that I don’t use the related platforms any more) both DCPcrypt and confluence-mathjax have been retired._   

Lazarus Online-package manager shows a 2.0.4.1 version from 2016-10-27 
If I [search here on github](https://github.com/search?q=dcpcrypt) I see some 2.1 versions, but mostly **without** Lazarus package.

## What is the recommended DCPcrypt package for Lazarus to use CEF4Delphi with?

**Comment by salvadordf** [comment]
Use the package from the Online Package Manager. 
Select "dcpcrypt_laz" inside the DCPCrypt package and then click on the "Install" button.

**Comment by PizzaProgram** [comment]
That wasn't my question. As I've already wrote:
> Lazarus Online-package manager shows a 2.0.4.1 version from 2016-10-27

- Did you read what I've asked?
- The link is still not fixed.

**Comment by salvadordf** [comment]
The recommended DCPcrypt package for Lazarus is the one on the Online Package Manager.
