### ISSUE TITLE
Links "<a href=" not working

### ISSUE THREAD

**Issue by jocasousa** [salvadordf/CEF4Delphi#432]
Hello, I have a bug, my page does not open any link "<a href=..."

I tested it in all browsers and it opens normally, only in CEF4Delphi these links do not work.

**Comment by salvadordf** [comment]
Hi,

Please provide an example to test this issue in my computer.

Most of the demos block links that open new tabs and popup windows for simplicity. Test your links using the MiniBrowser demo.

**Comment by jocasousa** [comment]
Thanks! I tested with minibrowser and my links worked, I was using Simple Browser.

Thank you so much again!
