### ISSUE TITLE
About text and input issues on MacOS and Linux.

### ISSUE THREAD

**Issue by sxmxta** [salvadordf/CEF4Delphi#435]
- In both the BrowserWindow and ExternalPumpBrowser examples on MacOS, I couldn't select text in the HTML page, nor could I copy, paste, and select all text.
- They all behave normally on Windows.
- In Linux, you can select text and copy text normally, but you cannot enter Chinese in Linux.

- Test versions 105.3.39 and 103.0.5060

**Comment by salvadordf** [comment]
There are some issues in CEF with the IME in Linux and we have to wait until the CEF project fixes them.

About the macOS issues I'll have to ask for some favors in order to fix them because I don't have a Mac.
