### ISSUE TITLE
Failed to load LibCef.dll on Windows

### ISSUE THREAD

**Issue by andreysisplan** [salvadordf/CEF4Delphi#439]
When starting an application that uses CEF4Delphi, Windows crashes when trying to load LibCef.dll and the application closes.

Note the attachment:
![libcef](https://user-images.githubusercontent.com/74619882/194052499-55f42b4a-3b58-4421-8300-d7567fe08dc5.jpeg)

**Comment by salvadordf** [comment]
Can you provide more details about that computer, operating system and some code to reproduce that error in my computer?

**Comment by andreysisplan** [comment]
> Can you provide more details about that computer, operating system and some code to reproduce that error in my computer?

Yes, OS and computer configuration can be seen in the following image.
![Computador](https://user-images.githubusercontent.com/74619882/194274538-9477bb60-66ef-4a3b-a598-e8b0b88e2cbf.jpg)

We are developing an integration with WhatsApp through the WPP4Delphi component (https://github.com/wppconnect-team/WPP4Delphi).
We just initialize the GlobalCEFApp.StartMainProcess

**Comment by salvadordf** [comment]
I just installed the evaluation version of Windows 2019 Standard 64 bits on a virtual machine. I run Windows Update several times until it reported that it's fully updated.

I also installed Lazarus and the latest version of CEF4Delphi to try several demos and all of them worked correctly.

Please check that you are using the right files from the CEF binaries. Copy the contents of the "Release" and "Resources" directories from the CEF binaries package.

**Comment by andreysisplan** [comment]
I noticed that a structure is repeatedly created in the Windows Temp folder.
![chrome_bits](https://user-images.githubusercontent.com/74619882/195566729-4d4396ba-48e5-4621-a3e1-c4e4abe91e95.gif)

When opening this chrome extension, I realized that it is about **_Widevine_**

But I still haven't figured out how to prevent or fix it.

**Comment by salvadordf** [comment]
This should not be necessary but try adding this code line before the GlobalCEFApp.StartMainProcess in the DPR file to disable the automatic Widevine component update : 
`GlobalCEFApp.DisableComponentUpdate := True;`

Also check that the Windows user executing your application has write privileges in the cache directory.

**Comment by andreysisplan** [comment]
> GlobalCEFApp.DisableComponentUpdate := True;

It worked that way.
Thank you very much for your helpfulness!

Last question: Could this configuration result in any additional issues?
