### ISSUE TITLE
TCefGetGeolocationCallbackOwn example.

### ISSUE THREAD

**Issue by grig27** [salvadordf/CEF4Delphi#44]
Please... Make example for TCefGetGeolocationCallbackOwn...

**Comment by salvadordf** [comment]
I'll create a demo as soon as I can.

**Comment by salvadordf** [comment]
I just uploaded a new demo with a TCefGetGeolocationCallbackOwn example. It's called "Geolocation".
I implemented the class and callback function but I haven't read anything about this geolocation functionality.
It shows location data in the status bar but I should read all the documentation to be sure.
If this needs to be tested in a laptop I won't be able to test it.

**Comment by salvadordf** [comment]
CEF3 no longer supports Geolocation.
