### ISSUE TITLE
Width & Height of rendered HTML

### ISSUE THREAD

**Issue by hafedh-trimeche** [salvadordf/CEF4Delphi#444]
Hello,

Please how to extract full Width & Height of the rendered HTML?

Best regards.

**Comment by salvadordf** [comment]
Hi,

You need to execute JavaScript to get those values and then send them to Delphi using a console message or registering a JavaScript extension. See the [DOMVisitor](https://github.com/salvadordf/CEF4Delphi/tree/master/demos/Delphi_VCL/DOMVisitor) and [JSExtension](https://github.com/salvadordf/CEF4Delphi/tree/master/demos/Delphi_VCL/JavaScript/JSExtension) demos.

These are some search results for "_how to get page size in javascript_" : 
https://stackoverflow.com/questions/3437786/get-the-size-of-the-screen-current-web-page-and-browser-window
https://stackoverflow.com/questions/1145850/how-to-get-height-of-entire-document-with-javascript
https://stackoverflow.com/questions/58099664/how-to-get-full-page-height-with-javascript
