### ISSUE TITLE
Extract response from session 0 (Service) problem

### ISSUE THREAD

**Issue by hafedh-trimeche** [salvadordf/CEF4Delphi#445]
Hello,

Please note that when running this executable (https://github.com/wanips7/SyncCEFBrowser) from a session 0 (Service) no output is generated!

Opening a user session and executing the application, the response text is generated.

Best regards.

**Comment by salvadordf** [comment]
Hi,

I'm not an expert in Windows Services but after searching for more details about creating a CEF browser from a service it seems that it could be possible if we use a browser in OSR mode.

I would probably try to use a different EXE for the CEF subprocesses and use part of the code from the [ConsoleBrowser2](https://github.com/salvadordf/CEF4Delphi/tree/master/demos/Delphi_VCL/ConsoleBrowser2) or [WebpageSnapshot](https://github.com/salvadordf/CEF4Delphi/tree/master/demos/Delphi_VCL/WebpageSnapshot) demos.

I might try to create a _WindowsServiceBrowser_ demo in the future. Thanks for the suggestion!

**Comment by hafedh-trimeche** [comment]
Thank you for proposing creation of  a WindowsServiceBrowser demo.

**Comment by salvadordf** [comment]
I'll keep this issue open as a reminder ;)

**Comment by salvadordf** [comment]
Download the latest CEF4Delphi version and see the new Delphi_VCL\WindowsServiceBrowser demo
