### ISSUE TITLE
Load X509 Certificate memory certificate

### ISSUE THREAD

**Issue by fneto-dev** [salvadordf/CEF4Delphi#447]
Is possible to load x509 certificate from file (.cer/.pfx) or stream?

**Comment by salvadordf** [comment]
The CEF API doesn't allow you to load a custom certificate. 

Chromium allows you to authenticate the user with the TChromiumCore.OnSelectClientCertificate event where you can show a certificate list and let the user select which one to use or select one automatically from a list of certificates that the server could accept. See the TMiniBrowserFrm.Chromium1SelectClientCertificate procedure in the MiniBrowser demo for all the details.

Read [these code comments](https://bitbucket.org/chromiumembedded/cef/src/400fbf78399986dc3ac4c6acf25953a5496617b3/include/capi/cef_request_handler_capi.h#lines-195) about that event.

Please, use our forums for more questions.
https://www.briskbard.com/forum/
