### ISSUE TITLE
DXVA2.DLL not found on Server 2022 Core

### ISSUE THREAD

**Issue by hafedh-trimeche** [salvadordf/CEF4Delphi#448]
Hello,

Is there a way to avoid loading **DXVA2.DLL** on **Server 2022 Core**?

https://magpcss.org/ceforum/viewtopic.php?t=17718

Best regards.

**Comment by salvadordf** [comment]
I don't have Windows Server Core and I can't test this but the last message in that forum thread seems to have the solution.
https://magpcss.org/ceforum/viewtopic.php?f=6&t=17718&sid=feee8df85ac546a8cc209593a9f86710&start=10#p46195

Install the missing components on server core operating systems. Open a PowerShell console as administrator and execute this command : 
`Add-WindowsCapability -Online -Name ServerCore.AppCompatibility~~~~0.0.1.0`
Then restart Windows.

Read this article for more information : 
https://learn.microsoft.com/en-us/windows-server/get-started/server-core-app-compatibility-feature-on-demand
