### ISSUE TITLE
How to  Set  the cef4delphi Print Options?

### ISSUE THREAD

**Issue by jfhyn** [salvadordf/CEF4Delphi#45]
Hi
How to Set Print Options like  Set PDF options?
for example : Chromium1.PDFPrintOptions.backgrounds_enabled :=1;
thanks.

**Comment by salvadordf** [comment]
The full details to set the PDF print settings are in the CEF3 source comments inside the /include/internal/cef_types.h file or here : 
https://bitbucket.org/chromiumembedded/cef/src/85c945bc0070a54773c6702226bcf413fa61e850/include/internal/cef_types.h?at=master&fileviewer=file-view-default

Search for the _cef_pdf_print_settings_t struct.

**Comment by jfhyn** [comment]
oh,
I mean  I want to set print  options.
but cef4delphi  Only has "print" method  but not find "print options".

**Comment by salvadordf** [comment]
At this moment CEF3 only allows to set print options to Linux users.

The printer settings are used by the printer handler, and the printer handler is only used in Linux as you can see here : 
https://bitbucket.org/chromiumembedded/cef/src/85c945bc0070a54773c6702226bcf413fa61e850/include/capi/cef_print_handler_capi.h?at=master&fileviewer=file-view-default

**Comment by jfhyn** [comment]
oh,I See.
thank you very much!
