### ISSUE TITLE
A small problem with MacOS

### ISSUE THREAD

**Issue by sxmxta** [salvadordf/CEF4Delphi#450]
@salvadordf 
    Hello. 
---
I want to achieve a frameless window area that can be dragged under MacOS.
Under Windows, I can use OnRenderCompMsg to observe the mouse area.
---
But I haven't found a suitable method in MacOS. How can I use similar events in MacOS? NSView.hitTest, I don't know where to use it. Or is there any other way to achieve it?
---
thank you!
---

**Comment by salvadordf** [comment]
Hi,

I'm not a macOS expert and I don't have a Mac, but I would try to use the off-screen rendering mode, also known as "OSR mode". 

That mode allows you to use the normal mouse events in the buffer panel : OnMouseMove, OnMouseEnter, OnMouseLeave, OnMouseUp, OnMouseDown, etc.

The Delphi demo for macOS already uses this mode and one of the demos for any OS also use this mode.

Please, use our forum for more questions : 
https://www.briskbard.com/forum/
