### ISSUE TITLE
2023 how use flash

### ISSUE THREAD

**Issue by 839781960** [salvadordf/CEF4Delphi#453]
2023 how use flash
which version？

**Comment by salvadordf** [comment]
[Adobe announced that Flash is no longer supported](https://www.adobe.com/products/flashplayer/end-of-life.html) and they even recommend uninstalling it.

Google removed Flash support in [Chromium 88](https://www.chromium.org/flash-roadmap)

[This was last CEF4Delphi release](https://github.com/salvadordf/CEF4Delphi/releases/tag/87.0.4280.141) that supported Flash.
