### ISSUE TITLE
PrintToPDF (portrait and landscape)

### ISSUE THREAD

**Issue by xelnaga64** [salvadordf/CEF4Delphi#455]
I use Chromium1.PrintToPDF(filename) to save the page as PDF file. Is it possible to choose portrait or landscape modes?

**Comment by salvadordf** [comment]
Yes. Add this line before the PrintToPDF call : 
`Chromium1.PDFPrintOptions.Landscape := True;`

Please, use our forums for more questions : 
https://www.briskbard.com/forum/
