### ISSUE TITLE
NetfreeAadJoininformation not found in libcef.dll

### ISSUE THREAD

**Issue by WalterDeb** [salvadordf/CEF4Delphi#456]
Hi!

I use Version 110.0.31.0 - it works on Windows Version 10.

On Windows Server 2012 or Windows 8.1 pro i get - see Screenshots.

![2023-04-12_090034](https://user-images.githubusercontent.com/130540636/231377517-6c0766cb-cc46-4859-bb90-1a211511cc6f.png)

![2023-04-12_090055](https://user-images.githubusercontent.com/130540636/231377608-9ce0132a-1e77-449f-b7f9-85e933296fbb.png)

Any ideas how to fix that?

Thanks
Walter

**Comment by salvadordf** [comment]
Hi,

This is the same issue as #452 

Google added new requirements and now you need Windows 10 to run the latest version of Chromium. Read the likened announcement in the other issue for more information.
