### ISSUE TITLE
you cannot enter Chinese in Linux.

### ISSUE THREAD

**Issue by jwj76** [salvadordf/CEF4Delphi#459]
In Linux,  you cannot enter Chinese in Linux.
In Linux, it is not possible to input Chinese characters directly. It seems that cef4delphi intercepts keyboard input. Even after bringing up the Chinese input method, the keyboard input is still in English and is not first processed by the operating system's input method.
Test versions 109.0.5414.120  111.0.5563.148

**Comment by salvadordf** [comment]
There are [several open issues](https://github.com/chromiumembedded/cef/issues?q=is%3Aissue+is%3Aopen+chinese+) in CEF about the IME and the Chinese language.

Please, test this issue with the official [CEF sample application](https://cef-builds.spotifycdn.com/cef_binary_112.3.0%2Bgb09c4ca%2Bchromium-112.0.5615.165_linux64_client.tar.bz2) and post the results.

**Comment by jwj76** [comment]
When running cefsimple --multi-threaded-message-loop --no-sandbox --off-screen-rendering-enabled --enable-gpu, it is possible to input Chinese characters. However, after compiling example Lazarus_Linux_GTK2/SimpleBrowser in Lazarus, I am unable to input Chinese characters.

**Comment by jwj76** [comment]
How to set up Lazarus to support Chinese input? Could you please give an example?

**Comment by salvadordf** [comment]
I'm not part of the development team of Lazarus. 
Please, post the Lazarus related questions in the [Lazarus forum](https://forum.lazarus.freepascal.org/index.php?action=forum).

**Comment by jwj76** [comment]
Okay, we need to use g_ signal_ Connect to associate key press event, key release event, and commit signals to process the input method.

**Comment by szlbz** [comment]
This is my solution(这是我的解决方案)：
https://www.cnblogs.com/qiufeng2014/p/18684993
