### ISSUE TITLE
DevTools: Console Object Copy to Clipboard is disabled

### ISSUE THREAD

**Issue by jchoover** [salvadordf/CEF4Delphi#461]
This is most certainly an issue on my side, but I am unable to reproduce this issue w/ the Mini Browser, even after applying all my initialization changes to the mini browser.

I am at a loss as to what could possibly change the behavior of the DevTools Console window, and only for attempting to right click on the "i" icon next to an object. Other lines in the console allow you to interact with them. Enabling the remote debugging port and then using a browser to access it via localhost also works.

If I turn on verbose logging I see (for every right click):
[ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Invalid resource type name "undefined"", source: devtools://devtools/panels/sources/sources.js (1)

**Comment by salvadordf** [comment]
Hi,

Perhaps your application uses a browser with a different configuration. 

Try the most similar demo in terms of browser configuration to your application.

In any case, I would need some minimal code to reproduce this issue in my computer.

If you don't mind, lets move this discussion to [our forum](https://www.briskbard.com/forum/).
