### ISSUE TITLE
CEF4Delphi version is 87.0.4280.141, loading Flash error

### ISSUE THREAD

**Issue by jwj76** [salvadordf/CEF4Delphi#463]
Use this to load

GlobalCEFApp.AddCustomCommandLine('--register-pepper-plugins','./libpepflashplayer.so ;application/x-shockwave-flash');

If GlobalCEFApp. NoSandbox:=true; Error reported as NOT SANDBOXED

If GlobalCEFApp. NoSandbox:=False; Error reported as [WARNING: flash/platform/pepper/pep_module.cpp (63)] SANDBOXED

The above cannot display Flash files properly.

May I ask how to handle it?

**Comment by salvadordf** [comment]
CEF 87 is extremely old and unsupported. Flash and  is also deprecated. 

If you still want to use the Flash plugin you can set the GlobalCEFApp.CustomFlashPath property as you can see [here](https://www.briskbard.com/forum/viewtopic.php?f=8&t=1693)

Please, use [our forum](https://www.briskbard.com/forum/) for more questions.
