### ISSUE TITLE
How to upload file without OpenFileDialog shown

### ISSUE THREAD

**Issue by xsfhacg** [salvadordf/CEF4Delphi#467]
In versions before 100, the Chromium1FileDialog method [callback. Font (selectedAcceptFilter: Integer; const filePaths: TStrings)] can directly add selected images without opening the file selection box. However, in version 102, the selectedAcceptFilter parameter is no longer present. How can we achieve the original function of directly returning selected images without opening the file selection box?

**Comment by xsfhacg** [comment]
![image](https://github.com/salvadordf/CEF4Delphi/assets/41864243/264c63f6-5e59-46a7-84b2-410a576a4b7e)

**Comment by salvadordf** [comment]
This is the current documentation for [ICefDialogHandler](https://cef-builds.spotifycdn.com/docs/114.2/classCefDialogHandler.html#a099ef54f885bce31438094d4dbb335e9) and [ICefFileDialogCallback](https://cef-builds.spotifycdn.com/docs/114.2/classCefFileDialogCallback.html#ac706e7ab01ff57ea4c95eba9a8b70662).

Please, update to the latest CEF4Delphi version and use the code from the MiniBrowser demo but remove the TempDialog.Execute call. Just add the file paths and call the ICefFileDialogCallback.cont function with the file paths.

**Comment by xsfhacg** [comment]
> 

【I used to do this in my previous version of CEF93, but after upgrading to CEF102, running Win64 bit to return existing images is no longer possible. Here is my code】：

procedure TFrameBaseWebBrowser.Chromium1FileDialog(Sender: TObject;
  const browser: ICefBrowser; mode: Cardinal;
  const title, defaultFilePath: ustring;
  const acceptFilters: TStrings; selectedAcceptFilter: Integer;
  const callback: ICefFileDialogCallback;
  out Result: Boolean);
var
  I: Integer;
  ATempFilePath:String;
var
  AFiles:TStringList;
begin
  uBaseLog.HandleException('TFrameFacebookWebSearchAPI.Chromium1FileDialog Begin');
  if FContentFiles.Count > 0 then
  begin
    AFiles:=TStringList.Create;
    uBaseLog.HandleException('TFrameFacebookWebSearchAPI.Chromium1FileDialog '
                           + ' title:' + title
                           + ' defaultFilePath:' + defaultFilePath
                           + ' acceptFilters:' + acceptFilters.Text
                           + ' selectedAcceptFilter:' + IntToStr(selectedAcceptFilter));
    try
      //如果是链接,则先下载再添加
      for I := 0 to FContentFiles.Count-1 do
      begin
        if SameText(Copy(FContentFiles[I],1,7),'http://')
        or SameText(Copy(FContentFiles[I],1,8),'https://') then
        begin
          ATempFilePath:=//System.IOUtils.TPath.GetTempPath()+
                          System.IOUtils.TPath.GetTempFileName()
                          +ExtractFileExt(GetFileNameFromUrl(FContentFiles[I]))
                          ;
          if uBaseHttpControl.DownloadImage(FContentFiles[I],ATempFilePath) then
          begin
            AFiles.Add(ATempFilePath);
          end;
        end
        else
        begin
          AFiles.Add(FContentFiles[I]);
        end;
      end;
  //    AFiles.Add('C:\Users\Administrator\Desktop\你很弱.jpg');
  //    AFiles.Add('C:\Users\Administrator\Desktop\傲途演示视频.mp4');
  //    AFiles.Add('C:\Users\Administrator\Desktop\不要.jpg');
      uBaseLog.HandleException('【已选媒体】：' + AFiles.CommaText);
      {$IFDEF CPUX64}
        callback.Cont(AFiles);
      {$ELSE}
        callback.Cont(selectedAcceptFilter, AFiles);
      {$ENDIF}
      Result := True;
    finally
      FreeAndNil(AFiles);
    end;
  end;
  uBaseLog.HandleException('TFrameFacebookWebSearchAPI.Chromium1FileDialog End');
end;

**Comment by xsfhacg** [comment]
> This is the current documentation for [ICefDialogHandler](https://cef-builds.spotifycdn.com/docs/114.2/classCefDialogHandler.html#a099ef54f885bce31438094d4dbb335e9) and [ICefFileDialogCallback](https://cef-builds.spotifycdn.com/docs/114.2/classCefFileDialogCallback.html#ac706e7ab01ff57ea4c95eba9a8b70662).
> 
> Please, update to the latest CEF4Delphi version and use the code from the MiniBrowser demo but remove the TempDialog.Execute call. Just add the file paths and call the ICefFileDialogCallback.cont function with the file paths.

> 

【I used to do this in my previous version of CEF93, but after upgrading to CEF102, running Win64 bit to return existing images is no longer possible. Here is my code】：

`procedure TFrameBaseWebBrowser.Chromium1FileDialog(Sender: TObject;
  const browser: ICefBrowser; mode: Cardinal;
  const title, defaultFilePath: ustring;
  const acceptFilters: TStrings; selectedAcceptFilter: Integer;
  const callback: ICefFileDialogCallback;
  out Result: Boolean);
var
  I: Integer;
  ATempFilePath:String;
var
  AFiles:TStringList;
begin
  uBaseLog.HandleException('TFrameFacebookWebSearchAPI.Chromium1FileDialog Begin');
  if FContentFiles.Count > 0 then
  begin
    AFiles:=TStringList.Create;
    uBaseLog.HandleException('TFrameFacebookWebSearchAPI.Chromium1FileDialog '
                           + ' title:' + title
                           + ' defaultFilePath:' + defaultFilePath
                           + ' acceptFilters:' + acceptFilters.Text
                           + ' selectedAcceptFilter:' + IntToStr(selectedAcceptFilter));
    try
      //如果是链接,则先下载再添加
      for I := 0 to FContentFiles.Count-1 do
      begin
        if SameText(Copy(FContentFiles[I],1,7),'http://')
        or SameText(Copy(FContentFiles[I],1,8),'https://') then
        begin
          ATempFilePath:=//System.IOUtils.TPath.GetTempPath()+
                          System.IOUtils.TPath.GetTempFileName()
                          +ExtractFileExt(GetFileNameFromUrl(FContentFiles[I]))
                          ;
          if uBaseHttpControl.DownloadImage(FContentFiles[I],ATempFilePath) then
          begin
            AFiles.Add(ATempFilePath);
          end;
        end
        else
        begin
          AFiles.Add(FContentFiles[I]);
        end;
      end;
  //    AFiles.Add('C:\Users\Administrator\Desktop\你很弱.jpg');
  //    AFiles.Add('C:\Users\Administrator\Desktop\傲途演示视频.mp4');
  //    AFiles.Add('C:\Users\Administrator\Desktop\不要.jpg');
      uBaseLog.HandleException('【已选媒体】：' + AFiles.CommaText);
      {$IFDEF CPUX64}
        callback.Cont(AFiles);
      {$ELSE}
        callback.Cont(selectedAcceptFilter, AFiles);
      {$ENDIF}
      Result := True;
    finally
      FreeAndNil(AFiles);
    end;
  end;
  uBaseLog.HandleException('TFrameFacebookWebSearchAPI.Chromium1FileDialog End');
end;`

**Comment by salvadordf** [comment]
The CEF project removed the selectedAcceptFilter parameter. 
Remove all instances of selectedAcceptFilter from your code. 
Remove it from the event parameters too.

Please, use [our forum](https://www.briskbard.com/forum/) for more questions.

**Comment by xsfhacg** [comment]
> The CEF project removed the selectedAcceptFilter parameter. Remove all instances of selectedAcceptFilter from your code. Remove it from the event parameters too.
> 
> Please, use [our forum](https://www.briskbard.com/forum/) for more questions.

OK，I will use the forum. But when I double-click on the OnFileDialogue event of the Chromium component on the interface, its automatically generated method still has the parameter selectedAcceptFilter. If it is deleted, it will prompt [Property and method Chromium1FileDialogue are not compatible.]
