### ISSUE TITLE
Can you help compile a binary

### ISSUE THREAD

**Issue by jwj76** [salvadordf/CEF4Delphi#469]
Can you help compile a binary that Chromium87.0.4280.141 can run under LInuxARM64? Currently, the PAGESIZE of files such as libcef.so is 4K, while the PAGESIZE of most LInuxARM64 is 64K. Thank you!

**Comment by salvadordf** [comment]
There's a tutorial to build the Windows CEF binaries [here](https://www.briskbard.com/forum/viewtopic.php?f=10&t=1097) but it uses the latest CEF version.

I'm not sure if it's possible to build an old version of CEF but the official guides are [here](https://bitbucket.org/chromiumembedded/cef/wiki/AutomatedBuildSetup.md)
