### ISSUE TITLE
Compatibility with DCEF3 ?

### ISSUE THREAD

**Issue by thefunkyjoint** [salvadordf/CEF4Delphi#47]
Hi

Not an issue, but a question : currently i use DCEF3, but it's outdated and seems abandoned. Is this CEF4 compatible with DCEF3 ? If i just uninstall DCEF3 and install CEF4, will my apps still run without need to change my code ?

Thanks !

**Comment by clone147** [comment]
You need to make some changes, but it's worth.

**Comment by salvadordf** [comment]
Hi,

Please read this : https://www.briskbard.com/index.php?lang=en&pageid=cef

CEF4Delphi is based on DCEF3 but you'll need to make some changes. If you need Windows XP or Vista compatibility you can't use CEF4Delphi.
