### ISSUE TITLE
Use OldCef4 and Eurekalog then meet an error

### ISSUE THREAD

**Issue by doublesx** [salvadordf/CEF4Delphi#470]
Hello，I used oldCef4 for Delphi and activated Eurekalog as shown in the attachment. When I run the application, an error occurs after the setting time.Can you tell me why this problem occurred and how to solve it？

![1689844182506](https://github.com/salvadordf/CEF4Delphi/assets/52943483/6673641f-e319-4e55-9044-cb387eb06c2b)

Eurekalog message:
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1.1 Start Date : Thu, 20 Jul 2023 17:07:27 +0800
1.2 Name/Description: SimpleOSRBrowser.exe - (SimpleOSRBrowser)
1.3 Version Number : 1.0.0.0
1.4 Parameters : --type=renderer --log-severity=verbose --user-data-dir="C:\Users\D10\AppData\Local\CEF\User Data" --first-renderer-process --no-sandbox --log-file=debug.log --touch-events=enabled --lang=en-US --device-scale-factor=1 --num-raster-threads=1 --renderer-client-id=5 --time-ticks-at-unix-epoch=-1689295619632011 --launch-time-ticks=548427400152 --mojo-platform-channel-handle=2200 --field-trial-handle=1832,i,16897806009432926035,14281575464793666129,131072 --disable-features=BackForwardCache,CalculateNativeWinOcclusion,WinUseBrowserSpellChecker /prefetch:1
1.5 Compilation Date: Thu, 20 Jul 2023 17:07:22 +0800
1.6 Up Time : 1 minute(s), 42 second(s)

Exception:
---------------------------------------------------------
2.1 Date : Thu, 20 Jul 2023 17:09:09 +0800
2.2 Address : 776AF8E1
2.3 Module Name : ntdll.dll - (NT 层 DLL)
2.4 Module Version: 6.1.7601.23864
2.5 Type : EFrozenApplication
2.6 Message : The application seems to be frozen.
2.7 ID : ACCE0621
2.8 Count : 1
2.11 Sent : 0

User:
----------------
3.2 Name : D10
3.3 Email:

Steps to reproduce:
------------
8.1 Text:
![1689844349316](https://github.com/salvadordf/CEF4Delphi/assets/52943483/156cca84-2ed5-448c-9e35-a855d1e35e27)

**Comment by salvadordf** [comment]
Hi,

This is the issue tracker for the CEF4Delphi project only. 

The forum for CEF4Delphi and OldCEF4Delphi developers is this :
https://www.briskbard.com/forum/

Please, move your question to that forum.
