### ISSUE TITLE
ErrorInitializingLibrary appears in Linux_arm64

### ISSUE THREAD

**Issue by jwj76** [salvadordf/CEF4Delphi#472]
Version: 87.0.4280.141

Question:
1. Running the built-in cefsimple is normal.
2. Compile the code in the Lazarus example and run it directly to exit.
3. WriteLn (GlobalCEFApp. Status) displays asErrorInitializingLibrary.
4. In the 'CustomiExceptionHandler' function of 'uCEFMiscFunctions', add
WriteLn(aFunctionName + ' error : ' + aException.message);
Echo
TCefApplicationCore.ExecuteProcess error : Access violation
TCefApplicationCore.InitializeLibrary error : Access violation
5. Compilation target changed to win32_ I386 and Linux_ X86_ 64 is normal and will not display the above error.

**Comment by salvadordf** [comment]
The demos run fine in RaspiOS 64 bit but they fail in Ubuntu 64 bit for RaspberryPi. This is the same issue as [#457](https://github.com/salvadordf/CEF4Delphi/issues/457).
