### ISSUE TITLE
HTML exibe no navegado mas não no CEF

### ISSUE THREAD

**Issue by mjsouza1977** [salvadordf/CEF4Delphi#474]
Utilizo o CEF para exibir um mapa do google e derepente da noite para o dia simplesmente o mapa não é exibido, até voltado o sistema em versões anteriores.

Segue o link do arquivo que estamos tendo problemas: https://drive.google.com/file/d/1xaLWndd6pdnDIYdgcGbINkA2WxvC9Jku/view?usp=sharing

**Comment by salvadordf** [comment]
Please, use English or Spanish. Use [our forum](https://www.briskbard.com/forum/) for questions regarding third party APIs.
