### ISSUE TITLE
Unsupported CEF version - libcef.dll

### ISSUE THREAD

**Issue by edmund5** [salvadordf/CEF4Delphi#478]
Downlaoded the latest libraries from spotify:

![image](https://github.com/salvadordf/CEF4Delphi/assets/299803/6e0ec10b-61be-407a-8c12-d51a892cdedf)

**Comment by salvadordf** [comment]
Hi,

That error message says that Delphi is using an old version of CEF4Delphi but the CEF binaries are new.

If you want to keep using the old version of CEF4Delphi then you need to download the CEF binaries using the links in the readme.md file for that version.
https://github.com/salvadordf/CEF4Delphi/releases/tag/99.0.4844.84

However, if you want to use the latest CEF4Delphi version then you need to download it from GitHub and reinstall the component following the installation steps available in the Wiki page.
https://github.com/salvadordf/CEF4Delphi/archive/refs/heads/master.zip
https://github.com/salvadordf/CEF4Delphi/wiki/Installation-in-Delphi
https://github.com/salvadordf/CEF4Delphi/wiki/Installation-in-Lazarus-FPC
