### ISSUE TITLE
Crashes immediately, All Demos Running FLASH on facebook (Game Playing) 

### ISSUE THREAD

**Issue by royalsysop** [salvadordf/CEF4Delphi#48]
I am developing with Delphi XE4 . Version 3071.1645 was the last version that worked. All branches afterwards (including current) will allow me to login to facebook then a few seconds later, it dies if i enable flash. 
exception class $COOOOOO5 access violation at 0x5c950171 read of address 0x00000008
(libcef.dll)
CEF		3.3112.1655.gd97fbff
Chromium	60.0.3112.90
OS		Windows
WebKit		537.36 (@e6ccc355a03184b2a4fa2b22bd15b89324d6a137)
JavaScript	6.0.286.52
Flash		26.0.0.151
User Agent	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
Command Line	"C:\Users\Public\Documents\RAD Studio\11.0\Projects\CEF4Delphi\3112.1655\demos\MiniBrowser\MiniBrowser.exe" 
                 --no-sandbox --lang=en-US --log-file=cef.log 
                 --log-severity=verbose 
                 --resources-dir-path="C:\CEF2\WIN32\Release" 
                 --locales-dir-path="C:\CEF2\WIN32\Release\locales" 
                 --remote-debugging-port=9000 
                 --enable-spelling-service=1 
                 --enable-media-stream=0 
                 --enable-speech-input=1 
                 --enable-system-flash
Module Path	C:\CEF2\WIN32\Release\libcef.dll
Cache Path	

Your browser (BriskBard) works fine.. 
Do I need to add/replace more commandline parms or insert more code to allow "FLASH BASED GAMES" to function right?   

The CEFCLIENT demo works, as well as the Latest CHROME.EXE (same ceflib.dll version).

Attached is the verbose error log... not sure why 3071.1645 runs but not 3112.1649 or 3112.1655..
I can get versions of cef3 (1979)  (2171) (2454) (2704) to ALL WORK.

[ceflog.txt](https://github.com/salvadordf/CEF4Delphi/files/1219359/ceflog.txt)

**Comment by salvadordf** [comment]
Can you post the URL with the flash game that causes the crash?

**Comment by salvadordf** [comment]
This is an old issue that I couldn't reproduce. Please, reopen if someone can provide more details.
