### ISSUE TITLE
Ubuntu 22.04.3 LTS, Lazarus 2.2.6 - package compilation issue

### ISSUE THREAD

**Issue by shinyclaw** [salvadordf/CEF4Delphi#481]
![image](https://github.com/salvadordf/CEF4Delphi/assets/7187363/49250417-9923-4ec1-8520-b103d585f5cf)

The file "uCEFDownLoadItem.pas" has incorrect case for "Load" part. Should be lowercase instead of uppercase.

**Comment by salvadordf** [comment]
Thanks for reporting this issue!

Please remember that the issue #441 don't allow us to run GTK2 demos. Use the GTK3 demos for the moment.
