### ISSUE TITLE
Prevent from opening links in chromium browser?

### ISSUE THREAD

**Issue by edmund5** [salvadordf/CEF4Delphi#483]
How to prevent from opening links as a pop-up within chromium window? because I open it directly to windows default browser (e.g. FireFox)

using

`ShellExecute(0, 'open', PChar(request.Url), nil, nil, SW_SHOWNORMAL);`

**Comment by salvadordf** [comment]
Hi,

Use the TChromiumWindow.ChromiumBrowser.OnBeforePopup event [like this](https://github.com/salvadordf/CEF4Delphi/blob/f9c670210787a85b0461cd30d12ea686087a528b/demos/Delphi_VCL/SimpleBrowser/uSimpleBrowser.pas#L149) and [this](https://github.com/salvadordf/CEF4Delphi/blob/f9c670210787a85b0461cd30d12ea686087a528b/demos/Delphi_VCL/SimpleBrowser/uSimpleBrowser.pas#L182).
