### ISSUE TITLE
Dpi crash on launch

### ISSUE THREAD

**Issue by sebou77** [salvadordf/CEF4Delphi#484]
Hi, here's my problem i code on delphi 10.3, with 4k screen (150% on windows scale). When i launch my app without cef no problem, and when i add : 

  CreateGlobalCEFApp;
  if GlobalCEFApp.StartMainProcess then
  
  my app juste become crazy on 150% windows scale (TImage on alClient take 25% of size, popupmenu appear at random place, etc..), it's keep working on 100% windows scale. Any idea ?

**Comment by salvadordf** [comment]
Hi,

CEF had some issues with the DPI awareness setting as you can see [here](https://github.com/chromiumembedded/cef/issues/3452).

I upgraded my Delphi installation to 11.3 and I can't test the workarounds suggested in that link with Delphi 10.3. 

Open the project settings and click on the "_Application -> Manifest_" section. Try setting "_DPI Awareness_" to "_None_".

Other DPI Awareness values might work too but I can't test them.

Please, post this information in [our forum](https://www.briskbard.com/forum/) if this workaround doesn't work for your application.
