### ISSUE TITLE
how to set multi page to idle status?

### ISSUE THREAD

**Issue by hzmsrv** [salvadordf/CEF4Delphi#485]
when opening multi-page, the browsers run out of my CPU, and every page uses several percent CPU! 
how to set the other pages to idle status?

**Comment by salvadordf** [comment]
Hi,

It depends on the browser configuration. 

Browsers in OSR mode can save some CPU time hiding the browser but normal browsers can only try some experimental properties.

Read [this forum thread](https://www.briskbard.com/forum/viewtopic.php?f=10&t=2005) for more information.
