### ISSUE TITLE
Classes in uCEFTask.pas contain pointers to interfaces of objects that can be destroyed

### ISSUE THREAD

**Issue by mterrisse** [salvadordf/CEF4Delphi#487]
Erratically I have crashes in uCEFTask.pas because pointers point to released objects.
I have an alternative to pointers than works on my projects, see the patch attached.

Regards,

Michel Terrisse
[NoPointerInTasks.patch](https://github.com/salvadordf/CEF4Delphi/files/13206635/NoPointerInTasks.patch)

**Comment by salvadordf** [comment]
Thanks for reporting this issue!

I see some generics in the patch and CEF4Delphi must work with old Delphi versions. I'll try to adapt your suggestions to keep backwards compatibility.

**Comment by salvadordf** [comment]
The latest commit includes an alternative way to fix this issue. 
I had to add the TCEFComponentIdList class for backwards compatibility reasons.
I also had to make several changes to the classes that handle CEF tasks.
