### ISSUE TITLE
about scale 

### ISSUE THREAD

**Issue by Evanchl** [salvadordf/CEF4Delphi#489]
Hi, here's my problem i code on delphi 10.1, with 2k screen (150% on windows scale)
and without Enable-High-DPI
When i launch my app without cef no problem, and when i add :

CreateGlobalCEFApp;
if GlobalCEFApp.StartMainProcess then

the app length and height are only 2/3 of the original size 

How do I solve this problem？
please give me some code to fix it
![Uploading image.png…]()

**Comment by salvadordf** [comment]
Hi,

I can't see the attached screenshot but this seems to be a duplicate if the issue #484

**Comment by Evanchl** [comment]
issue #484 i can not find the answer.
i run DLLBrowser demo
before i click 1. Initialize it's normal
![image](https://github.com/salvadordf/CEF4Delphi/assets/19363096/438bc175-344f-4e71-a54c-4bd4bff370a0)

after i click 1. Initialize ，It has become smaller and form caption disappeared。
![image](https://github.com/salvadordf/CEF4Delphi/assets/19363096/1870f9f9-4282-4c4a-ab5b-3e50b3977508)

![image](https://github.com/salvadordf/CEF4Delphi/assets/19363096/765b2896-170d-41f5-bce3-6798a0cd8fff)

**Comment by salvadordf** [comment]
I tested the DLLBrowser demo again with Delphi 12 in Windows 10 with a 4k monitor using 200% scale and it works correctly.

Please, check that the CEF4DelphiLoader project has the right manifest settings.

Right-click on the "**CEF4DelphiLoader.exe**" node in the "**Projects**" panel and select "_Options_".

Then go to the "_Application -> Manifest_" section and make sure the "_DPI awareness_" option has a "**Per monitor**" value and the "_Manifest File_" option is set to "_Auto Generate_".

**Comment by salvadordf** [comment]
Another workaround: call SetProcessDpiAwareness before loading the CEF.

Similar issue in [stackoverflow](https://stackoverflow.com/questions/77494784/cef4delphi-application-font-size-decreased-after-cef-is-loaded).
