### ISSUE TITLE
How do I load crx plug-ins

### ISSUE THREAD

**Issue by jwj76** [salvadordf/CEF4Delphi#492]
FLASH is not supported in versions later than 87. I want to display Flash as a crx plugin. Now I have downloaded a plug-in of Flash Player Emulator 2023 1.7.1.crx, please tell me how to load this plug-in. thank you

**Comment by salvadordf** [comment]
Try using a browser the "_Chrome runtime_" mode. 

The [TinyBrowser2](https://github.com/salvadordf/CEF4Delphi/tree/master/demos/Delphi_VCL/TinyBrowser2) should work but remember that the Chrome runtime mode is in experimental state.
