### ISSUE TITLE
No-SnedBox False 

### ISSUE THREAD

**Issue by KimK-Hack** [salvadordf/CEF4Delphi#494]
GlobalCEFApp.NoSandbox := False;

chrome://version/ 

Command Line | "C:\TEST\MDIBrowser.exe" --disable-features=EnableHangWatcher --lang=ko-KR --no-sandbox

"--no-sandbox" 

I want to get rid of that.
This is an obstacle for web automation. Even if you check it in uCEFApplicationCore, it will never change even if it dies. I don't even know how to build anything other than Delphi. Everything else goes well and there are no problems. Where on earth do I have to fix it to remove that part? Since the membership registration email is not even sent on the official site, I am posting my question here.

**Comment by salvadordf** [comment]
Please, read [these code comments](https://github.com/chromiumembedded/cef/blob/738192addf1f0d3f713affe033659c64f8dbeaf9/include/cef_sandbox_win.h#L44) in CEF about the sandbox feature.

It's not possible to link the _cef_sandbox.lib_ static library in Delphi applications so we can't enable the sandbox feature.

Chromium appends the "--no-sandbox" command line switch automatically when necessary.

Let me know the forum username and I'll activate your account manually.

**Comment by salvadordf** [comment]
I just added this information to the _Frequently asked questions_ Wiki page.

**Comment by KimK-Hack** [comment]
> --no-sandbox

Thank you for answer. In the end, does Chromium require --no-sandbox? Selinium is not a necessity.
Even if you delete cef_sandbox.lib in the folder, it will connect automatically.

sodlf159

**Comment by salvadordf** [comment]
The user sodlf159 has been activated manually in the forum.

The readme file in the Selenium repository indicates that it requires Visual Studio 2022. That IDE allows linking the static library in C++ projects. 

In any case, many other developers use CEF4Delphi for web automation and it works even with the "--no-sandbox" switch.

If you don't mind, let's continue this conversation in the forum.
