### ISSUE TITLE
Minibrowser Demo Can't Play Video

### ISSUE THREAD

**Issue by nguyennhatdung** [salvadordf/CEF4Delphi#496]
Hi!

Seem tiktok can detect cef and not allow to play video. I just wonder how they detect ? Can we do anything to bypass the check ?

**Comment by salvadordf** [comment]
Hi,

They probably use proprietary codecs in the video or audio.
[Read this](https://www.briskbard.com/index.php?lang=en&pageid=cef#codecs) for more information.

**Comment by nguyennhatdung** [comment]
oh thanks for the info

i'll try build the cef my self then, many thanks
