### ISSUE TITLE
FMX support

### ISSUE THREAD

**Issue by kormizz** [salvadordf/CEF4Delphi#5]
Will there be FMX version of the component?
Thank you!

**Comment by salvadordf** [comment]
No, sorry. I know nothing about FMX components but you can use the FMX component in DCEF3.

**Comment by kormizz** [comment]
Yep, I'm already using it. But the whole component is not maintained well. The Firemonkey part is just one small unit. It should not be hard to reuse it if you change your mind in a future.
Anyway, thank you!
