### ISSUE TITLE
how to add this argument to start CHROMIUM browser --disable-blink-features=AutomationControlled

### ISSUE THREAD

**Issue by marcelo386** [salvadordf/CEF4Delphi#504]
how to add this argument to start CHROMIUM browser --disable-blink-features=AutomationControlled

**Comment by salvadordf** [comment]
Add this before the GlobalCEFApp.StartMainProcess call in the DPR file : 
`GlobalCEFApp.DisableBlinkFeatures := 'AutomationControlled';`

You can also use GlobalCEFApp.AddCustomCommandLine for custom command line switches.

Please, use [our forum](https://www.briskbard.com/forum/) for more questions.
