### ISSUE TITLE
change cache folder path runtime

### ISSUE THREAD

**Issue by kayaliabd** [salvadordf/CEF4Delphi#505]
I am using the lib for multiuser profile app and I would like to update the cache folder path at running time.

**Comment by salvadordf** [comment]
Hi,

CEF allows you too set the [cache folder](https://github.com/salvadordf/CEF4Delphi/blob/16639d5ea5d5c6d5fddaa4c771504abb4fbb7641/demos/Delphi_VCL/MDIBrowser/uMainForm.pas#L89) before the GlobalCEFApp.StartMainProcess call or before [creating the request context](https://github.com/salvadordf/CEF4Delphi/blob/16639d5ea5d5c6d5fddaa4c771504abb4fbb7641/demos/Delphi_VCL/MDIBrowser/uChildForm.pas#L179)

See the MDIBrowser demo for more information. Please, use [our forum](https://www.briskbard.com/forum/) for more questions.
