### ISSUE TITLE
libcef.dll  serious error

### ISSUE THREAD

**Issue by KimK-Hack** [salvadordf/CEF4Delphi#508]
![스크린샷 2024-04-16 210333](https://github.com/salvadordf/CEF4Delphi/assets/80802067/dec29a9c-12ff-4a5e-88ff-1442dd5953ea)

I want to go down because I want to use 92.0.27.0, but if I build and run the demo after building and installing the package, an error saying it is not compatible appears.

The latest Chromium builds and runs well, but I have to go down to an older version, so it's Windows 11.

**Comment by salvadordf** [comment]
Hi,

You currently have a newer version of CEF4Delphi installed in Delphi but you need to use the CEF4Delphi version that supports  CEF 92.0.27.

[This is the CEF4Delphi release that you need](https://github.com/salvadordf/CEF4Delphi/releases/tag/92.0.4515.159).

Download the sources and the binaries using the links in the release announcement. [This is the link](https://github.com/salvadordf/CEF4Delphi/archive/refs/tags/92.0.4515.159.zip) to the CEF4Delphi sources.

These are the CEF binaries you need :
- [Windows 32 bits](https://cef-builds.spotifycdn.com/cef_binary_92.0.27%2Bg274abcf%2Bchromium-92.0.4515.159_windows32.tar.bz2)
- [Windows 64 bits](https://cef-builds.spotifycdn.com/cef_binary_92.0.27%2Bg274abcf%2Bchromium-92.0.4515.159_windows64.tar.bz2)

Uninstall the CEF4Delphi version currently installed in your PC and then follow [this guide](https://github.com/salvadordf/CEF4Delphi/wiki/Installation-in-Delphi) to install the CEF4Delphi version you just downloaded.

Don't hesitate to use [our forum](https://www.briskbard.com/forum/) for more questions.

**Comment by KimK-Hack** [comment]
---------------------------
Error
---------------------------
CEF binaries missing !



The missing files are :

vk_swiftshader.dll

vk_swiftshader_icd.json

vulkan-1.dll
---------------------------
OK
---------------------------

92.0.4515.159
vk_swiftshader.dll
vk_swiftshader_icd.json
vulkan-1.dll

There is no file called. If you take this from the latest file and insert it, it will be the same

Unsupported CEF version !

Use only the CEF binaries specified in the CEF4Delphi Readme.md file at https://github.com/salvadordf/CEF4Delphi

Expected libcef.dll version : 117.2.4.0

Found libcef.dll version : 92.0.27.0

The message box appears the same.

All IDE packages have been removed. Even after reinstalling 5 times, it’s the same

**Comment by salvadordf** [comment]
Let's continue this conversation in [this forum thread](https://www.briskbard.com/forum/viewtopic.php?t=2278).

**Comment by KimK-Hack** [comment]
C:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl

Even though I removed everything related to CEF4Delphi, it's still the same.

CEF binaries
chromium-92.0.4515.159

vk_swiftshader.dll
vk_swiftshader_icd.json
vulkan-1.dll

Is it normal not to have one?
Even if I reinstall and delete it properly, it's the same. This seems like a serious problem.
