### ISSUE TITLE
ResponseFilterBrowser demo run error in delphi7?

### ISSUE THREAD

**Issue by xtfnpgy** [salvadordf/CEF4Delphi#511]
procedure TResponseFilterBrowserFrm.Chromium1GetResourceResponseFilter(      Sender    : TObject;
                                                                       const browser   : ICefBrowser;
                                                                       const frame     : ICefFrame;
                                                                       const request   : ICefRequest;
                                                                       const response  : ICefResponse;
                                                                       out   Result    : ICefResponseFilter);
begin
  if not(FRscCompleted) and (response <> nil) and IsMyResource(request) then
  begin
    Result      := FFilter;  //error in here 
    FFilterInit := True;
    CheckResponseHeaders(response);
      UpdateRscEncoding(response.MimeType, response.GetHeaderByName('Content-Type'));
  end
  else
    Result := nil;
end;

when I delete the line "Result      := FFilter;",it can be run normal.

![1715764935540](https://github.com/salvadordf/CEF4Delphi/assets/14869366/3f961c00-aa01-4b52-8258-b0c760047af5)

**Comment by salvadordf** [comment]
Hi,

Only a few demos are ready to be used in Delphi 7 : SimpleBrowser, SimpleBrowser2 and MiniBrowserD7.

Older Delphi versions have issues with interface assignments and this is one example. ResponseFilterBrowser works with Delphi 2010 and newer but it has issues in older versions.

Install **Lazarus** and open the **demos\Lazarus_Windows\ResponseFilterBrowser** demo.
