### ISSUE TITLE
Broken binary URL CEF 125.0.22 for Linux x86_64

### ISSUE THREAD

**Issue by zamronypj** [salvadordf/CEF4Delphi#516]
Can not download URL mentioned in README.

[Binary Linux x86_64](https://cef-builds.spotifycdn.com/cef_binary_125.0.22%2Bgc410c95%2Bchromium-125.0.6422.142_linux64.tar.bz2)

**Comment by salvadordf** [comment]
The automated build system at Spotify failed, I don't work for that company and I can't fix this issue.

In this case you can still use the [previous binaries](https://cef-builds.spotifycdn.com/cef_binary_125.0.21%2Bgc8b1a8c%2Bchromium-125.0.6422.142_linux64.tar.bz2) for Linux.

**Comment by salvadordf** [comment]
The CEF 125.0.22 binaries for Linux are available now.
