### ISSUE TITLE
 Google Street View problem

### ISSUE THREAD

**Issue by htoujani** [salvadordf/CEF4Delphi#52]
I'm using MimiBrowser demo with this url : https://developers.google.com/maps/documentation/javascript/examples/streetview-embed?hl=fr

the page freeze long time.
Why ?
Thanks for your help.

**Comment by salvadordf** [comment]
I just used MiniBrowser with that URL and it loads completely in 2-3 seconds even without setting a cache directory.

Are you behind a firewall?
Can you test other browsers like Chrome, Chromium or the sample CEF application ?
http://opensource.spotify.com/cefbuilds/cef_binary_3.3112.1656.g9ec3e42_windows32_client.tar.bz2

**Comment by htoujani** [comment]
I did not explain the problem well, the page loads very quickly, but the street view takes time and during this time you can't do anything on the page.
With the CEF sample application, it works fine.
Thanks.

**Comment by salvadordf** [comment]
This is an old issue that I couldn't reproduce. Please, reopen if someone can provide more details.
