### ISSUE TITLE
CEF 126 proxy ERR_INVALID_AUTH_CREDENTIALS

### ISSUE THREAD

**Issue by rodendron** [salvadordf/CEF4Delphi#520]
Hi,

CEF126 has error in all demos (test on MiniBrowser) with all proxy type:

err_invalid_auth_credentials (-338)

I am using the same data wich works in other versions (last my test was in old 117).

**Comment by salvadordf** [comment]
This looks to be related to [this CEF issue](https://github.com/chromiumembedded/cef/issues/3603)

**Comment by salvadordf** [comment]
Try setting GlobalCEFApp.DisableChromeLoginPrompt to TRUE before the GlobalCEFApp.StartMainProcess call in the DPR file.

**Comment by salvadordf** [comment]
The latest CEF4Delphi version sets the GlobalCEFApp.DisableChromeLoginPrompt value to true by default.

**Comment by rodendron** [comment]
@salvadordf thank you very much
