### ISSUE TITLE
Load a non-installed .pfx certificate

### ISSUE THREAD

**Issue by lucasmence** [salvadordf/CEF4Delphi#521]
Hello,

Is it possible to select a certificate file (.pfx) to authenticate a page? In other words, select a certificate that is not installed.

Thanks!

**Comment by salvadordf** [comment]
Hi,

No. The certificate must be installed in the system and its issuer must be trusted by the server. 
Chromium shows a list of preselected certificates installed in the operating system to authenticate the user.

Please, use [our forum](https://www.briskbard.com/forum/) for more questions.
