### ISSUE TITLE
Using the source code of CEF 127.3.1 and the binary files in the folder, the FMX version crashes

### ISSUE THREAD

**Issue by chenzhifeng0025** [salvadordf/CEF4Delphi#524]
The version I am using is: CEF4Delphi uses CEF 127.3.1 which includes Chromium 127.0.6533.100. I downloaded it from the latest version on GitHub, and the binary files are from the download link in the Readme file: [Windows 32 bits](https://cef-builds.spotifycdn.com/cef_binary_127.3.1%2Bg6cbb30e%2Bchromium-127.0.6533.100_windows32.tar.bz2). I used the debug files from this download and compiled the FMXTabbedBrowser.dproj project. The project compiles and runs to the interface normally, but when it displays the interface, it keeps loading the URL and then suddenly crashes and exits. I have not modified any code in this source. What could be the issue? I have been puzzled for a long time. What am I doing wrong?

**Comment by salvadordf** [comment]
Hi,

Copy the contents of the _Release_ and _Resources_ directories from the CEF binaries. 
https://github.com/salvadordf/CEF4Delphi/wiki/Before-you-run-the-demos

The debug files in the binaries cause issues.

**Comment by chenzhifeng0025** [comment]
Thank you, the issue has been resolved.
