### ISSUE TITLE
CEF 109 for windows7 crashes at closing application.

### ISSUE THREAD

**Issue by mytvdat** [salvadordf/CEF4Delphi#531]
The last version of CEF with Windows 7 support was CEF 109,but it can not play all videos.it crashes at closing application.
Chromium v94 support Windows 7, 8.0 or 10,but it can play all videos. my windows uses Chromium v94 ,it works well,not any bugs.

**Comment by salvadordf** [comment]
Some Chromium versions and Chrome have all the video codecs but the CEF binaries at Spotify only have the open source codecs. Try several YouTube short or normal videos and you'll play them normally.

Use the CEF4Delphi demos as a template for your application to avoid shutdown errors.

Consider using Windows 10/11 and upgrading to the latest version of CEF4Delphi.

CEF 109 and Windows 7 are no longer supported.  Closing this issue.

**Comment by mytvdat** [comment]
you do not know all cef4delphi crashes at closing application.
