### ISSUE TITLE
please tell me how to play media

### ISSUE THREAD

**Issue by wwq0071** [salvadordf/CEF4Delphi#533]
please tell me how to play media? like mp4 resources. or like this link https://v.youku.com/v_show/id_XNjQyMDc1NzkxMg==.html?spm=a2hje.13141534.app.5~5!6~A&scm=20140719.rcmd.238959.show_dece837b948642578ab1&s=dece837b948642578ab1

**Comment by salvadordf** [comment]
Please, read [this page](https://www.briskbard.com/index.php?lang=en&pageid=cef#codecs) to know why the CEF binaries only play the media that uses open source codecs.

I just added this information to the [Wiki](https://github.com/salvadordf/CEF4Delphi/wiki/Frequently-asked-questions)
