### ISSUE TITLE
784275408@qq.com

### ISSUE THREAD

**Issue by Leewx820** [salvadordf/CEF4Delphi#535]
![image](https://github.com/user-attachments/assets/6c68820b-eab7-469f-b213-ebd8c979c38b)
The FMXTabbedOSRBrowser sample has blurry fonts on the window when the window size changes at 150% DPI in Windows 10！

**Comment by Leewx820** [comment]
![image](https://github.com/user-attachments/assets/6fa48271-fb72-4f17-8fc8-00a27d57fdf2)
The version I am using

**Comment by salvadordf** [comment]
Set TFMXBufferPanel.HighSpeedDrawing to False or download the latest CEF4Delphi version.

**Comment by Leewx820** [comment]
I found that the same problem occurs on some Windows 7 computers, even when setting HighSpeedDrawing to False, but I cannot use the new version because the software still needs to run on Windows 7
