### ISSUE TITLE
browser always store cache and cookies

### ISSUE THREAD

**Issue by epneeh** [salvadordf/CEF4Delphi#536]
i am using cef4delphi version 129

this is my dpr

```
GlobalCEFApp := TCefApplication.Create;
  GlobalCEFApp.EnableMediaStream := true;
  GlobalCEFApp.DeleteCache := true;
  GlobalCEFApp.DeleteCookies := true;

  GlobalCEFApp.Cache:='';
  GlobalCEFApp.PersistSessionCookies := false;


  if GlobalCEFApp.StartMainProcess then
  begin
    Application.Initialize;
    Application.MainFormOnTaskbar := true;
    Application.CreateForm(TfrmBrowser, frmBrowser);
    Application.Run;
  end;
  GlobalCEFApp.Free;
```

but after close and open browser always stored cache/cookies

**Comment by salvadordf** [comment]
GlobalCEFApp.DeleteCache is used to delete the cache directory set in GlobalCEFApp.Cache.

Set the GlobalCEFApp.Cache property with a local directory.

For more questions please use our [forum](https://www.briskbard.com/forum/).
