### ISSUE TITLE
Second process launch an external chromium interface

### ISSUE THREAD

**Issue by zerabba** [salvadordf/CEF4Delphi#537]
I'm upgrading the CEF4Delphi version from version 107.0.5304.88 to the latest release version (129.0.6668.101) in a VCL application.

When I launch the first process, all is fine. But when we launch a second process and the first one is still active, the second process cannot launch the chromium correctly inside the application main windows.

To reproduce the issue, it's quite simple. I took for example the demo CEF4Delphi-129.0.6668.101\demos\Delphi_VCL\SubProcess, the only thing I changed is that I uncomment for the cef binaries:

![image](https://github.com/user-attachments/assets/d9521d39-5c11-44bd-86f1-c7ab3af2b6bd)

then you just need to build in Win64/Debug and launch two times the SimpleBrowser.exe.

Second process launched will look like this:

![image](https://github.com/user-attachments/assets/fbf7fd01-db98-4b8f-b801-b911cab31490)

Do you know why the second process is launched like this?

I was not the case with the version 107.

If you need more informations or do some testing don't hesitate to ask me.

Thanks for your help and best regards

**Comment by salvadordf** [comment]
Read the information in these links about the limitations when we try to launch several instances of the same application with a CEF browser :
https://www.briskbard.com/forum/viewtopic.php?t=2208
https://stackoverflow.com/questions/78652092/cef4delphi-application-cant-run-two-instances
