### ISSUE TITLE
madExcept 5.1.5 will report The Application seems to be frozen. If enabled Check for frozen main thread. 

### ISSUE THREAD

**Issue by wqmeng** [salvadordf/CEF4Delphi#540]
Hello,

Just let you know that,
madExcept 5.1.5 will report The Application seems to be frozen. If enabled Check for frozen main thread. 

I do not think it is a bug, just want to know if it could be improved.

Thank you very much.

**Comment by salvadordf** [comment]
Hi,

madReport should only be enabled for the main application process and not for the CEF subprocesses because they _seem_ frozen but that's an expected behavior.
