### ISSUE TITLE
App error on Windows startup

### ISSUE THREAD

**Issue by petko** [salvadordf/CEF4Delphi#57]
There is some strange problem with my app: if it is installed in the Program Files directory and it set to run at Windows startup (shortcut placed in the Startup folder), I get the following error on startup:

CEF framework files missing! 
Make sure all the CEF framework files can be found in this directory:
[app directory]

The files are exactly there and the app runs if I start it manually. If I move the installation out of Program Files (x86), it works as expected on startup. If I use MiniDemo, it works in both program files and random locations on the disk.

I am wondering what could cause this? The app uses sub process for the CEF library.

**Comment by salvadordf** [comment]
I just uploaded a crash_reporter.cfg and a simplebrowser to the SubProcess demo. 

All of them form a complete browser demo and after following your steps I couldn't reproduce your error. 

I copied the CEF binaries, both EXEs and the "crash_reporter.cfg" file inside "Program Files (x86)" subfolder ("Archivos de programa (x86)" in my Spanish Windows). 

I created a link and copied to the startup folder. After rebooting the simplebrowser is executed normally without errors.

Maybe some other part of your program is changing the current directory for the current process and you need to set GlobalCEFApp.SetCurrentDir to True in the main exe and in the subprocess.

I had some difficulties with the crash_reporter.cfg when it was introduced in CEF months ago and I remember that I needed to set add a ".\" before the ExternalHandler value.

**Comment by petko** [comment]
Well, I really can't find what it is, but I found out that setting the Framework, Resource and Locales dirs explicitly to an absolute value fixes the problem, so I will use this workaround.

**Comment by jjjude** [comment]
I have the same problem!
Tell me in detail how to fix it?
