### ISSUE TITLE
 CEF framework files missing!

### ISSUE THREAD

**Issue by jjjude** [salvadordf/CEF4Delphi#59]
When start demo MiniBrowser become error  CEF framework files missing!
Tell me in detail how to fix it?

**Comment by salvadordf** [comment]
Please, read this web page : 
https://www.briskbard.com/index.php?lang=en&pageid=cef

You have to download the CEF3 binaries linked in the front page of this project : 
https://github.com/salvadordf/CEF4Delphi

Decompress the package and copy the contents of the **Release** and **Resources** directories to the directory of your application's exe. Here's an screenshot of the final layout : 
https://www.briskbard.com/images/ceflayout.png
