### ISSUE TITLE
GetElementsByTagName

### ISSUE THREAD

**Issue by virtelot** [salvadordf/CEF4Delphi#62]
Is there any opportunity to get element by name or tag name? Element doesn't have ID.
I'm using a tag name now in WebBrowser. But did not find any solution in CEF :(
`
a:=webbrowser1.oleobject.document.GetElementsByTagName('select').item(0);`

**Comment by salvadordf** [comment]
Please, use the CEF4Delphi forum for these questions : https://www.briskbard.com/forum/index.php

...and yes, there are several ways to search for elements in the DOM using CEF4Delphi.
