### ISSUE TITLE
All demos should output the exe to the same folder

### ISSUE THREAD

**Issue by raelb** [salvadordf/CEF4Delphi#67]
All demos should output their exe's to the same shared folder, so that cef binaries only need to be updated in one place.  This will save time and space...

Alternatively, a simple program to copy new binaries to each demo folder would also be helpful. 

What do you think?

**Comment by salvadordf** [comment]
The latest update includes your suggestion. Thanks! :-D

**Comment by raelb** [comment]
Thanks! It is good
