### ISSUE TITLE
JSExtension fails to register the extension

### ISSUE THREAD

**Issue by salvadordf** [salvadordf/CEF4Delphi#68]
The JSExtension demo fails to register the extension with the latest CEF3 binaries and the browser remains blank.

This demo worked with previous versions of the CEF3 libraries.

**Comment by gouling** [comment]
New version，Has the problem been solved?

**Comment by salvadordf** [comment]
This bug is still present. I'll take a look as soon as I can.

**Comment by gouling** [comment]
Thank you very much

**Comment by salvadordf** [comment]
I'm currently investigating why this demo is not working. The problem appeared in the commit made in Oct 26, 2017 with the title "Update to CEF 3.3202.1674.g2a991c4"

This is the last CEF4Delphi version where this demo was working : 
https://github.com/salvadordf/CEF4Delphi/tree/87d11774bd1b4f34019127d95b3ab38bbb8d42b8
It used CEF 3.3163.1671.g700dc25 at that time.

I'll keep looking...

**Comment by gouling** [comment]
Thank you, Look forward to solving

**Comment by salvadordf** [comment]
In a few minutes I'll add a forum message with all the changes. Please read it.

**Comment by gouling** [comment]
Great, thank you.

**Comment by gouling** [comment]
Remove some unnecessary code, only keep the registration event(Onwebkitinitialized), only call the Onwebkitinitialized method, the page will not load. 

For example(D2010)：
1. Delete file uSimpleTextViewer。
2. Remove from files uJSExtension TPanel。

For debug code(D2010)：

JSExtension.dpr
-------------------
GlobalCEFApp := TCefApplication.Create;
GlobalCEFApp.OnWebKitInitialized := GlobalCEFApp_OnWebKitInitialized;
if GlobalCEFApp.StartMainProcess then
begin
	Application.Initialize;
	Application.MainFormOnTaskbar := True;
	Application.CreateForm(TJSExtensionFrm, JSExtensionFrm);
	//Application.CreateForm(TSimpleTextViewerFrm, SimpleTextViewerFrm); //Delete file
	Application.Run;
end;
 
GlobalCEFApp.Free;
-------------------

uJSExtension.pas
-------------------
Remove Control： Timer、Nav Panel
Remove Method： Chromium1BeforeContextMenu
Chromium1.LoadURL(Edit1.Text) to FormShow Chromium1.DefaultUrl := 'http://localhost' 
-------------------

only change, page will not load。Thank you for keep looking。

**Comment by salvadordf** [comment]
Reopening because there's a bug when you compile in release mode.

**Comment by salvadordf** [comment]
Please download CEF4Delphi again. It works correctly in debug and release mode now.

**Comment by gouling** [comment]
Beautiful, perfect.Thank you very much.
