### ISSUE TITLE
SimpleOSRBrowser demo does not work for me (XE4)

### ISSUE THREAD

**Issue by raelb** [salvadordf/CEF4Delphi#69]
I just get a black window

![image](https://user-images.githubusercontent.com/13108198/32618185-aa2e72c2-c57f-11e7-8e7d-38575bddd63c.png)

Using the latest code from Graphics32.

When opening the project in XE4 I get this error:

![image](https://user-images.githubusercontent.com/13108198/32618264-d9ba993a-c57f-11e7-9690-5620e5784628.png)

However, I don't suppose it has to do with the problem..

**Comment by salvadordf** [comment]
The TForm.OnAfterMonitorDpiChanged has nothing to do with this error. That's an event for high DPI support that was introduced in older Delphi versions.

I checked again with Delphi 10.2 (32bit) and it works. 

I'm using a version of Graphics32 that's only a few months old but I think this is a problem with the synchronization of TChromium.CreateBrowser and GlobalCEFApp.GlobalContextInitialized.

TChromium.CreateBrowser needs to be called after GlobalCEFApp.GlobalContextInitialized is set to true. This should be done with synchronization objects but for simplicity I used a simple timer that tries to call TChromium.CreateBrowser every 300ms until it can create the browser (TChromium.CreateBrowser checks GlobalCEFApp.GlobalContextInitialized internally).  

I'll check again with the latest Graphics32 version as soon as I can.

**Comment by raelb** [comment]
For one, the CreateBrowser was not succeeding. I made some changes to the code (increase timer to 2000s). Then the CreateBrowser does succeed, however, the problem still continues. Nothing happens.

    procedure TForm1.Timer1Timer(Sender: TObject);
    begin
      Timer1.Enabled := False;
    
      if chrmosr.CreateBrowser(nil, '') then
      begin
        ShowMessage('Created');
        chrmosr.InitializeDragAndDrop(PaintBox);
    
        if chrmosr.Initialized then
        begin
          chrmosr.WasHidden(False);
          chrmosr.SendFocusEvent(True);
        end
      end
       else
        Timer1.Enabled := True;
    end;

    procedure TForm1.FormShow(Sender: TObject);
    begin
      if chrmosr.Initialized then
        begin
          chrmosr.WasHidden(False);
          chrmosr.SendFocusEvent(True);
        end
       else
        begin
          chrmosr.Options.BackgroundColor := CefColorSetARGB($FF, $FF, $FF, $FF); // opaque white background color
    
          //if chrmosr.CreateBrowser(nil, "") then
          //  chrmosr.InitializeDragAndDrop(PaintBox)
          // else
            Timer1.Enabled := True;
        end;
    end;

**Comment by salvadordf** [comment]
I tested the latest version of the Graphics32 component in Delphi 10.2 and it works fine, except for the mouse wheel event. 

I uploaded a new version of this demo fixing some focus bugs and moving the mouse wheel code to AppEventsMessage.

Are you using a high DPI monitor ?

If that's the case, there's a known rounding issues with the paint procedure in this demo explained in the comments.

**Comment by salvadordf** [comment]
The latest version of this demo uses a new component called TBufferPanel instead of the PaintBox32 from Graphics32. 
It also has a much improved paint function that works correctly with high dpi monitors. 
Please, try it.

**Comment by raelb** [comment]
Thanks Salvador - that works!

However I noticed some problems:

1) If I type into google, "RightNote" and then click on the link (www.bauerapps.com/rightnote), after the page loads and I resize the App window, the webpage image will correctly expand. However, if after I start the app, I type into the edit box "http://www.bauerapps.com/rightnote", then press Go, after the page loads, the webpage image will not expand if I expand the App Window.

2) The snapshot function only takes a picture of the visible window, not the whole webpage. (I understood it should take the whole webpage...)

3) After loading the RightNote webpage and taking an image, I get an AV when closing the app.

**Comment by salvadordf** [comment]
About the problems : 

1. There's a synchronization problem between the windows paint and resize messages, and the CEF paint events. The official CEF sample application uses opengl and it does a few things differently. I'll see what I can do. For now, it seems to fix itself if you resize the app a little bit more.
2. CEF only draws what's visible. If you want the whole page you can stretch the panel but some web pages are bigger than the CEF drawing size limits.
3. There is a known bug in the destruction of TChromium in OSR mode. Sometimes it's necessary to add a timer and wait 1-2 seconds after the TChromium's destruction to close the app.

**Comment by salvadordf** [comment]
I uploaded more fixes for some of the resize issues but after more tests with the official CEF sample application it seems that the problem 1 you discovered is a CEF3 issue in OSR mode with high DPI monitors.
I added an issue in the CEF3 project : 
https://bitbucket.org/chromiumembedded/cef/issues/2305/cefclient-in-osr-mode-stops-painting-in

**Comment by raelb** [comment]
Great, thanks

**Comment by salvadordf** [comment]
The latest CEF 3.3239.1723.g071d1c1 update seems to have resolved this issue. 
Please, update to the latest CEF4Delphi version.
