### ISSUE TITLE
Please add

### ISSUE THREAD

**Issue by Topgen** [salvadordf/CEF4Delphi#72]
Hi!
Please add support proxy Socks5
and
in the demo dynamic creation of browser.
Thank

**Comment by salvadordf** [comment]
Sorry for the long delay.

Socks5 is already implemented. You only need to add **socks5://** to the proxy address.
Read these web pages for more info : 
https://www.briskbard.com/forum/viewtopic.php?f=8&t=243
https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage.md#markdown-header-proxy-resolution

3 demos create browsers dynamically : MDIBrowser, ToolBoxBrowser and TabbedBrowser.
