### ISSUE TITLE
Open in new window problem

### ISSUE THREAD

**Issue by realaaaaa** [salvadordf/CEF4Delphi#73]
I saw there's a problem when we tried to open link in a new window.
The current window will always stay at the front the pop window  will not show as a active window.
How to make the popup window at the top ?
Thanks ,its a  good chrome browser for delphi

**Comment by salvadordf** [comment]
Right now CEF4Delphi has some issues with the popup windows created automatically by CEF3. 
I should create a demo about custom popup windows created in Delphi.

Perhaps you can use EnumChildWindows , ShowWindow and BringWindowToTop to bring that window to the top.

**Comment by realaaaaa** [comment]
thx for your fast response. i can see same problem with cef3

**Comment by salvadordf** [comment]
The last commit fixed the issue with popup windows. 

The MiniBrowser demo can show popup windows created automatically by CEF but the rest of the demos block them for simplicity. 

It's recommended to create your own child windows for the popups as described here : 
https://www.briskbard.com/forum/viewtopic.php?f=8&t=313#p1291
