### ISSUE TITLE
Access Violation after GlobalCEFApp.Free

### ISSUE THREAD

**Issue by NesDmitrijj** [salvadordf/CEF4Delphi#74]
Hi!
I'm using CEF loading from a DLL. After calling GlobalCEFApp.Free, after about 20 seconds an "Access Violation" error occurs.
I prepared an example for reproducing the error.
Run cefDemoExe.exe and click "Init". Then click the "UnInit" button. Wait 15-30 seconds.
[GIT.zip](https://github.com/salvadordf/CEF4Delphi/files/1534601/GIT.zip)

**Comment by salvadordf** [comment]
I've never tried to put CEF4Delphi inside a DLL but some other users might help you in the forum.
 
https://www.briskbard.com/forum/
