### ISSUE TITLE
Multi-browser

### ISSUE THREAD

**Issue by kewinbrand** [salvadordf/CEF4Delphi#75]
Is possible to open more than one browser in a single application?
If so, how can I accomplish it?

Thank you.

**Comment by salvadordf** [comment]
Yes, it's possible. The MDIBrowser, TabbedBrowser and ToolBoxBrowser demos show you how to do it.

Please, use the forum for questions : 
https://www.briskbard.com/forum/

**Comment by kewinbrand** [comment]
Ok thank you
