### ISSUE TITLE
Chromium DLLs with mp4 codecs

### ISSUE THREAD

**Issue by eduardobento** [salvadordf/CEF4Delphi#76]
Hi,

Is there any easy way to get Chromium current DLLs compiled with h264 codec ?

Thanks.

**Comment by salvadordf** [comment]
Hi Eduardo,

I'm not aware of any website distributing those DLLs but you can compile them yourself.
Visual Studio is free and the instructions are here : 
http://magpcss.org/ceforum/viewtopic.php?f=6&t=13515

You will need a really powerful computer with lots of RAM. It takes several hours to compile them on a Intel I7 cpu. 

MP3 and MP4 will be enabled by default in the official libraries when Chromium 64 is released in Jan 23rd, 2018. 
Read more about this here : 
https://bugs.chromium.org/p/chromium/issues/detail?id=746579

**Comment by eduardobento** [comment]
Thanks @salvadordf ! 

By the way, excelent job here in CEF4D, great project.

**Comment by nextglory** [comment]
@salvadordf , “You will need a really powerful computer with lots of RAM. It takes several hours to compile them on a Intel I7 cpu” it is intimidating by reading your message :) ...

**Comment by nextglory** [comment]
@salvadordf, when the official libraries updated after Jan 23rd, 2018, will your CEF4Delphi library natively support that update? Do we have to download the binaries from http://opensource.spotify.com/cefbuilds/xxxxxxxxxxxxx ?

**Comment by salvadordf** [comment]
Just to clarify, that's the estimated release date for the Chromium 64 available here : 
https://www.chromium.org/developers/calendar

As you can see in the Chromium issue, this feature was going to be added in the version 62 but now it's announced for the version 64. 

I don't work for Google and I'm not a Chromium developer, and that means that I only know what's publicly available.

About the compilation time, I'm only repeating the information given in the official CEF3 forum. CEF3 and Chromium are **really** big projects and Visual Studio is not the fastest compiler.

As far as I know, CEF4Delphi shouldn't have to be modified if the codec support changes but I could be wrong...

I suppose the official CEF3 binaries will be available at Spotify, as always.

**Comment by astral2k5** [comment]
Regardin compilation time, it's very true you need some power and patience :)
I've compiled Chrome 47 last year on a I7 6700 with 8GB RAM and it took around 2-3 hours and more than 70GB space. Probably with latest Chrome it will take need more time and space :)

**Comment by astral2k5** [comment]
Regarding compilation, it is very true you need some power and patience :)
It took 3 hours and 70 GB to compile Chrome 47 last year on a I7 6700 8GB RAM.
