### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by alpires** [salvadordf/CEF4Delphi#77]
Hi guys, I have a problem here. When I open web.whatsapp.com and log in my accont with my celfone, if I close the application and open again, the session is gone and I have to make login again. Exist some way to avoid this?
Thanks

**Comment by salvadordf** [comment]
Cookies are stored in memory unless you set a cache directory in GlobalCEFApp.cache before the GlobalCEFApp.StartMainProcess call in the DPR file. 

Remember that cookies have a limited lifetime and web sessions close automatically.
