### ISSUE TITLE
Difference between methods

### ISSUE THREAD

**Issue by edsonalvesan** [salvadordf/CEF4Delphi#82]
Hello,
What is the difference between executing the methods

Chromium1.ExecuteJavaScript ();
for
Chromium1.Browser.MainFrame.ExecuteJavaScript ();

**Comment by salvadordf** [comment]
Hi,

Basically they are the same but I added TChromium.ExecuteJavaScript and many other methods to TChromium to make them a little bit easier and safer. 

As you can see, TChromium.ExecuteJavaScript checks that the browser is initialized and it also checks if there's a MainFrame before calling one of its methods. 

Please, use the CEF4Delphi forum for questions : 
https://www.briskbard.com/forum
