### ISSUE TITLE
is there any plans for  cef_message_router in cef4delphi?

### ISSUE THREAD

**Issue by zhangdongfarmer** [salvadordf/CEF4Delphi#83]
hi, many thanks to your respectful work on cef4delphi. Is there any official plans to introduce message_router in cef4delphi? because this feature is very useful when use javascript to interact with browser process directly.

thank you!  @salvadordf

**Comment by salvadordf** [comment]
Hi,

CEF4Delphi is a C API wrapper for the CEF3 project and cef_message_router doesn't belong to the set of classes, types and functions described in the C API.

I just took a quick look but it seems to be a class built on top of the C API to make JavaScript and C++ communications easier.

Right now you have 9 CEF4Delphi demos with examples of JavaScript and Delphi communications, functions, etc.

**Comment by zhangdongfarmer** [comment]
yeah, thank u for your reply. I now solve this problem with inter process message communication between js from render process and delphi code from browser process.

thank you again for your excellent work.
