### ISSUE TITLE
Unsupported CEF version

### ISSUE THREAD

**Issue by mass0001** [salvadordf/CEF4Delphi#86]
Use only the CEF3 binaries specified in the CEF4Delphi Readme.md file at 
https://github.com/salvadordf/CEF4Delphi
...
...
I did everythigs wthat i can do it. but it's not work.
I hope download that all in one files.
source + all binarys

can i ?
please.....

**Comment by salvadordf** [comment]
For the current CEF4Delphi version you have to download this file : 
http://opensource.spotify.com/cefbuilds/cef_binary_3.3239.1720.g1ad5e2a_windows32.tar.bz2

Decompress it and copy the **contents** of the **Release** and **Resources** directories to the **BIN** directory in CEF4Delphi.

This is how it should look : 
https://www.briskbard.com/images/ceflayout.png

I'm sorry but CEF3 updates the binaries too often and it takes too much time to upload them.
