### ISSUE TITLE
Support for Delphinus Packagemanager

### ISSUE THREAD

**Issue by Memnarch** [salvadordf/CEF4Delphi#87]
Hi,
Seems you're quite active on updating your implementation. I thought it might be a good idea to add it as a package to the Delphinus-PackageManager.

It is an OpenSourcePackagamanger for the Delphi IDE which runs on XE and newer(unlike GetIt).
https://github.com/Memnarch/Delphinus
My Blog with some more information on it:
http://memnarch.bplaced.net/
If you have any questions, don't hesitate to ask me :)

**Comment by salvadordf** [comment]
First of all, sorry for the extremely long delay.

I've added the "Delphinus-Support" tag and the json files. In a few days I'll create a new release which will include all those changes. 

Please, let me know if you need anything else.
