### ISSUE TITLE
Memory leak in DOMVisitor demo

### ISSUE THREAD

**Issue by salvadordf** [salvadordf/CEF4Delphi#89]
FastMM4 shows a memory leak in the DOMVisitor demo : 

> 13 - 20 bytes: DOMVisitor$ActRec x 1

This may be related to that leak : 
https://stackoverflow.com/questions/9282103/anonymous-method-in-project-leaks-memory

This leak only appears when you assign procedures to GlobalCEFApp events.

**Comment by PioPio2** [comment]
Hello Salvador, 

Is there any ETA for this bug ?

Many thanks and very good job with CEF4Delphi !!!
Alberto

**Comment by PioPio2** [comment]
Hi Salvador,
Did you have the chance to look into this bug ?

**Comment by salvadordf** [comment]
I'll try to make some time this weekend for this. Right now I'm very busy.

**Comment by PioPio2** [comment]
Thank you very much, Salvador

**Comment by PioPio2** [comment]
Thank yoy very much, Salvador. I can confirm this bug is fixed :-)
