### ISSUE TITLE
Support for D7?

### ISSUE THREAD

**Issue by raelb** [salvadordf/CEF4Delphi#9]
Hi,

Are you willing to add support for Delphi 7? I spent some time making the code compatible with D7 (based on DCEF3), and was pleased to see that there was not that much required. Not sure what your thoughts on that are.

I will highlight the main changes here. (Full source is attached)

- The most widespread change is OutputDebugString(PWideChar(...)) which needs PAnsiChar. It would help if this could be refactored into a separate debug procedure or unit (maybe in uCEFTypes).
- Definition for D7 types. (uCEFTypes)
- reference to -> {$IFDEF DELPHI12_UP}reference to{$ENDIF} 
- inline -> {$IFDEF SUPPORTS_INLINE} inline; {$ENDIF}
- TCefRTTIExtension -> {$IFDEF DELPHI14_UP}... {$ENDIF}
- IOUtils -> Commented out.
- Some small other changes

Thanks

[source_D7.zip](https://github.com/salvadordf/CEF4Delphi/files/769374/source_D7.zip)

**Comment by salvadordf** [comment]
The biggest problem is that I don't have a D7 license to test it. I'll take a look and merge it if you guarantee that it works on D7.

**Comment by raelb** [comment]
Oh, did Seattle not come with a license for D7? (At some point Delphi licenses included older versions...)

Anyway, could you refactor the OutputDebugString into a separate debug procedure, then I will download, make changes, and upload again. It will be a lot less changes.

**Comment by salvadordf** [comment]
I just have a Delphi 10 Starter license. I'm not sure I can use that with D7.
I'll change the OutputDebugString as soon as I can.

**Comment by raelb** [comment]
Ok, that makes sense. I think the older versions only come with a Pro license.
I'll wait for you.

**Comment by salvadordf** [comment]
Done. Now TCEFApplication has a new procedure to log messages called OutputDebugMessage. It logs he error message using cef_log too which creates a file called "debug.log" in the same folder as the application exe.

**Comment by raelb** [comment]
What about having a standalone `OutputDebugMessage` procedure in `uCEFApplication`?
That way the code is neater (does not need `if (GlobalCEFApp <> nil) then` every time OutputDebugMessage is called - put it in the procedure) and also allows you to output debug message in far off case that the error code is being called and GlobalCEFApp = nil.

**Comment by salvadordf** [comment]
Moved to uCEFMiscFunctions in the latest version of CEF4Delphi

**Comment by raelb** [comment]
Here are modifications for D7 compatibility.

[source_D7.zip](https://github.com/salvadordf/CEF4Delphi/files/772020/source_D7.zip)

Note: In uCEFApplication.pas  - TCefApplication.InitializeLibrary I defined out the code but did not replace.

**Comment by salvadordf** [comment]
I added all your modifications. Please check that it works in Delphi 7.

Thank you very much! :smiley:

**Comment by raelb** [comment]
Just checked and it is working in D7 and XE4.
Thank you!

**Comment by brianjford** [comment]
It's working in Delphi 2007 as well..  I just use the D7 project to install the component into the IDE.
