### ISSUE TITLE
TCefRTTIExtension.Register crashes the subprocess

### ISSUE THREAD

**Issue by srmanc** [salvadordf/CEF4Delphi#90]
I want to register an extension in the subprocess by calling 
TCefRTTIExtension.Register('myextensionname',TMyExtensionClass);

TMyExtensionClass is a simple class with class procedures.
TChromiumMessageCallback=class
  class procedure hello(welcomeMsg,from: string);
end;

I am calling TCefRTTIExtension.Register in the subprocess in the OnWebKitInitialized event. SingleProcess is set to false.

When I load a page in the main process, i get a runtime error and the subprocess crashes.

This used to work with DCEF3.

**Comment by salvadordf** [comment]
Hi,

TCefRTTIExtension no longer works but I created several demos in the \demos\JavaScript directory to do the same without that class.

This problem was detected a few months ago :  
https://github.com/salvadordf/CEF4Delphi/issues/68
