### ISSUE TITLE
Selected text

### ISSUE THREAD

**Issue by bdwilton** [salvadordf/CEF4Delphi#91]
Is there a function or mechanism that can be used to get the selected text on a web page ?

Also would be interested in how to highlight specific text if that was possible ?

Regards,
Brett

**Comment by salvadordf** [comment]
To get the selected text you can use the TChromium.ClipboardCopy procedure or use a DOM visitor to call document.SelectionAsText. The DOMVisitor demo has all the code you need for that.

There are several ways to highlight text with javascript that can be used in CEF4Delphi if you use the TChromium.ExecuteJavaScript procedure.

Please, use the forum for questions : 
https://www.briskbard.com/forum/index.php

**Comment by bdwilton** [comment]
Much appreciated, I will look into both
