### ISSUE TITLE
set cookie

### ISSUE THREAD

**Issue by lovemit** [salvadordf/CEF4Delphi#94]
How do I specify cookies and then go directly to the login success page?
Thank you very much!

**Comment by salvadordf** [comment]
The CookieVisitor demo might have what you are looking for.
Please, use the forum for questions : 
https://www.briskbard.com/forum/

**Comment by lovemit** [comment]
I have seen this example, but I haven't tested it successfully. I will try again. If there is anything I don't understand, I will go to BBS. Thank you very much.
