### ISSUE TITLE
Upload File

### ISSUE THREAD

**Issue by beryindo** [salvadordf/CEF4Delphi#95]
how to upload file with CEF4, I try with js but not work
```
  chromium1.Browser.MainFrame.ExecuteJavaScript(
    'var b = document.getElementsByClassName("upload-file"); '+
    'b[0].click();', chromium1.Browser.MainFrame.Url,0);
```

**Comment by salvadordf** [comment]
Search "How to submit the form in Javascript" in google.
https://stackoverflow.com/questions/9855656/how-to-submit-a-form-using-javascript

Please, use the forum for questions : 
https://www.briskbard.com/forum/
