### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by azzahrah** [salvadordf/CEF4Delphi#96]
Helo

Is this support FMX android version?, i try install and add platform for android plat not available?

**Comment by salvadordf** [comment]
I'm sorry but I only have a Delphi Starter license and I can only support Windows in 32 bit. In addition to licensing issues, I know nothing about programming for Android, Linux or MacOS.

However, it shouldn't be too difficult to add support for other platforms and I would gladly help anyone interested. 

The CEF3 project has an automatic build system for the libraries with versions for Windows, Linux and MacOS. The Android binaries would have to be compiled manually.
