### ISSUE TITLE
cookievisitor sample

### ISSUE THREAD

**Issue by lovemit** [salvadordf/CEF4Delphi#97]
Excuse me, the registration of BBS is not successful, it may be the email address.
I watched cookievisitor this example, only Chromium1AfterCreated this event to perform in the launcher, other useful methods and events are not executed, don't know where is the problem, hope to get further solutions, thank you very much!

**Comment by salvadordf** [comment]
Please, try another free email provider from this list : 
https://www.briskbard.com/blog/?q=node/24

If you still have problems, try any of these free VPN providers : 
https://www.briskbard.com/blog/?q=node/47

I tried the CookieVisitor demo successfully and it showed all the cookies available at that moment.

Please, read the original CEF3 code comments to know how to use the cookie manager and the cookie visitor : 
https://github.com/chromiumembedded/cef/blob/master/include/capi/cef_cookie_capi.h

**Comment by lovemit** [comment]
@salvadordf The test was successful. Thank you very much.This one is reading cookies, and I'll learn how to set up cookies.
