### ISSUE TITLE
OnTooltip not working

### ISSUE THREAD

**Issue by petko** [salvadordf/CEF4Delphi#99]
OnTooltip event seems never to be called. I've tried it both in my project and by setting an event handler in the PopupBrowser (main window). Is there something special that should be done for it to work or is this a bug?

**Comment by salvadordf** [comment]
I just tested the OnTooltip event in the PopupBrowser main form and it works fine. 

Add this code to the OnTooltip event in uMainForm.pas : 
`  CEFWindowParent1.hint     := text;
  CEFWindowParent1.ShowHint := (length(text) > 0);
  Result := True;`

Then load google.com and move the mouse over the search box.

**Comment by petko** [comment]
There is a tooltip, but this is the browser tooltip, not application one. You can check it changing `hint` to something else or by trying to set a breakpoint in the event. It is never called on my machine, at least..

**Comment by salvadordf** [comment]
You're right! This event is not called in normal mode but it works in OSR mode. 

I found an unresolved CEF issue about this : 
https://bitbucket.org/chromiumembedded/cef/issues/783

It seems that the tooltips are handled internally in normal mode.
